// Auto-generated by scripts/updateOffseason.js — do not edit by hand.
// Source: ESPN public NFL news + transactions feeds, read 2026-08-16T10:30:44.038Z.
// Refresh with: npm run offseason
//
// Hand-curated coaching/moves/key points live in offseasonData.js.
// This file carries live headlines and roster transactions only.

export const OFFSEASON_NEWS_UPDATED_AT = "2026-08-16T10:30:44.038Z";

export const offseasonNews = {
    "ARI": {
        news: [
            {"id":"49619508","headline":"Cardinals rookie RB Love to miss a week due to sore ankle","summary":"Cardinals rookie running back Jeremiyah Love will miss the next week to let a sore ankle he injured Thursday night against the Raiders heal, coach Mike LaFleur said.","date":"2026-08-15T20:28:36Z","url":"https://www.espn.com/nfl/story/_/id/49619508/cardinals-rookie-rb-love-miss-week-due-sore-ankle"},
            {"id":"49613585","headline":"Cardinals OL Chase Bisontis' season in doubt with torn MCL","summary":"Chase Bisontis, the Cardinals' second-round pick who was expected to push starter Isaiah Adams for playing time, could miss the season after tearing his left MCL.","date":"2026-08-15T16:20:07Z","url":"https://www.espn.com/nfl/story/_/id/49613585/cardinals-ol-bisontis-season-doubt-torn-mcl"},
            {"id":"49605597","headline":"No. 1 pick Fernando Mendoza throws TD pass in preseason debut for Raiders in 27-14 loss to Cardinals","summary":"— No. 1 draft pick Fernando Mendoza threw a touchdown pass in his preseason debut for the Las Vegas","date":"2026-08-14T04:37:29Z","url":"http://www.espn.com/nfl/recap?gameId=401873640"},
            {"id":"49602122","headline":"Source: Cardinals' Beck (rib) out, derailing rematch vs. Mendoza","summary":"Cardinals quarterback Carson Beck won't play in Thursday night's preseason game against the Raiders due to a rib injury sustained in last Thursday's Hall of Fame Game, a source tol…","date":"2026-08-13T20:39:17Z","url":"https://www.espn.com/nfl/story/_/id/49602122/source-cardinals-beck-rib-derailing-rematch-vs-mendoza"},
        ],
        transactions: [
            {"date":"2026-08-15T07:00Z","description":"Signed TE Baylor Cupp, DL Keveion'ta Spears and RB Tre Stewart. Placed OL Chase Bisontis, TE Jameson Geers and LB Austin Keys on injured reserve."},
            {"date":"2026-08-12T07:00Z","description":"Waived DT PJ Mustipher."},
            {"date":"2026-08-11T07:00Z","description":"Released DT PJ Mustipher from injured reserve with a settlement."},
            {"date":"2026-08-09T07:00Z","description":"Signed TE Shawn Bowman and LB Eugene Asante."},
            {"date":"2026-08-08T07:00Z","description":"Placed S Joey Blount and TE Kenny Yeboah on injured reserve."},
        ],
    },
    "ATL": {
        news: [
            {"id":"49614925","headline":"What adjustments do Tua, Falcons offense need to make?","summary":"What adjustments do Tua, Falcons offense need to make?","date":"2026-08-15T04:14:38Z","url":"https://www.espn.com/video/clip/_/id/49614925/what-adjustments-do-tua-falcons-offense-need-make"},
            {"id":"49614782","headline":"Tua Tagovailoa says Falcons' play 'not up to standard' in loss","summary":"Falcons quarterback Tua Tagovailoa said he was \"frustrated and disappointed\" after a preseason loss to the Broncos, during which he played two series and was 3-of-5 passing for 22…","date":"2026-08-15T10:39:21Z","url":"https://www.espn.com/nfl/story/_/id/49614782/falcons-qb-tua-tagovailoa-frustrated-disappointed-play-preseason-loss-broncos"},
            {"id":"49614199","headline":"Barron returns pick 97 yards for a TD as Stidham leads Broncos to runaway 27-7 win over Falcons","summary":"— Jarrett Stidham threw a touchdown pass in his bid to keep his hold on Denver’s backup job and Jahdae Barron returned an interception 97 yards for a touchdown as the Broncos...","date":"2026-08-15T03:09:29Z","url":"http://www.espn.com/nfl/recap?gameId=401873278"},
            {"id":"49614191","headline":"Broncos down Falcons 27-7 in preseason opener","summary":"Broncos down Falcons 27-7 in preseason opener","date":"2026-08-15T02:12:50Z","url":"https://www.espn.com/video/clip/_/id/49614191/broncos-falcons-27-7-preseason-opener"},
        ],
        transactions: [
            {"date":"2026-08-14T07:00Z","description":"Waived OT Jack Nelson with an injury settlement."},
            {"date":"2026-08-12T07:00Z","description":"Reverted DT Le'Meke Brockington and S Malik Verdon to injured reserve after they cleared waivers."},
            {"date":"2026-08-11T07:00Z","description":"Signed TE Nick Muse and RB Trey Sermon."},
            {"date":"2026-08-10T07:00Z","description":"Reinstated RT Jawaan Taylor from the active/PUP list. Signed DE Cameron Sample. Waived LS Phil Florenzo. Waived/injured OL Jack Nelson."},
            {"date":"2026-08-08T07:00Z","description":"Activated DL Zach Harrison from the non-football injury list."},
        ],
    },
    "BAL": {
        news: [
            {"id":"49623964","headline":"Philadelphia Eagles vs. Baltimore Ravens Game Highlights","summary":"Philadelphia Eagles vs. Baltimore Ravens Game Highlights","date":"2026-08-16T02:33:19Z","url":"https://www.espn.com/video/clip/_/id/49623964/philadelphia-eagles-vs-baltimore-ravens-game-highlights"},
            {"id":"49623897","headline":"Ja'Kobi Lane has TD catch on promising night for Ravens rookie receivers in 24-7 win over Eagles","summary":"— Rookie wide receiver Ja’Kobi Lane keeps turning heads. On Saturday night, so did his recently drafted teammates.","date":"2026-08-16T03:13:31Z","url":"http://www.espn.com/nfl/recap?gameId=401873284"},
            {"id":"49434567","headline":"2026 Baltimore Ravens training camp: Latest intel, updates","summary":"Catch up on our daily updates from Ravens training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-13T19:52:42Z","url":"https://www.espn.com/nfl/story/_/id/49434567/baltimore-ravens-training-camp-2026-intel-updates"},
            {"id":"49591531","headline":"Inside Lamar Jackson's adjustments to Ravens' new offense","summary":"Under new OC Declan Doyle, Lamar Jackson has the opportunity to embrace a new vision.","date":"2026-08-13T11:24:12Z","url":"https://www.espn.com/nfl/story/_/id/49591531/inside-lamar-jackson-adjustment-baltimore-ravens-new-offense-jesse-minter"},
        ],
        transactions: [
            {"date":"2026-08-14T07:00Z","description":"Placed OT Kendall Lamm on the reserve/retire list."},
            {"date":"2026-08-12T07:00Z","description":"Signed QB Austin Reed. Placed QB Skylar Thompson on injured reserve."},
            {"date":"2026-08-09T07:00Z","description":"Waived DB Matthew McDoom."},
            {"date":"2026-08-08T07:00Z","description":"Signed LB Jamon Johnson. Waived DB Matthew McDoom."},
            {"date":"2026-08-05T07:00Z","description":"Reinstated C Corey Bullock from the active/PUP list."},
        ],
    },
    "BUF": {
        news: [
            {"id":"49621204","headline":"Carolina Panthers vs. Buffalo Bills: Game Highlights","summary":"Carolina Panthers vs. Buffalo Bills: Game Highlights","date":"2026-08-15T20:37:47Z","url":"https://www.espn.com/video/clip/_/id/49621204/game-highlights"},
            {"id":"49621171","headline":"Josh Allen gets comfortable in Bills' new stadium with TD pass in 29-14 preseason win over Panthers","summary":"— New head coach. New Buffalo Bills stadium.","date":"2026-08-15T22:28:28Z","url":"http://www.espn.com/nfl/recap?gameId=401873282"},
            {"id":"49611988","headline":"Bills' Phidarian Mathis banned 3 games for substance abuse violation","summary":"Bills defensive tackle Phidarian Mathis has been suspended for the first three games of the season for violating the NFL's substance abuse policy.","date":"2026-08-15T00:27:33Z","url":"https://www.espn.com/nfl/story/_/id/49611988/bills-phidarian-mathis-banned-3-games-substance-abuse-violation"},
            {"id":"49610104","headline":"Why Canty is more worried about the Bills' defense than DJ Moore fitting in","summary":"Why Canty is more worried about the Bills' defense than DJ Moore fitting in","date":"2026-08-14T15:07:28Z","url":"https://www.espn.com/video/clip/_/id/49610104/why-canty-more-worried-bills-defense-dj-moore-fitting-in"},
        ],
        transactions: [
            {"date":"2026-08-14T07:00Z","description":"Signed DB Wande Owens. Waived LB Otis Reese."},
            {"date":"2026-08-12T07:00Z","description":"Signed DB Anthony Kendall. Waived DT Kody Huisman."},
            {"date":"2026-08-06T07:00Z","description":"Signed LB Otis Reese IV to a contract. Placed LB Demetrius Flannigan-Fowles on injured reserve."},
            {"date":"2026-07-31T07:00Z","description":"Signed CB D.J. Miller to a contract. Released S Wande Owens."},
            {"date":"2026-07-30T07:00Z","description":"Waived/injured WR Jalen Virgil. Signed WR Dante Pettis to a contract."},
        ],
    },
    "CAR": {
        news: [
            {"id":"49621729","headline":"New defensive additions shine for Panthers in preseason debut","summary":"Mike Kaye breaks down impressive debuts for Devin Lloyd and Jaelan Phillips with the Panthers.","date":"2026-08-15T21:44:52Z","url":"https://www.espn.com/video/clip/_/id/49621729/new-defensive-additions-shine-panthers-preseason-debut"},
            {"id":"49621204","headline":"Carolina Panthers vs. Buffalo Bills: Game Highlights","summary":"Carolina Panthers vs. Buffalo Bills: Game Highlights","date":"2026-08-15T20:37:47Z","url":"https://www.espn.com/video/clip/_/id/49621204/game-highlights"},
            {"id":"49621171","headline":"Josh Allen gets comfortable in Bills' new stadium with TD pass in 29-14 preseason win over Panthers","summary":"— New head coach. New Buffalo Bills stadium.","date":"2026-08-15T22:28:28Z","url":"http://www.espn.com/nfl/recap?gameId=401873282"},
            {"id":"49377273","headline":"2026 Carolina Panthers training camp: Latest intel, updates","summary":"Catch up on our daily updates from Panthers training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-13T21:01:36Z","url":"https://www.espn.com/nfl/story/_/id/49377273/carolina-panthers-training-camp-2026-intel-updates"},
        ],
        transactions: [
            {"date":"2026-08-12T07:00Z","description":"Released WR Malick Meiga from injured reserve with a settlement."},
            {"date":"2026-08-10T07:00Z","description":"Signed G Joshua Gray. Waived TE Chamon Metayer. Reverted LB Nick Hampton and WR Malick Meiga to injured reserve after they cleared waivers."},
            {"date":"2026-08-09T07:00Z","description":"Signed QB Kyle Trask and LB Jeremiah Moon. Waived/injured LBs Nick Hampton and Malick Meiga."},
            {"date":"2026-08-06T07:00Z","description":"Waived/injured WR Ainas Smith. Released G Saahdiq Charles with an injury settlement."},
            {"date":"2026-08-05T07:00Z","description":"Signed T Jake Curhan and DT Parker Petersen. Placed G Saahdiq Charles on injured reserve. Reverted WR Ainias Smith to injured reserve after he cleared waivers."},
        ],
    },
    "CHI": {
        news: [
            {"id":"49624578","headline":"Randle El takes over playcalling, sparking Bears' 24-0 run","summary":"Bears assistant head coach Antwaan Randle El took over playcalling duties for the second half of the preseason opener vs.","date":"2026-08-16T04:06:17Z","url":"https://www.espn.com/nfl/story/_/id/49624578/randle-el-takes-play-calling-sparking-bears-24-0-run"},
            {"id":"49621189","headline":"Deshaun Watson leads the Browns on 2 scoring drives in a 34-10 preseason loss to the Bears","summary":"— It was a mixed bag for Deshaun Watson. Same for Shedeur Sanders.","date":"2026-08-15T22:13:29Z","url":"http://www.espn.com/nfl/recap?gameId=401874393"},
            {"id":"49621117","headline":"Cleveland Browns vs. Chicago Bears Game Highlights","summary":"Cleveland Browns vs. Chicago Bears Game Highlights","date":"2026-08-15T20:23:48Z","url":"https://www.espn.com/video/clip/_/id/49621117/cleveland-browns-vs-chicago-bears-game-highlights"},
            {"id":"49602630","headline":"Confident Caleb Wlliams has Bears flying high","summary":"Williams is starting to show the grasp and confidence Johnson believes will help the Bears take the next step.","date":"2026-08-14T13:51:18Z","url":"https://www.espn.com/nfl/story/_/id/49602630/chicago-bears-caleb-williams-post-camp"},
        ],
        transactions: [
            {"date":"2026-08-12T07:00Z","description":"Waived S Brandon Hill."},
            {"date":"2026-08-11T07:00Z","description":"Signed OL Wesley French to a contract. Waived DB Brandon Hill."},
            {"date":"2026-08-10T07:00Z","description":"Signed WR Ray-Ray McCloud III. Waived/injured WR Kyron Hudson."},
            {"date":"2026-08-09T07:00Z","description":"Waived LS Luke Elkin. Placed RB KC Eziomume and S Gervarrius Owens on injured reserve. Signed CB Beanie Bishop Jr."},
            {"date":"2026-08-08T07:00Z","description":"Signed DBs Brandon Hill and William Wright. Waived DBs K.C. Eziomume and Gervarrius Owens."},
        ],
    },
    "CIN": {
        news: [
            {"id":"49609343","headline":"Orlovsky: A healthy Joe Burrow is 'essential' for the Bengals","summary":"Orlovsky: A healthy Joe Burrow is 'essential' for the Bengals","date":"2026-08-14T13:53:36Z","url":"https://www.espn.com/video/clip/_/id/49609343/healthy-joe-burrow-essential-bengals"},
            {"id":"49609261","headline":"Bengals down Lions 16-14 in preseason","summary":"Bengals down Lions 16-14 in preseason","date":"2026-08-14T13:38:45Z","url":"https://www.espn.com/video/clip/_/id/49609261/bengals-lions-16-14-preseason"},
            {"id":"49605302","headline":"Joe Burrow starts and backup Joe Flacco throws a TD pass as Bengals beat Lions 16-14","summary":"— Joe Flacco threw a touchdown pass in relief of Joe Burrow, Evan McPherson kicked three field goals and the Cincinnati Bengals beat the Detroit Lions 16-14 Thursday night in the p…","date":"2026-08-14T03:43:29Z","url":"http://www.espn.com/nfl/recap?gameId=401873272"},
            {"id":"49448120","headline":"2026 Cincinnati Bengals training camp: Latest intel, updates","summary":"Catch up on our daily updates from Bengals training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-13T19:53:20Z","url":"https://www.espn.com/nfl/story/_/id/49448120/cincinnati-bengals-training-camp-2026-intel-updates"},
        ],
        transactions: [
            {"date":"2026-08-15T07:00Z","description":"Signed CB Matthew McDoom. Placed CB Ceyair Wright on the exempt/left list. Reinstated DT B.J. Hill from the physically unable to perform list."},
            {"date":"2026-08-06T07:00Z","description":"Activated TE Josh Kattus from the NFI list."},
            {"date":"2026-08-04T07:00Z","description":"Waived S Isaiah Nwokobia."},
            {"date":"2026-07-25T07:00Z","description":"Placed DT B.J. Hill on the pup list. Placed TE Josh Jattus on the non-football injury list."},
            {"date":"2026-06-09T07:00Z","description":"Signed DE Cashius Howell to a rookie contract."},
        ],
    },
    "CLE": {
        news: [
            {"id":"49623049","headline":"Breaking down Browns' QB competition after first preseason game","summary":"Daniel Oyefusi discusses where things stand between Deshaun Watson and Shedeur Sanders after the first preseason game.","date":"2026-08-16T00:28:36Z","url":"https://www.espn.com/video/clip/_/id/49623049/breaking-browns-qb-competition-first-preseason-game"},
            {"id":"49622047","headline":"Deshaun Watson returns with 'awesome' first half for Browns","summary":"Quarterback Deshaun Watson, in his first game since the 2024 season, completed 11 of 15 passes for 126 yards and led two scoring drives, the only points for the Cleveland Browns in…","date":"2026-08-16T00:29:28Z","url":"https://www.espn.com/nfl/story/_/id/49622047/deshaun-watson-returns-awesome-first-half-browns"},
            {"id":"49621189","headline":"Deshaun Watson leads the Browns on 2 scoring drives in a 34-10 preseason loss to the Bears","summary":"— It was a mixed bag for Deshaun Watson. Same for Shedeur Sanders.","date":"2026-08-15T22:13:29Z","url":"http://www.espn.com/nfl/recap?gameId=401874393"},
            {"id":"49621117","headline":"Cleveland Browns vs. Chicago Bears Game Highlights","summary":"Cleveland Browns vs. Chicago Bears Game Highlights","date":"2026-08-15T20:23:48Z","url":"https://www.espn.com/video/clip/_/id/49621117/cleveland-browns-vs-chicago-bears-game-highlights"},
        ],
        transactions: [
            {"date":"2026-08-14T07:00Z","description":"Placed DB Tyron Herring on injured reserve."},
            {"date":"2026-08-13T07:00Z","description":"Signed CB Jeremiah McClendon. Waived CB Tyron Herring with an injury designation."},
            {"date":"2026-08-12T07:00Z","description":"Waived WR Aaron Anderson."},
            {"date":"2026-08-11T07:00Z","description":"Claimed TE Dae'Quan Wright off waivers from Philadelphia. Placed CB Damarri Mathis on injured reserve."},
            {"date":"2026-08-08T07:00Z","description":"Reverted WR Jamari Thrash to injured reserve after clearing waivers."},
        ],
    },
    "DAL": {
        news: [
            {"id":"49624396","headline":"Brown stands out for Cowboys with 2 TD catches in 17-7 win over Seahawks","summary":"— Rookie Camden Brown had two touchdown catches, including a diving, one-handed snag, to help lead the Dallas Cowboys past the Super Bowl champion Seattle Seahawks 17-7 on Saturday…","date":"2026-08-16T04:48:29Z","url":"http://www.espn.com/nfl/recap?gameId=401873279"},
            {"id":"49624282","headline":"Cowboys take down Seahawks 17-7","summary":"Cowboys take down Seahawks 17-7","date":"2026-08-16T03:09:46Z","url":"https://www.espn.com/video/clip/_/id/49624282/cowboys-take-seahawks-17-7"},
            {"id":"49603843","headline":"Could Ryan Flournoy give Cowboys a third 1,000-yard receiver?","summary":"Ryan Flournoy's \"confidence is up\" after securing the No. 3 role behind CeeDee Lamb and George Pickens.","date":"2026-08-15T10:00:12Z","url":"https://www.espn.com/nfl/story/_/id/49603843/nfl-dallas-cowboys-ryan-flournoy-ceedee-lamb-george-pickens"},
            {"id":"49613465","headline":"Who will be the Cowboys' QB2?","summary":"Todd Archer discusses Joe Milton and Sam Howell continuing to battle for the Cowboys' backup quarterback spot.","date":"2026-08-15T00:42:13Z","url":"https://www.espn.com/video/clip/_/id/49613465/who-cowboys-qb2"},
        ],
        transactions: [
            {"date":"2026-08-09T07:00Z","description":"Waived RB Dominic Richardson and DE Charles Snowden."},
            {"date":"2026-08-08T07:00Z","description":"Signed RB Jashaun Corbin. Waived RB Dominic Richardson and DE Charles Snowden."},
            {"date":"2026-08-07T07:00Z","description":"Signed RB Jashaun Corbin to a contract. Waived RB Dominic Richardson."},
            {"date":"2026-08-03T07:00Z","description":"Signed OL Sebastian Gutierrez. Reverted OLB Charles Snowden to injured reserve after he cleared waivers."},
            {"date":"2026-08-02T07:00Z","description":"Signed T Sebastian Gutierrez. Waived DE Charles Snowden."},
        ],
    },
    "DEN": {
        news: [
            {"id":"49622744","headline":"Takeaways from the Broncos 1st preseason game","summary":"Jeff Legwold breaks down why turnovers from guys besides Pat Surtain II are so important.","date":"2026-08-15T23:49:40Z","url":"https://www.espn.com/video/clip/_/id/49622744/takeaways-broncos-1st-preseason-game"},
            {"id":"49614199","headline":"Barron returns pick 97 yards for a TD as Stidham leads Broncos to runaway 27-7 win over Falcons","summary":"— Jarrett Stidham threw a touchdown pass in his bid to keep his hold on Denver’s backup job and Jahdae Barron returned an interception 97 yards for a touchdown as the Broncos...","date":"2026-08-15T03:09:29Z","url":"http://www.espn.com/nfl/recap?gameId=401873278"},
            {"id":"49614191","headline":"Broncos down Falcons 27-7 in preseason opener","summary":"Broncos down Falcons 27-7 in preseason opener","date":"2026-08-15T02:12:50Z","url":"https://www.espn.com/video/clip/_/id/49614191/broncos-falcons-27-7-preseason-opener"},
            {"id":"49379469","headline":"2026 Denver Broncos training camp: Latest intel, updates","summary":"Catch up on our daily updates from Broncos training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-13T19:56:11Z","url":"https://www.espn.com/nfl/story/_/id/49379469/denver-broncos-training-camp-2026-intel-updates"},
        ],
        transactions: [
            {"date":"2026-08-13T07:00Z","description":"Signed OL Lecitus Smith."},
            {"date":"2026-08-10T07:00Z","description":"Reinstated LB Jordan Turner from the active/non-football injury list."},
            {"date":"2026-08-08T07:00Z","description":"Placed DE Matt Henningsen on injured reserve. Released DB Sam Webb. Signed WRs Kyre Duplessis and Kyrese Rowan. Signed DB Ricardo Hallman."},
            {"date":"2026-08-02T07:00Z","description":"Waived DB Blake Cotton."},
            {"date":"2026-08-01T07:00Z","description":"Reverted DB Blake Cotton to injured reserve after clearing waivers."},
        ],
    },
    "DET": {
        news: [
            {"id":"49609261","headline":"Bengals down Lions 16-14 in preseason","summary":"Bengals down Lions 16-14 in preseason","date":"2026-08-14T13:38:45Z","url":"https://www.espn.com/video/clip/_/id/49609261/bengals-lions-16-14-preseason"},
            {"id":"49605302","headline":"Joe Burrow starts and backup Joe Flacco throws a TD pass as Bengals beat Lions 16-14","summary":"— Joe Flacco threw a touchdown pass in relief of Joe Burrow, Evan McPherson kicked three field goals and the Cincinnati Bengals beat the Detroit Lions 16-14 Thursday night in the p…","date":"2026-08-14T03:43:29Z","url":"http://www.espn.com/nfl/recap?gameId=401873272"},
            {"id":"49419620","headline":"2026 Detroit Lions training camp: Latest intel, updates","summary":"Catch up on our daily updates from Lions training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-13T20:28:09Z","url":"https://www.espn.com/nfl/story/_/id/49419620/detroit-lions-training-camp-2026-intel-updates"},
            {"id":"49578327","headline":"Jared Goff understands urgency, eager for Lions to return to form","summary":"Coach Dan Campbell is thrilled with the urgency and guidance Goff shows his Lions teammates.","date":"2026-08-11T15:17:02Z","url":"https://www.espn.com/nfl/story/_/id/49578327/detroit-lions-2026-outlook-jared-goff"},
        ],
        transactions: [
            {"date":"2026-08-12T07:00Z","description":"Waived TE Miles Kitselman."},
            {"date":"2026-08-10T07:00Z","description":"Signed QB Joshua Dobbs to a one-year contract. Released TE Anthony Firkser. Waived DB De'Shawn Rucker. Placed DT Aidan Keanaaina on injured reserve."},
            {"date":"2026-08-09T07:00Z","description":"Released TE Nick Muse. Placed QB Teddy Bridgewater on the reserve/retired list. Signed LB Amen Ogbongbemiga and DB Ryan Cooper Jr."},
            {"date":"2026-08-08T07:00Z","description":"Reverted DB De'Shawn Rucker to injured reserve after clearing waivers."},
            {"date":"2026-08-07T07:00Z","description":"Waived/injured CB De'Shawn Rucker. Signed DL Ben Stille to a contract."},
        ],
    },
    "GB": {
        news: [
            {"id":"49376941","headline":"2026 Green Bay Packers training camp: Latest intel, updates","summary":"Catch up on our daily updates from Packers training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-14T23:15:15Z","url":"https://www.espn.com/nfl/story/_/id/49376941/green-bay-packers-training-camp-2026-intel-updates"},
            {"id":"49609315","headline":"Steelers win big over Packers in the preseason","summary":"Steelers win big over Packers in the preseason","date":"2026-08-14T13:48:23Z","url":"https://www.espn.com/video/clip/_/id/49609315/steelers-win-big-packers-preseason"},
            {"id":"49607095","headline":"Kicker Trey Smack shows out in Packers' presason opener","summary":"Rob Demovsky details the big performance from rookie kicker Trey Smack after a rough training camp.","date":"2026-08-14T07:13:55Z","url":"https://www.espn.com/video/clip/_/id/49607095/kicker-trey-smack-shows-packers-presason-opener"},
            {"id":"49605255","headline":"Rookie Drew Allar has 2 TD passes, 1 TD run as Steelers beat Packers 28-9 in preseason opener","summary":"— Mike McCarthy loves playing the role of teacher during what he calls “Quarterback School,” shorthand for his highly detailed process of teaching young signal callers the finer po…","date":"2026-08-14T03:31:29Z","url":"http://www.espn.com/nfl/recap?gameId=401873275"},
        ],
        transactions: [
            {"date":"2026-08-15T07:00Z","description":"Released QB Kyron Drones."},
            {"date":"2026-08-14T07:00Z","description":"Waived TE RJ Maryland."},
            {"date":"2026-08-12T07:00Z","description":"Waived G Karsen Barnhart and TE Drew Biber. Released TE Luke Lachey from injured reserve with a settlement."},
            {"date":"2026-08-11T07:00Z","description":"Signed Ss Trey Dean III and Tra Fluellen. Released TE Drew Biber and G Karsen Barnhart."},
            {"date":"2026-08-10T07:00Z","description":"Claimed WR Chris Hilton Jr. off waivers from Washington. Reverted DBs Johnathan Baldwin and Marlon Jones to injured reserve after they cleared waivers."},
        ],
    },
    "HOU": {
        news: [
            {"id":"49609453","headline":"Chargers beat the Texans on the road","summary":"Chargers beat the Texans on the road","date":"2026-08-14T14:11:27Z","url":"https://www.espn.com/video/clip/_/id/49609453/chargers-beat-texans-road"},
            {"id":"49609387","headline":"Texans' rookies impress in their debut","summary":"DJ Bien-Aime recaps the Texans' rookie performances against the Chargers.","date":"2026-08-14T13:53:45Z","url":"https://www.espn.com/video/clip/_/id/49609387/texans-rookies-impress-their-debut"},
            {"id":"49605693","headline":"Texans' DeMeco Ryans praises rookie Marlin Klein after catch vs Chargers in his NFL debut","summary":"— Houston Texans rookie Marlin Klein played just 11 snaps in his NFL debut Thursday night against the Los Angeles Chargers.","date":"2026-08-14T04:15:44Z","url":"http://www.espn.com/nfl/recap?gameId=401873274"},
            {"id":"49419567","headline":"2026 Houston Texans training camp: Latest intel, updates","summary":"Catch up on our daily updates from Texans training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-13T19:47:35Z","url":"https://www.espn.com/nfl/story/_/id/49419567/houston-texans-training-camp-2026-intel-updates"},
        ],
        transactions: [
            {"date":"2026-08-15T07:00Z","description":"Signed QB Brett Rypien. Placed QB Graham Mertz and RB Josh Pitsenberger on injured reserve."},
            {"date":"2026-08-14T07:00Z","description":"Waived K Chris Freeman."},
            {"date":"2026-08-12T07:00Z","description":"Waived WR Montrell Washington. Signed K Chris Freeman."},
            {"date":"2026-08-10T07:00Z","description":"Signed WR Juwann Winfree. Placed LB Sione Takitaki on injured reserve."},
            {"date":"2026-08-09T07:00Z","description":"Waived P Jack Stonehouse."},
        ],
    },
    "IND": {
        news: [
            {"id":"49612373","headline":"Source: Colts' special teams coordinator has torn knee ligaments","summary":"Colts special teams coordinator Brian Mason tore multiple ligaments in his knee after a sideline collision on the final play of Thursday night's preseason game against the Patriots…","date":"2026-08-14T21:33:51Z","url":"https://www.espn.com/nfl/story/_/id/49612373/colts-special-teams-coordinator-torn-knee-ligaments"},
            {"id":"49609380","headline":"Colts and Patriots finish first preseason game in a 13-13 tie","summary":"Colts and Patriots finish first preseason game in a 13-13 tie","date":"2026-08-14T13:55:44Z","url":"https://www.espn.com/video/clip/_/id/49609380/colts-patriots-finish-first-preseason-game-13-13-tie"},
            {"id":"49605614","headline":"Colts backup QB Anthony Richardson runs for a TD in 13-13 preseason tie with Patriots","summary":"— Anthony Richardson believes he's done a good job turning the page during his NFL career.","date":"2026-08-14T04:04:29Z","url":"http://www.espn.com/nfl/recap?gameId=401873273"},
            {"id":"49448214","headline":"2026 Indianapolis Colts training camp: Latest intel, updates","summary":"Catch up on our daily updates from Colts training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-13T19:49:39Z","url":"https://www.espn.com/nfl/story/_/id/49448214/indianapolis-colts-training-camp-2026-intel-updates"},
        ],
        transactions: [
            {"date":"2026-08-09T07:00Z","description":"Signed WR D.J. Montgomery. Waived WR Liam Clifford."},
            {"date":"2026-08-07T07:00Z","description":"Signed TE Pharaoh Brown to a contract."},
            {"date":"2026-08-06T07:00Z","description":"Signed RB Jonathan Taylor to a three-year contract extension. Signed TE Pharaoh Brown to a contract. Placed TE Sean McKeon on injured reserve."},
            {"date":"2026-08-03T07:00Z","description":"Signed CB Mekhi Rodgers. Waived/injured CB Cameron Mitchell."},
            {"date":"2026-07-31T07:00Z","description":"Activated LB C.J. Allen from the PUP list. Signed RB Roydell Williams to a contract."},
        ],
    },
    "JAX": {
        news: [
            {"id":"49622747","headline":"Zach Wilson stands out for the Saints in a 24-20 preseason loss to the Jaguars","summary":"— Zach Wilson, saddled with the “draft bust” label as he tries to salvage his NFL career, is giving the New Orleans Saints reasons to take him seriously as a potential backup to Ty…","date":"2026-08-16T01:53:30Z","url":"http://www.espn.com/nfl/recap?gameId=401873281"},
            {"id":"49622569","headline":"Jacksonville Jaguars vs. New Orleans Saints: Game Highlights","summary":"Jacksonville Jaguars vs. New Orleans Saints: Game Highlights","date":"2026-08-15T23:30:14Z","url":"https://www.espn.com/video/clip/_/id/49622569/game-highlights"},
            {"id":"49427691","headline":"2026 Jacksonville Jaguars training camp: Latest intel, updates","summary":"Catch up on our daily updates from Jaguars training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-13T19:51:11Z","url":"https://www.espn.com/nfl/story/_/id/49427691/jacksonville-jaguars-training-camp-2026-intel-updates"},
            {"id":"49577700","headline":"How Jaguars WR Brian Thomas Jr. prepared to be better in 2026","summary":"Thomas has worked intentionally to improve his hands for 2026, and as Liam Coen said, \"It elevates everybody's game when BT is playing at his highest level.\"","date":"2026-08-11T11:46:10Z","url":"https://www.espn.com/nfl/story/_/id/49577700/jacksonville-jaguars-wr-brian-thomas-jr-fantasy-offseason-improve-2026"},
        ],
        transactions: [
            {"date":"2026-08-12T07:00Z","description":"Waived CB Keni-H Lovely."},
            {"date":"2026-08-11T07:00Z","description":"Signed LB Amari Burney to a contract. Waived CB Keni-H Lovely."},
            {"date":"2026-08-08T07:00Z","description":"Placed T Garrett DiGiorgio on injured reserve. Reverted LB Jared Bartlett to injured reserve after clearing waivers. Signed T Geron Christian. Signed OL Geron Christian."},
            {"date":"2026-08-07T07:00Z","description":"Signed LB Jahlani Taval to a contract."},
            {"date":"2026-08-05T07:00Z","description":"Signed C Sam Mustipher."},
        ],
    },
    "KC": {
        news: [
            {"id":"49622481","headline":"Rams take down Chiefs 20-12 in preseason opener","summary":"Rams take down Chiefs 20-12 in preseason opener","date":"2026-08-15T23:14:31Z","url":"https://www.espn.com/video/clip/_/id/49622481/rams-take-chiefs-20-12-preseason-opener"},
            {"id":"49622454","headline":"First-round pick Ty Simpson throws 2 TD passes, rallies Rams past Chiefs 20-12 in preseason debut","summary":"— There were a whole bunch of raised eyebrows when the Los Angeles Rams drafted Ty Simpson in the first round in April.","date":"2026-08-16T00:06:32Z","url":"http://www.espn.com/nfl/recap?gameId=401873283"},
            {"id":"49602431","headline":"Rookie Benson earns shot to start at RT for Chiefs","summary":"The former starter for national champion Indiana has garnered a lot of praise in camp for his attitude and strength.","date":"2026-08-14T10:00:12Z","url":"https://www.espn.com/nfl/story/_/id/49602431/kansas-city-chiefs-rookie-kahlil-benson"},
            {"id":"49447878","headline":"2026 Kansas City Chiefs training camp: Latest intel, updates","summary":"Catch up on our daily updates from Chiefs training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-13T19:59:31Z","url":"https://www.espn.com/nfl/story/_/id/49447878/kansas-city-chiefs-training-camp-2026-intel-updates"},
        ],
        transactions: [
            {"date":"2026-08-14T07:00Z","description":"Waived DB Bryce Phillips."},
            {"date":"2026-08-13T07:00Z","description":"Signed DE Emmanuel Ogbah."},
            {"date":"2026-08-03T07:00Z","description":"Signed WR Jeff Weimer."},
            {"date":"2026-08-01T07:00Z","description":"Signed DE Ethan Hurkett."},
            {"date":"2026-07-28T07:00Z","description":"Placed LB Ethan Downs and TE John Michael Gyllenborg on injured reserve."},
        ],
    },
    "LAC": {
        news: [
            {"id":"49609453","headline":"Chargers beat the Texans on the road","summary":"Chargers beat the Texans on the road","date":"2026-08-14T14:11:27Z","url":"https://www.espn.com/video/clip/_/id/49609453/chargers-beat-texans-road"},
            {"id":"49605693","headline":"Texans' DeMeco Ryans praises rookie Marlin Klein after catch vs Chargers in his NFL debut","summary":"— Houston Texans rookie Marlin Klein played just 11 snaps in his NFL debut Thursday night against the Los Angeles Chargers.","date":"2026-08-14T04:15:44Z","url":"http://www.espn.com/nfl/recap?gameId=401873274"},
            {"id":"49424976","headline":"2026 Los Angeles Chargers training camp: Latest intel, updates","summary":"Catch up on our daily updates from Chargers training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-13T20:02:03Z","url":"https://www.espn.com/nfl/story/_/id/49424976/los-angeles-chargers-training-camp-2026-intel-updates"},
            {"id":"49593606","headline":"Why the Chargers' schedule makes them a fantasy defense to target","summary":"Why the Chargers' schedule makes them a fantasy defense to target","date":"2026-08-12T22:15:26Z","url":"https://www.espn.com/video/clip/_/id/49593606/why-chargers-schedule-makes-fantasy-defense-target"},
        ],
        transactions: [
            {"date":"2026-08-10T07:00Z","description":"Signed OLB Andre Carter II. Waived WR Mante Morrow."},
            {"date":"2026-07-28T07:00Z","description":"Signed LS Peter Bowden to a contract."},
            {"date":"2026-07-27T07:00Z","description":"Released G Ben Cleveland."},
            {"date":"2026-07-24T07:00Z","description":"Placed OT Isaiah World on the NFI list."},
            {"date":"2026-05-27T07:00Z","description":"Signed S Derwin James to a three-year contract extension."},
        ],
    },
    "LAR": {
        news: [
            {"id":"49622863","headline":"Rams' top pick Simpson shines in 2-TD preseason debut vs. Chiefs","summary":"Rams rookie Ty Simpson, the second quarterback taken in this year's draft, showed plenty of poise in going 21-of-25 for 190 yards and two touchdowns in his preseason debut against…","date":"2026-08-16T01:34:23Z","url":"https://www.espn.com/nfl/story/_/id/49622863/rams-top-pick-simpson-shines-2-td-preseason-debut-vs-chiefs"},
            {"id":"49622481","headline":"Rams take down Chiefs 20-12 in preseason opener","summary":"Rams take down Chiefs 20-12 in preseason opener","date":"2026-08-15T23:14:31Z","url":"https://www.espn.com/video/clip/_/id/49622481/rams-take-chiefs-20-12-preseason-opener"},
            {"id":"49622454","headline":"First-round pick Ty Simpson throws 2 TD passes, rallies Rams past Chiefs 20-12 in preseason debut","summary":"— There were a whole bunch of raised eyebrows when the Los Angeles Rams drafted Ty Simpson in the first round in April.","date":"2026-08-16T00:06:32Z","url":"http://www.espn.com/nfl/recap?gameId=401873283"},
            {"id":"49610407","headline":"Canty on whether Rams are Super Bowl favorites: 'Hell no!'","summary":"Canty on whether Rams are Super Bowl favorites: 'Hell no!'","date":"2026-08-14T16:11:09Z","url":"https://www.espn.com/video/clip/_/id/49610407/hell-no"},
        ],
        transactions: [
            {"date":"2026-08-13T07:00Z","description":"Signed LB Monty Rice."},
            {"date":"2026-08-10T07:00Z","description":"Signed CB Zech McPhearson. Waived DB Drey Norwood."},
            {"date":"2026-08-09T07:00Z","description":"Placed S Drey Norwood on injured reserve."},
            {"date":"2026-08-08T07:00Z","description":"Waived DB Drey Norwood."},
            {"date":"2026-08-07T07:00Z","description":"Signed DE Daniel Rickert to a contract."},
        ],
    },
    "LV": {
        news: [
            {"id":"49606498","headline":"Raiders rookie Fernando Mendoza throws for 97 yards in 4 drives","summary":"Raiders rookie QB Fernando Mendoza completed 10 of 16 passes for 97 yards and a touchdown on four drives against the Cardinals.","date":"2026-08-14T05:40:20Z","url":"https://www.espn.com/nfl/story/_/id/49606498/raiders-rookie-fernando-mendoza-throws-97-yards-4-drives"},
            {"id":"49605597","headline":"No. 1 pick Fernando Mendoza throws TD pass in preseason debut for Raiders in 27-14 loss to Cardinals","summary":"— No. 1 draft pick Fernando Mendoza threw a touchdown pass in his preseason debut for the Las Vegas","date":"2026-08-14T04:37:29Z","url":"http://www.espn.com/nfl/recap?gameId=401873640"},
        ],
        transactions: [
            {"date":"2026-08-15T07:00Z","description":"Signed DT Folorunso Fatukasi. Placed LB Brennan Jackson on injured reserve."},
            {"date":"2026-08-13T07:00Z","description":"Placed G Justin Pickett on injured reserve"},
            {"date":"2026-08-12T07:00Z","description":"Signed OL Braeden Daniels. Waived G Justin Pickett with an injury designation."},
            {"date":"2026-08-06T07:00Z","description":"Signed RB Dare Ogunbowale to a contract."},
            {"date":"2026-08-05T07:00Z","description":"Signed TE Chris Myarick. Waived TE Zack Kuntz and DB Tanner Wall."},
        ],
    },
    "MIA": {
        news: [
            {"id":"49614504","headline":"Miami Dolphins vs. Washington Commanders Game Highlights","summary":"Miami Dolphins vs. Washington Commanders Game Highlights","date":"2026-08-15T02:52:53Z","url":"https://www.espn.com/video/clip/_/id/49614504/miami-dolphins-vs-washington-commanders-game-highlights"},
            {"id":"49614344","headline":"Dolphins' Malik Willis has impressive start, Marcus Mariota injured as Commanders win 20-7","summary":"— Malik Willis got off to an impressive start as Miami's new quarterback, leading a 14-play, 93-yard touchdown drive as the Dolphins lost 20-7 to the Washington Commanders Friday n…","date":"2026-08-15T03:45:41Z","url":"http://www.espn.com/nfl/recap?gameId=401873277"},
            {"id":"49611336","headline":"Troy Aikman facing MNF limits due to Dolphins role, NFL says","summary":"ESPN analyst Troy Aikman will see some restrictions in the lead-up to \"Monday Night Football\" broadcasts similar to those for Fox's Tom Brady.","date":"2026-08-14T20:18:34Z","url":"https://www.espn.com/nfl/story/_/id/49611336/troy-aikman-facing-mnf-limits-due-dolphins-role-nfl-says"},
            {"id":"49601790","headline":"Rookie Caleb Douglas atop Dolphins WR depth chart for preseason opener","summary":"Miami's thin wide receiver room created an opportunity for Caleb Douglas to make an early impact, which he has done so far.","date":"2026-08-14T10:00:11Z","url":"https://www.espn.com/nfl/story/_/id/49601790/dolphins-wr-caleb-douglas-depth-chart-starting-preseason-games"},
        ],
        transactions: [
            {"date":"2026-08-12T07:00Z","description":"Waived DT Omar Brown."},
            {"date":"2026-08-10T07:00Z","description":"Signed CB Nick McCloud. Placed K Zane Gonzalez on injured reserve. Waived RB Anthony Hankerson."},
            {"date":"2026-08-08T07:00Z","description":"Reverted DB Omar Brown to injured reserve."},
            {"date":"2026-08-07T07:00Z","description":"Signed S Tanner Wall to a contract. Claimed CB Ahmari Harvey off waivers from Pittsburgh. Waived QB Mark Gronowski. Waived/injured S Omar Brown."},
            {"date":"2026-08-05T07:00Z","description":"Claimed TE Jeremiah Franklin off waivers from New England. Signed DT Fatorma Mulbah. Waived OLB Seth Coleman-Lyles. Placed DE Rene Konga on injured reserve."},
        ],
    },
    "MIN": {
        news: [
            {"id":"49621093","headline":"Murray debuts as Minnesota's starting QB and Dart throws for a TD as Vikings beat Giants 13-10","summary":"— Everything is new for Kyler Murray after joining the Minnesota Vikings, so he made sure to soak in every little thing, from the flights and bus rides to the purple-and-white unif…","date":"2026-08-15T21:30:29Z","url":"http://www.espn.com/nfl/recap?gameId=401873280"},
            {"id":"49621061","headline":"Vikings down the Giants 13-10 in the preseason","summary":"Vikings down the Giants 13-10 in the preseason","date":"2026-08-15T20:12:47Z","url":"https://www.espn.com/video/clip/_/id/49621061/vikings-giants-13-10-preseason"},
            {"id":"49620313","headline":"Jamal Adams carted to locker room in Vikings' preseason debut","summary":"Veteran defender Jamal Adams was taken to the locker room on a cart Saturday shortly after his preseason debut with the Vikings","date":"2026-08-15T20:40:25Z","url":"https://www.espn.com/nfl/story/_/id/49620313/jamal-adams-carted-locker-room-vikings-preseason-debut"},
            {"id":"49604084","headline":"What to watch for in Vikings' preseason opener","summary":"Kevin Seifert details what he would like to see in the Vikings' preseason opener against the Giants.","date":"2026-08-13T23:37:36Z","url":"https://www.espn.com/video/clip/_/id/49604084/what-watch-vikings-preseason-opener"},
        ],
        transactions: [
            {"date":"2026-08-12T07:00Z","description":"Signed RB Jermar Jefferson. Waived RB Jordan Mims."},
            {"date":"2026-08-02T07:00Z","description":"Signed CB Jarod Washington. Waived RB Kejon Owens."},
            {"date":"2026-07-28T07:00Z","description":"Signed S Jamal Adams and RB Jordan Mims to contracts. Signed T Brian O'Neill to a four-year contract extension through the 2030 season."},
            {"date":"2026-07-27T07:00Z","description":"Waived LB Keli Lawson and WR Luke Wysong. Placed RB Kejon Owens on the NFI list."},
            {"date":"2026-06-16T07:00Z","description":"Waived T Caleb Etienne and DL Minkell Doodwine. Signed TE Marshall Lang and DL Jahvaree Ritzie to contracts."},
        ],
    },
    "NE": {
        news: [
            {"id":"49427703","headline":"2026 New England Patriots training camp: Latest intel, updates","summary":"Catch up on our daily updates from Patriots training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-15T21:28:12Z","url":"https://www.espn.com/nfl/story/_/id/49427703/new-england-patriots-training-camp-2026-intel-updates"},
            {"id":"49609380","headline":"Colts and Patriots finish first preseason game in a 13-13 tie","summary":"Colts and Patriots finish first preseason game in a 13-13 tie","date":"2026-08-14T13:55:44Z","url":"https://www.espn.com/video/clip/_/id/49609380/colts-patriots-finish-first-preseason-game-13-13-tie"},
            {"id":"49605614","headline":"Colts backup QB Anthony Richardson runs for a TD in 13-13 preseason tie with Patriots","summary":"— Anthony Richardson believes he's done a good job turning the page during his NFL career.","date":"2026-08-14T04:04:29Z","url":"http://www.espn.com/nfl/recap?gameId=401873273"},
        ],
        transactions: [
            {"date":"2026-08-15T07:00Z","description":"Signed OLs Darrian Dalcourt and Joe Michalski. Waived LS Niko Lalos. Placed G Andrew Rupcich on injured reserve. Waived RB Terrell Jennings with an injury settlement."},
            {"date":"2026-08-13T07:00Z","description":"Signed RB JaMycal Hasty. Placed RB Terrell Jennings on injured reserve."},
            {"date":"2026-08-12T07:00Z","description":"Signed RB Hassan Haskins. Waived RB Myles Montgomery with an injury designation."},
            {"date":"2026-08-10T07:00Z","description":"Signed DE Niko Lalos. Traded OL Caedan Wallace and a 2029 seventh-round draft pick to Miami in exchange for a 2028 sixth-round draft pick."},
            {"date":"2026-08-07T07:00Z","description":"Signed S Eric Butler to a contract. Released DT David Blay Jr."},
        ],
    },
    "NO": {
        news: [
            {"id":"49622747","headline":"Zach Wilson stands out for the Saints in a 24-20 preseason loss to the Jaguars","summary":"— Zach Wilson, saddled with the “draft bust” label as he tries to salvage his NFL career, is giving the New Orleans Saints reasons to take him seriously as a potential backup to Ty…","date":"2026-08-16T01:53:30Z","url":"http://www.espn.com/nfl/recap?gameId=401873281"},
            {"id":"49622569","headline":"Jacksonville Jaguars vs. New Orleans Saints: Game Highlights","summary":"Jacksonville Jaguars vs. New Orleans Saints: Game Highlights","date":"2026-08-15T23:30:14Z","url":"https://www.espn.com/video/clip/_/id/49622569/game-highlights"},
            {"id":"49424731","headline":"2026 New Orleans Saints training camp: Latest intel, updates","summary":"Catch up on our daily updates from Saints training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-14T22:06:53Z","url":"https://www.espn.com/nfl/story/_/id/49424731/new-orleans-saints-training-camp-2026-intel-updates"},
            {"id":"49611207","headline":"Saints rookie WR Tyson to miss time due to hamstring injury","summary":"Saints rookie wide receiver Jordyn Tyson has a right hamstring issue and will miss time, according to Saints coach Kellen Moore.","date":"2026-08-14T18:42:19Z","url":"https://www.espn.com/nfl/story/_/id/49611207/saints-rookie-wr-tyson-miss-hamstring-injury"},
        ],
        transactions: [
            {"date":"2026-08-12T07:00Z","description":"Signed DT Kahlil Saunders. Placed OL Dillon Radunz on injured reserve, ending his season."},
            {"date":"2026-08-09T07:00Z","description":"Waived DT Zxavian Harris."},
            {"date":"2026-08-08T07:00Z","description":"Reverted DT Keeshawn Silver to injured reserve after clearing waivers. Signed LB Deion Jones, DT Brien Taylor, and DE Malakai Williams. Waived DT Zxavian Harris."},
            {"date":"2026-08-07T07:00Z","description":"Claimed DE Garrett Nelson off waivers from Seattle. Placed DT Bryan Bresee on injured reserve. Waived DT Keeshawn Silver."},
            {"date":"2026-08-05T07:00Z","description":"Reinstated DT Keeshawn Silver from the active/PUP list."},
        ],
    },
    "NYG": {
        news: [
            {"id":"49623388","headline":"Giants show promise in preseason opener","summary":"Jordan Raanan discusses the encouraging signs and the negative signs after the Giants' preseason opener.","date":"2026-08-16T01:19:11Z","url":"https://www.espn.com/video/clip/_/id/49623388/giants-show-promise-preseason-opener"},
            {"id":"49621093","headline":"Murray debuts as Minnesota's starting QB and Dart throws for a TD as Vikings beat Giants 13-10","summary":"— Everything is new for Kyler Murray after joining the Minnesota Vikings, so he made sure to soak in every little thing, from the flights and bus rides to the purple-and-white unif…","date":"2026-08-15T21:30:29Z","url":"http://www.espn.com/nfl/recap?gameId=401873280"},
            {"id":"49621061","headline":"Vikings down the Giants 13-10 in the preseason","summary":"Vikings down the Giants 13-10 in the preseason","date":"2026-08-15T20:12:47Z","url":"https://www.espn.com/video/clip/_/id/49621061/vikings-giants-13-10-preseason"},
            {"id":"49434181","headline":"2026 New York Giants training camp: Latest intel, updates","summary":"Catch up on our daily updates from Giants training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-14T01:14:15Z","url":"https://www.espn.com/nfl/story/_/id/49434181/new-york-giants-training-camp-2026-intel-updates"},
        ],
        transactions: [
            {"date":"2026-08-14T07:00Z","description":"Placed DB DJ James on injured reserve. Waived WR Beaux Collins with an injury settlement."},
            {"date":"2026-08-13T07:00Z","description":"Signed DBs Ugo Amadi and Sam Webb."},
            {"date":"2026-08-10T07:00Z","description":"Signed DB J.T. Woods. Released DT Sam Roberts."},
            {"date":"2026-08-08T07:00Z","description":"Reverted DB Jarrick Bernard-Converse to injured reserve after clearing waivers. Signed G Brenden Jaimes."},
            {"date":"2026-08-06T07:00Z","description":"Signed FB Grant Finley to a contract. Waived TE Tyler Moore."},
        ],
    },
    "NYJ": {
        news: [
            {"id":"49621750","headline":"Jets activate DT T'Vondre Sweat from non-football injury list","summary":"The Jets activated defensive tackle T'Vondre Sweat from the active/non-football injury list on Saturday after he was sidelined for the start of training camp with a hamstring ailme…","date":"2026-08-15T21:52:06Z","url":"https://www.espn.com/nfl/story/_/id/49621750/jets-activate-dt-tvondre-sweat-non-football-injury-list"},
            {"id":"49616235","headline":"Tampa Bay Buccaneers vs. New York Jets: Game Highlights","summary":"Tampa Bay Buccaneers vs. New York Jets: Game Highlights","date":"2026-08-15T06:56:11Z","url":"https://www.espn.com/video/clip/_/id/49616235/game-highlights"},
            {"id":"49614843","headline":"Jets' Geno Smith scratched vs. Bucs due to sore ankle, is day-to-day","summary":"Jets quarterback Geno Smith is day-to-day with an ankle injury that occurred Wednesday and resulted in him being scratched from the preseason opener Friday night against the Buccan…","date":"2026-08-15T13:15:06Z","url":"https://www.espn.com/nfl/story/_/id/49614843/jets-geno-smith-scratched-vs-bucs-due-sore-ankle-day-day"},
            {"id":"49614171","headline":"Rookie Cade Klubnik leads 2 scoring drives after Geno Smith is scratched in Jets' 24-16 loss to Bucs","summary":"— Cade Klubnik knew he'd make his NFL debut early in the New York Jets' preseason opener. It turned out it came even sooner than expected for the rookie fourth-rounder.","date":"2026-08-15T03:17:29Z","url":"http://www.espn.com/nfl/recap?gameId=401873276"},
        ],
        transactions: [
            {"date":"2026-08-14T07:00Z","description":"Waived DE Eric Watts."},
            {"date":"2026-08-06T07:00Z","description":"Claimed DL Junior Tafuna off waivers from Houston. Waived DL Patrick Jenkins"},
            {"date":"2026-08-05T07:00Z","description":"Signed TE Connor Hulstein and DT Patrick Jenkins. Waived DB Keidron Smith and DE Eric Watts."},
            {"date":"2026-08-01T07:00Z","description":"Signed DL Ben Barten. Waived S Garrison Grimes. Reverted WR Gee Scott Jr. to injured reserve after clearing waivers."},
            {"date":"2026-07-31T07:00Z","description":"Reverted WR Jalen Walthall to injured reserve after clearing waivers. Signed WR Cam Camper. Waived WR Gee Scott Jr.."},
        ],
    },
    "PHI": {
        news: [
            {"id":"49623964","headline":"Philadelphia Eagles vs. Baltimore Ravens Game Highlights","summary":"Philadelphia Eagles vs. Baltimore Ravens Game Highlights","date":"2026-08-16T02:33:19Z","url":"https://www.espn.com/video/clip/_/id/49623964/philadelphia-eagles-vs-baltimore-ravens-game-highlights"},
            {"id":"49623897","headline":"Ja'Kobi Lane has TD catch on promising night for Ravens rookie receivers in 24-7 win over Eagles","summary":"— Rookie wide receiver Ja’Kobi Lane keeps turning heads. On Saturday night, so did his recently drafted teammates.","date":"2026-08-16T03:13:31Z","url":"http://www.espn.com/nfl/recap?gameId=401873284"},
            {"id":"49603297","headline":"What to expect from the Eagles' offense this preseason","summary":"Tim McManus reports the latest on Eagles OC Sean Mannion's offense ahead of their preseason opener.","date":"2026-08-13T21:18:34Z","url":"https://www.espn.com/video/clip/_/id/49603297/what-expect-eagles-offense-preseason"},
            {"id":"49434399","headline":"2026 Philadelphia Eagles training camp: Latest intel, updates","summary":"Catch up on our daily updates from Eagles training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-13T19:21:18Z","url":"https://www.espn.com/nfl/story/_/id/49434399/philadelphia-eagles-training-camp-2026-intel-updates"},
        ],
        transactions: [
            {"date":"2026-08-15T07:00Z","description":"Signed LB Brandon George. Waived WR Brandon Hayes."},
            {"date":"2026-08-10T07:00Z","description":"Signed DT David Blay Jr., RB Ja'Quinden Jackson and OLB Tarron Jackson. Waived G Jaeden Roberts and TE Dae'Quan Wright. Placed RB Elijah Mitchell on injured reserve."},
            {"date":"2026-08-05T07:00Z","description":"Signed WR Brandon Hayes."},
            {"date":"2026-08-02T07:00Z","description":"Waived DE Ta'Quon Graham."},
            {"date":"2026-06-23T07:00Z","description":"Signed OT Markel Bell to a rookie contract."},
        ],
    },
    "PIT": {
        news: [
            {"id":"49449169","headline":"2026 Pittsburgh Steelers training camp: Latest intel, updates","summary":"Catch up on our daily updates from Steelers training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-15T21:38:48Z","url":"https://www.espn.com/nfl/story/_/id/49449169/pittsburgh-steelers-training-camp-2026-intel-updates"},
            {"id":"49614342","headline":"Steelers' Keeanu Benton agrees to 4-year, $72M extension, sources say","summary":"The Steelers and defensive tackle Keeanu Benton have agreed to a four-year, $72 million extension, sources told NFL Network's Ian Rapoport.","date":"2026-08-15T13:38:54Z","url":"https://www.espn.com/nfl/story/_/id/49614342/steelers-keeanu-benton-agrees-4-year-72m-extension-sources-say"},
            {"id":"49610646","headline":"McCarthy on his Steelers coaching debut: 'It was very emotional'","summary":"McCarthy on his Steelers coaching debut: 'It was very emotional'","date":"2026-08-14T17:00:21Z","url":"https://www.espn.com/video/clip/_/id/49610646/was-very-emotional"},
            {"id":"49609315","headline":"Steelers win big over Packers in the preseason","summary":"Steelers win big over Packers in the preseason","date":"2026-08-14T13:48:23Z","url":"https://www.espn.com/video/clip/_/id/49609315/steelers-win-big-packers-preseason"},
        ],
        transactions: [
            {"date":"2026-08-15T07:00Z","description":"Agreed to terms with DT Keeanu Benton on a four-year contract extension."},
            {"date":"2026-08-14T07:00Z","description":"Waived OT Lorenzo Thompson with an injury settlement."},
            {"date":"2026-08-13T07:00Z","description":"Signed LB Elandon Roberts."},
            {"date":"2026-08-10T07:00Z","description":"Signed WRs Cornell Powell and Isaiah Winstead. Waived T Lorenzo Thompson."},
            {"date":"2026-08-09T07:00Z","description":"Waived WR Colton Dowell."},
        ],
    },
    "SEA": {
        news: [
            {"id":"49624396","headline":"Brown stands out for Cowboys with 2 TD catches in 17-7 win over Seahawks","summary":"— Rookie Camden Brown had two touchdown catches, including a diving, one-handed snag, to help lead the Dallas Cowboys past the Super Bowl champion Seattle Seahawks 17-7 on Saturday…","date":"2026-08-16T04:48:29Z","url":"http://www.espn.com/nfl/recap?gameId=401873279"},
            {"id":"49624282","headline":"Cowboys take down Seahawks 17-7","summary":"Cowboys take down Seahawks 17-7","date":"2026-08-16T03:09:46Z","url":"https://www.espn.com/video/clip/_/id/49624282/cowboys-take-seahawks-17-7"},
            {"id":"49619266","headline":"Seahawks, CB Witherspoon agree on extension: 4 years, $132M, sources say","summary":"Three-time Pro Bowl cornerback Devon Witherspoon and the Seattle Seahawks reached an agreement on an extension Saturday, with sources telling ESPN's Adam Schefter it's a four-year…","date":"2026-08-16T05:52:50Z","url":"https://www.espn.com/nfl/story/_/id/49619266/sources-seahawks-cb-witherspoon-agree-4-year-132m-deal"},
            {"id":"49613541","headline":"Seahawks' DeMarcus Lawrence confirms 2026 season his last","summary":"Seahawks outside linebacker DeMarcus Lawrence confirmed to Yahoo Sports that his 13th NFL season will be his last.","date":"2026-08-15T16:13:54Z","url":"https://www.espn.com/nfl/story/_/id/49613541/seahawks-linebacker-demarcus-lawrence-confirms-2026-season-last"},
        ],
        transactions: [
            {"date":"2026-08-15T07:00Z","description":"Agreed to terms with CB Devon Witherspoon on a four-year contract extension."},
            {"date":"2026-08-14T07:00Z","description":"Waived DB Brandon Johnson with an injury settlement."},
            {"date":"2026-08-11T07:00Z","description":"Reinstated S Nick Emmanwori from the active/PUP list. Signed LB Aaron Smith. Placed FB Robbie Ouzts on injured reserve."},
            {"date":"2026-08-09T07:00Z","description":"Waived LB Power Echols."},
            {"date":"2026-08-08T07:00Z","description":"Reverted LB Joseph Vaughn to injured reserve after clearing waivers. Signed RB Justin Jones. Waived LB Power Echols."},
        ],
    },
    "SF": {
        news: [
            {"id":"49427696","headline":"2026 San Francisco 49ers training camp: Latest intel, updates","summary":"Catch up on our daily updates from 49ers training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-15T22:34:01Z","url":"https://www.espn.com/nfl/story/_/id/49427696/san-francisco-49ers-training-camp-2026-intel-updates"},
            {"id":"49609924","headline":"Can the 49ers depend on rookie WR De'Zhaun Stribling?","summary":"Stribling had a strong preseason debut after an exciting training camp. How does he transform the 49ers' depleted WR room?","date":"2026-08-15T21:18:32Z","url":"https://www.espn.com/nfl/story/_/id/49609924/san-francisco-49ers-wide-receiver-dezhaun-stribling-preseason-debut"},
            {"id":"49609587","headline":"Titans down the 49ers in preseason","summary":"Titans down the 49ers in preseason","date":"2026-08-14T14:16:26Z","url":"https://www.espn.com/video/clip/_/id/49609587/titans-49ers-preseason"},
            {"id":"49605904","headline":"Cam Ward struggles in the Titans' 19-13 preseason win over the 49ers","summary":"— Cam Ward struggled in three drives for Tennessee against San Francisco's backup defense and the...","date":"2026-08-14T15:43:29Z","url":"http://www.espn.com/nfl/recap?gameId=401874392"},
        ],
        transactions: [
            {"date":"2026-08-13T07:00Z","description":"Placed DE KJ Henry on injured reserve."},
            {"date":"2026-08-12T07:00Z","description":"Signed CB Eli Apple, RB Zamir White and DE Xavier Thomas. Waived LB Junior Bergen and WR Jack Bouwmeester and DE K.J. Henry (injured)."},
            {"date":"2026-08-10T07:00Z","description":"Signed OL Doug Kramer Jr. Released OL Nick Zakelj."},
            {"date":"2026-08-06T07:00Z","description":"Signed OL Kion Smith to a one-year contract. Waived WR Colton Dowell."},
            {"date":"2026-08-05T07:00Z","description":"Signed WR KhaDarel Hodge and LB Ogbonnia Okoronkwo. Released DT Kevin Givens and DE Cameron Sample."},
        ],
    },
    "TB": {
        news: [
            {"id":"49616235","headline":"Tampa Bay Buccaneers vs. New York Jets: Game Highlights","summary":"Tampa Bay Buccaneers vs. New York Jets: Game Highlights","date":"2026-08-15T06:56:11Z","url":"https://www.espn.com/video/clip/_/id/49616235/game-highlights"},
            {"id":"49419613","headline":"2026 Tampa Bay Buccaneers training camp: Latest intel, updates","summary":"Catch up on our daily updates from Bucs training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-13T21:20:48Z","url":"https://www.espn.com/nfl/story/_/id/49419613/tampa-bay-buccaneers-training-camp-2026-intel-updates"},
            {"id":"49591712","headline":"Buccaneers WR Emeka Egbuka limps off in practice against Jets","summary":"Buccaneers wide receiver Emeka Egbuka limped off the field during a joint practice with the Jets on Wednesday and didn't return.","date":"2026-08-12T19:18:46Z","url":"https://www.espn.com/nfl/story/_/id/49591712/buccaneers-wr-emeka-egbuka-limps-practice-jets"},
        ],
        transactions: [
            {"date":"2026-08-10T07:00Z","description":"Signed CB Roman Parodie. Placed DB Kemon Hall on injured reserve."},
            {"date":"2026-07-31T07:00Z","description":"Reverted DT Haggai Chisom Ndubuisi to the PUP list."},
            {"date":"2026-07-30T07:00Z","description":"Signed CB Ifeatu Melifonwu and DT Travis Shaw to contracts. Waived DT Haggai Chisom Ndubuisi."},
            {"date":"2026-07-29T07:00Z","description":"Signed DT Travis Shaw. Waived DT Haggai Chisom Ndubuisi."},
            {"date":"2026-07-28T07:00Z","description":"Waived DB Ja'Qurious Conley. Placed DB Chase Lucas and DT Haggai Chisom Ndubuisi on the active/PUP list."},
        ],
    },
    "TEN": {
        news: [
            {"id":"49609587","headline":"Titans down the 49ers in preseason","summary":"Titans down the 49ers in preseason","date":"2026-08-14T14:16:26Z","url":"https://www.espn.com/video/clip/_/id/49609587/titans-49ers-preseason"},
            {"id":"49605904","headline":"Cam Ward struggles in the Titans' 19-13 preseason win over the 49ers","summary":"— Cam Ward struggled in three drives for Tennessee against San Francisco's backup defense and the...","date":"2026-08-14T15:43:29Z","url":"http://www.espn.com/nfl/recap?gameId=401874392"},
            {"id":"49419824","headline":"2026 Tennessee Titans training camp: Latest intel, updates","summary":"Catch up on our daily updates from Titans training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-13T19:51:58Z","url":"https://www.espn.com/nfl/story/_/id/49419824/tennessee-titans-training-camp-2026-intel-updates"},
            {"id":"49574642","headline":"Titans WR Ayomanor standing out above all in training camp","summary":"After an inconsistent rookie season, the Tennessee receiver had a laser-focused offseason.","date":"2026-08-11T10:00:11Z","url":"https://www.espn.com/nfl/story/_/id/49574642/tennessee-titans-wr-elic-ayomanor-stand-training-camp-year-2"},
        ],
        transactions: [
            {"date":"2026-08-10T07:00Z","description":"Waived LB Shad Banks."},
            {"date":"2026-08-07T07:00Z","description":"Signed G Peter Skoronski to a multi-year contract extension."},
            {"date":"2026-08-06T07:00Z","description":"Signed LB Dominique Hampton to a contract. Waived/injured LB Shad Banks Jr."},
            {"date":"2026-08-02T07:00Z","description":"Signed DB Derrick Canteen, DT Khalen Saunders and NT Laki Tasi. Waived DE David Ebuka Agoha, DB Hudson Clark and DT Cam Horsley."},
            {"date":"2026-08-01T07:00Z","description":"Signed CB Mario Goodrich. Waived CB Jeadyn Lukus."},
        ],
    },
    "WAS": {
        news: [
            {"id":"49615272","headline":"Commanders' RB competition heats up after preseason win","summary":"John Keim breaks down the play from RBs Kaytron Allen and Robert Henry Jr. after the Commanders' preseason win against the Dolphins.","date":"2026-08-15T04:50:43Z","url":"https://www.espn.com/video/clip/_/id/49615272/commanders-rb-competition-heats-preseason-win"},
            {"id":"49614504","headline":"Miami Dolphins vs. Washington Commanders Game Highlights","summary":"Miami Dolphins vs. Washington Commanders Game Highlights","date":"2026-08-15T02:52:53Z","url":"https://www.espn.com/video/clip/_/id/49614504/miami-dolphins-vs-washington-commanders-game-highlights"},
            {"id":"49614344","headline":"Dolphins' Malik Willis has impressive start, Marcus Mariota injured as Commanders win 20-7","summary":"— Malik Willis got off to an impressive start as Miami's new quarterback, leading a 14-play, 93-yard touchdown drive as the Dolphins lost 20-7 to the Washington Commanders Friday n…","date":"2026-08-15T03:45:41Z","url":"http://www.espn.com/nfl/recap?gameId=401873277"},
            {"id":"49611801","headline":"Commanders' Dorance Armstrong suspended for season opener","summary":"Commanders defensive end/linebacker Dorance Armstrong has been suspended without pay for the season opener for violating the NFL's personal conduct policy.","date":"2026-08-14T21:17:35Z","url":"https://www.espn.com/nfl/story/_/id/49611801/commanders-dorance-armstrong-suspended-season-opener"},
        ],
        transactions: [
            {"date":"2026-08-12T07:00Z","description":"Waived G Sala Aumavae-Laulu and S Rob McDaniel."},
            {"date":"2026-08-11T07:00Z","description":"Signed DT Byron Cowart. Released G Sala Aumavae-Laulu and S Rob McDaniel. Signed LB Curtis Jacobs to a contract."},
            {"date":"2026-08-09T07:00Z","description":"Waived G Timothy McKay."},
            {"date":"2026-08-08T07:00Z","description":"Placed DT D.J. Davidson on the retired list. Signed C Daniel Brunskill, T Nicholas Petit-Frere, and G Max Scharping. Waived WR Chris Hilton and T Timothy McKay."},
            {"date":"2026-08-07T07:00Z","description":"Signed WR Stefon Diggs to a contract. Activated CB Trey Amos, DE Dorance Armstrong and P Tress Way from the PUP list. Released G Tyler Cooper."},
        ],
    },
};

export const getOffseasonNews = (abbr) => offseasonNews[abbr] || { news: [], transactions: [] };
