// Auto-generated by scripts/updateOffseason.js — do not edit by hand.
// Source: ESPN public NFL news + transactions feeds, read 2026-08-04T04:15:49.655Z.
// Refresh with: npm run offseason
//
// Hand-curated coaching/moves/key points live in offseasonData.js.
// This file carries live headlines and roster transactions only.

export const OFFSEASON_NEWS_UPDATED_AT = "2026-08-04T04:15:49.655Z";

export const offseasonNews = {
    "ARI": {
        news: [
            {"id":"49426382","headline":"2026 Arizona Cardinals training camp: Latest intel, updates","summary":"Follow our daily updates from Cardinals training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-04T01:45:43Z","url":"https://www.espn.com/nfl/story/_/id/49426382/arizona-cardinals-training-camp-2026-intel-updates"},
            {"id":"49355483","headline":"Betting on the Arizona Cardinals in 2026: Cards the longest of long shots","summary":"Examining the Cardinals' outlook for 2026, the ways to bet them and our best bet going into the NFL season.","date":"2026-07-30T10:45:20Z","url":"https://www.espn.com/espn/betting/story/_/id/49355483/arizona-cardinals-betting-outlook-2026"},
        ],
        transactions: [
            {"date":"2026-08-03T07:00Z","description":"Claimed RB Evan Hull off waivers from Houston and DT Cam Horsley off waivers from Tennessee. Waived DT Coziah Izzard and WR Tejhuan Palmer."},
            {"date":"2026-08-01T07:00Z","description":"Signed DL Broderic Martin. Placed DL P.J. Mustipher on injured reserve. Waived RB Chris Collier."},
            {"date":"2026-07-31T07:00Z","description":"Signed CB Quinton Newsome to a contract. Placed CB Jaden Davis on injured reserve."},
            {"date":"2026-07-23T07:00Z","description":"Placed OT Paris Johnson, TE Tip Reiman, OLB Josh Sweat and CB Garrett Williams on the PUP list."},
            {"date":"2026-07-22T07:00Z","description":"Signed QB Carson Beck to a rookie contract. Placed DT Kaleb Proctor on injured reserve. Signed DT Coziah Izzard to a contract."},
        ],
    },
    "ATL": {
        news: [
            {"id":"49448429","headline":"2026 Atlanta Falcons training camp: Latest intel, updates","summary":"Follow our daily updates from Falcons training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T18:01:24Z","url":"https://www.espn.com/nfl/story/_/id/49448429/atlanta-falcons-training-camp-2026-intel-updates"},
            {"id":"49505699","headline":"Falcons sign guard Matthew Bergeron to 4-year, $96M extension","summary":"The Falcons have signed starting left guard Matthew Bergeron to a four-year extension that sources said is worth $96 million with $60 million guaranteed.","date":"2026-08-01T18:09:30Z","url":"https://www.espn.com/nfl/story/_/id/49505699/falcons-sign-matthew-bergeron-four-year-96m-extension"},
            {"id":"49504750","headline":"Why Bijan Robinson hasn't signed a new deal with Falcons yet","summary":"Why Bijan Robinson hasn't signed a new deal with Falcons yet","date":"2026-08-01T14:52:59Z","url":"https://www.espn.com/video/clip/_/id/49504750/why-bijan-robinson-signed-new-deal-falcons-yet"},
        ],
        transactions: [
            {"date":"2026-08-01T07:00Z","description":"Signed G Matthew Bergeron to a 4-year, $96M contract extension."},
            {"date":"2026-07-30T07:00Z","description":"Released DT Ross Blacklock. Signed LB Josh Woods to a contract."},
            {"date":"2026-07-29T07:00Z","description":"Signed QB Cooper Rush to a contract."},
            {"date":"2026-07-22T07:00Z","description":"Waived DE C.J. Nunnally and WR Casey Washington. Released DT Elijah Garcia. Signed DE Keshawn Banks, DT Devonnsha Maxwell and WR Antwane Wells to contracts."},
            {"date":"2026-06-18T07:00Z","description":"Signed P Matthew Hayball to a contract."},
        ],
    },
    "BAL": {
        news: [
            {"id":"49434567","headline":"2026 Baltimore Ravens training camp: Latest intel, updates","summary":"Follow our daily updates from Ravens training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T20:17:22Z","url":"https://www.espn.com/nfl/story/_/id/49434567/baltimore-ravens-training-camp-2026-intel-updates"},
            {"id":"49496459","headline":"How will Lamar Jackson affect the Ravens' running game this season?","summary":"How will Lamar Jackson affect the Ravens' running game this season?","date":"2026-07-31T14:27:27Z","url":"https://www.espn.com/video/clip/_/id/49496459/how-lamar-jackson-affect-ravens-running-game-season"},
            {"id":"49490329","headline":"Ravens' Henry, entering 11th year, not thinking about retirement","summary":"Ravens running back Derrick Henry said Thursday he isn't contemplating calling it quits as he enters his 11th NFL season.","date":"2026-07-30T19:07:07Z","url":"https://www.espn.com/nfl/story/_/id/49490329/ravens-henry-entering-11th-year-not-thinking-retirement"},
            {"id":"49480322","headline":"Ravens' Madubuike (neck) practices for 1st time in 10 months","summary":"Pro Bowl defensive tackle Nnamdi Madubuike practiced for the first time in 10 months on Wednesday, which provided a celebratory start to the Ravens' first training camp under coach…","date":"2026-07-29T18:04:46Z","url":"https://www.espn.com/nfl/story/_/id/49480322/ravens-madubuike-neck-practices-1st-10-months"},
        ],
        transactions: [
            {"date":"2026-08-03T07:00Z","description":"Reinstated NT John Jenkin from the active/non-football injury list."},
            {"date":"2026-08-02T07:00Z","description":"Placed OL Hakeem Adeniji on the reserve/retired list."},
            {"date":"2026-07-31T07:00Z","description":"Activated OLB Adisa Isaac and CB Bilhal Kone from the PUP list."},
            {"date":"2026-07-25T07:00Z","description":"Waived P Luke Elzinga and G Jared Penning. Signed OL Hakeem Adeniji and WR Chris Moore."},
            {"date":"2026-07-23T07:00Z","description":"Waived QB Diego Pavia."},
        ],
    },
    "BUF": {
        news: [
            {"id":"49434544","headline":"2026 Buffalo Bills training camp: Latest intel, updates","summary":"Follow our daily updates from Bills training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T20:17:50Z","url":"https://www.espn.com/nfl/story/_/id/49434544/buffalo-bills-training-camp-2026-intel-updates"},
            {"id":"49509353","headline":"Gardner-Johnson pays off $20,000 of Bills staffer's student loans","summary":"During a Twitch stream Thursday, the Bills' safety gave a huge gift to a graduate student working with the team's training staff.","date":"2026-08-02T16:05:51Z","url":"https://www.espn.com/nfl/story/_/id/49509353/cj-gardner-johnson-buffalo-bills-student-loans-20000-twitch-stream"},
            {"id":"49510846","headline":"Bills dodge injury scare","summary":"C.J. Gardner Johnson avoids a serious injury after tests reveal a lower calf strain.","date":"2026-08-02T06:58:19Z","url":"https://www.espn.com/video/clip/_/id/49510846/bills-dodge-injury-scare"},
            {"id":"49505167","headline":"Source: Bills S C.J. Gardner-Johnson has lower calf strain","summary":"Buffalo Bills safety C.J. Gardner-Johnson was carted to the locker room after suffering a lower-body injury during training camp practice Saturday, and a source later told ESPN's A…","date":"2026-08-01T22:24:11Z","url":"https://www.espn.com/nfl/story/_/id/49505167/bills-safety-gardner-johnson-carted-leg-injury"},
        ],
        transactions: [
            {"date":"2026-07-31T07:00Z","description":"Signed CB D.J. Miller to a contract. Released S Wande Owens."},
            {"date":"2026-07-30T07:00Z","description":"Waived/injured WR Jalen Virgil. Signed WR Dante Pettis to a contract."},
            {"date":"2026-07-28T07:00Z","description":"Placed WR Tyrell Shavers on the active/PUP list."},
            {"date":"2026-07-14T07:00Z","description":"Claimed WR Quentin Skinner off waivers from the N.Y. Jets. Released WR Deven Thompkins."},
            {"date":"2026-06-22T07:00Z","description":"Waived RB Desmond Reid from injured reserve."},
        ],
    },
    "CAR": {
        news: [
            {"id":"49522616","headline":"Panthers VP says decision on Bryce Young deal 'collaborative'","summary":"The Panthers remain tight-lipped about the long-term contractual future of quarterback Bryce Young as he prepares to enter his fourth NFL season.","date":"2026-08-03T19:03:36Z","url":"https://www.espn.com/nfl/story/_/id/49522616/panthers-vp-says-decision-bryce-young-deal-collaborative"},
            {"id":"49377273","headline":"2026 Carolina Panthers training camp: Latest intel, updates","summary":"Follow our updates from Panthers training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T23:47:52Z","url":"https://www.espn.com/nfl/story/_/id/49377273/carolina-panthers-training-camp-2026-intel-updates"},
            {"id":"49507879","headline":"Injuries shadow Panthers' team scrimmage in front of fans","summary":"The Panthers scrimmaged in front of approximately 40,000 fans in their first appearance on their home turf since losing in the opening round of the playoffs.","date":"2026-08-01T22:12:39Z","url":"https://www.espn.com/nfl/story/_/id/49507879/injuries-shadow-panthers-team-scrimmage-front-fans"},
            {"id":"49489959","headline":"Panthers WR Chris Brazzell to have season-ending knee surgery","summary":"Panthers rookie wide receiver Chris Brazzell II will undergo season-ending surgery on his torn LCL in his left knee.","date":"2026-07-30T19:12:36Z","url":"https://www.espn.com/nfl/story/_/id/49489959/panthers-wr-brazzell-season-ending-surgery-source-says"},
        ],
        transactions: [
            {"date":"2026-08-03T07:00Z","description":"Reinstated DT Bobby Brown III from the active/non-football injury list."},
            {"date":"2026-07-31T07:00Z","description":"Placed WR Chris Brazzell on injured reserve. Signed TE Chamon Metayer to a contract. Waived"},
            {"date":"2026-07-30T07:00Z","description":"Signed WR Gabriel Benyard to a contract. Waived DT Parker Petersen."},
            {"date":"2026-07-29T07:00Z","description":"Signed WR Casey Washington to a contract."},
            {"date":"2026-07-28T07:00Z","description":"Activated CB Jaycee Horn from the active/non-football injury list."},
        ],
    },
    "CHI": {
        news: [
            {"id":"49448378","headline":"2026 Chicago Bears training camp: Latest intel, updates","summary":"Follow our daily updates from Bears training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T20:33:45Z","url":"https://www.espn.com/nfl/story/_/id/49448378/chicago-bears-training-camp-2026-intel-updates"},
            {"id":"49522578","headline":"New Bears safety Coby Bryant out 8-10 weeks with injury","summary":"Bears new safety Coby Bryant will miss eight to 10 weeks with a leg injury.","date":"2026-08-03T19:48:21Z","url":"https://www.espn.com/nfl/story/_/id/49522578/new-bears-safety-coby-bryant-8-10-weeks-injury"},
            {"id":"49519975","headline":"Will a 'more talented' Bears regress this season?","summary":"Will a 'more talented' Bears regress this season?","date":"2026-08-03T13:46:16Z","url":"https://www.espn.com/video/clip/_/id/49519975/will-more-talented-bears-regress-season"},
            {"id":"49505992","headline":"Bears CB Johnson views 2026 as 'definitely a contract year'","summary":"Bears cornerback Jaylon Johnson is approaching the 2026 season with his sights set on another payday.","date":"2026-08-01T21:00:04Z","url":"https://www.espn.com/nfl/story/_/id/49505992/bears-cb-johnson-views-2026-definitely-contract-year"},
        ],
        transactions: [
            {"date":"2026-07-29T07:00Z","description":"Reinstated DL Montez Sweat from the active/non-football illness list."},
            {"date":"2026-07-28T07:00Z","description":"Placed DB Elijah Hicks on the active/PUP list. Placed DL Montez Sweat on the active/non-football illness list."},
            {"date":"2026-07-10T07:00Z","description":"Signed TE Sam Roush to a rookie contract."},
            {"date":"2026-06-16T07:00Z","description":"Signed WR Kaden Davis and LB Tony Fields II to contracts. Waived LB Dominique Hampton and K Gabriel Plascencia."},
            {"date":"2026-05-26T07:00Z","description":"Waived RB Deion Hankins."},
        ],
    },
    "CIN": {
        news: [
            {"id":"49448120","headline":"2026 Cincinnati Bengals training camp: Latest intel, updates","summary":"Follow our daily updates from Bengals training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T18:25:57Z","url":"https://www.espn.com/nfl/story/_/id/49448120/cincinnati-bengals-training-camp-2026-intel-updates"},
            {"id":"49512851","headline":"Joe Burrow, Bengals find camaraderie on unusual battlefield","summary":"Center Ted Karras brought a chessboard into the locker room, and it has become a hit.","date":"2026-08-03T10:28:18Z","url":"https://www.espn.com/nfl/story/_/id/49512851/joe-burrow-cincinnati-bengals-find-camaraderie-unusual-battlefield"},
            {"id":"49508634","headline":"Bengals looking to have more of an edge","summary":"Ben Baby reports on how the Bengals' new acquisitions are providing a level of competitiveness heading into the next season.","date":"2026-08-02T00:01:40Z","url":"https://www.espn.com/video/clip/_/id/49508634/bengals-looking-more-edge"},
        ],
        transactions: [
            {"date":"2026-07-25T07:00Z","description":"Placed DT B.J. Hill on the pup list. Placed TE Josh Jattus on the non-football injury list."},
            {"date":"2026-06-09T07:00Z","description":"Signed DE Cashius Howell to a rookie contract."},
            {"date":"2026-05-13T07:00Z","description":"Signed CB Tacario Davis to a rookie contract."},
            {"date":"2026-05-08T07:00Z","description":"Signed G Liam Brown, RBs Kentrel Bullock and Jamal Haynes, LBs Jack Dingle and Eric Gentry, OTs Christian Jones and Corey Robinson II, TE Josh Kattus, WR Noah Thomas and CB Ceyair Wright to UDFA contracts. Signed C Connor Lew, WR Colbie Young, OT Brian Parker II, TE Jack Endries and DT Landon Robinson to rookie contracts. Claimed LB Swayze Bozeman off waivers from the N.Y. Giants. Signed S Isaiah Nwokobia to a UDFA contract."},
            {"date":"2026-04-20T07:00Z","description":"Acquired NT Dexter Lawrence from the New York Giants in exchange for a 2026 first-round draft pick."},
        ],
    },
    "CLE": {
        news: [
            {"id":"49449000","headline":"2026 Cleveland Browns training camp: Latest intel, updates","summary":"Follow our daily updates from Browns training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T22:27:15Z","url":"https://www.espn.com/nfl/story/_/id/49449000/cleveland-browns-training-camp-2026-intel-updates"},
            {"id":"49515833","headline":"Here's what to know about the Browns' QB competition","summary":"Daniel Oyefusi breaks down the Browns' quarterback competition after the first week of training camp.","date":"2026-08-02T22:13:49Z","url":"https://www.espn.com/video/clip/_/id/49515833/here-know-browns-qb-competition"},
            {"id":"49489789","headline":"Deion Sanders gives Browns 'insight' on Shedeur Sanders","summary":"Hall of Famer Deion Sanders visited the Browns at training camp Thursday and provided coach Todd Monken with some \"insight\" on Shedeur Sanders.","date":"2026-07-30T17:55:34Z","url":"https://www.espn.com/nfl/story/_/id/49489789/deion-sanders-gives-browns-insight-shedeur-sanders"},
        ],
        transactions: [
            {"date":"2026-08-03T07:00Z","description":"Signed DT Travis Bell. Waived RB T.J. Harden."},
            {"date":"2026-07-30T07:00Z","description":"Signed S Grant Delpit to a three-year contract extension."},
            {"date":"2026-07-29T07:00Z","description":"Signed CB Denzel Ward to a two-year contract extension."},
            {"date":"2026-07-23T07:00Z","description":"Placed DT Maliek Collins on the PUP list."},
            {"date":"2026-07-21T07:00Z","description":"Signed CB Damarri Mathis to a contract."},
        ],
    },
    "DAL": {
        news: [
            {"id":"49524799","headline":"CB Shavon Revel Jr. shines in Cowboys camp","summary":"Todd Archer breaks down Shavon Revel Jr.'s impressive performance in the Cowboys' first padded practice.","date":"2026-08-03T23:42:47Z","url":"https://www.espn.com/video/clip/_/id/49524799/cb-shavon-revel-jr-shines-cowboys-camp"},
            {"id":"49376535","headline":"2026 Dallas Cowboys training camp: Latest intel, updates","summary":"Follow our daily updates from Cowboys training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T21:53:37Z","url":"https://www.espn.com/nfl/story/_/id/49376535/dallas-cowboys-training-camp-2026-intel-updates"},
            {"id":"49510207","headline":"Cowboys sharpen red zone attack","summary":"Dak Prescott throws four touchdown passes during Saturday's red zone work.","date":"2026-08-02T04:32:20Z","url":"https://www.espn.com/video/clip/_/id/49510207/cowboys-sharpen-red-zone-attack"},
            {"id":"49496600","headline":"Evan Cohen puzzled why Cowboys are in Super Bowl conversation","summary":"Evan Cohen puzzled why Cowboys are in Super Bowl conversation","date":"2026-07-31T14:38:57Z","url":"https://www.espn.com/video/clip/_/id/49496600/evan-cohen-puzzled-why-cowboys-super-bowl-conversation"},
        ],
        transactions: [
            {"date":"2026-08-03T07:00Z","description":"Signed OL Sebastian Gutierrez. Reverted OLB Charles Snowden to injured reserve after he cleared waivers."},
            {"date":"2026-08-02T07:00Z","description":"Signed T Sebastian Gutierrez. Waived DE Charles Snowden."},
            {"date":"2026-06-22T07:00Z","description":"Signed DE Charles Snowden to a a contract."},
            {"date":"2026-06-18T07:00Z","description":"Signed DE Charles Snowden, WR Denzel Mims, OL Chris Glaser, and CB Ameer Speed. Paced OL Matt Hennessey on IR. Waived CB Corey Ballentine and WR Romello Brinson."},
            {"date":"2026-06-03T07:00Z","description":"Signed WR Jaden Smith to a contract."},
        ],
    },
    "DEN": {
        news: [
            {"id":"49379469","headline":"2026 Denver Broncos training camp: Latest intel, updates","summary":"Follow our daily updates from Broncos training camp, including intel on the QBs, position battles and potential breakouts.","date":"2026-08-03T20:34:53Z","url":"https://www.espn.com/nfl/story/_/id/49379469/denver-broncos-training-camp-2026-intel-updates"},
            {"id":"49523079","headline":"Sean Payton to talk to Taysom Hill about interest in Broncos","summary":"Broncos coach Sean Payton told reporters Monday he will talk to free agent Taysom Hill, 35, to gauge the veteran's interest in continuing his career, potentially with Denver, after…","date":"2026-08-03T20:22:00Z","url":"https://www.espn.com/nfl/story/_/id/49523079/sean-payton-talk-taysom-hill-interest-broncos"},
            {"id":"49507138","headline":"Broncos QB Bo Nix not afraid to run on repaired ankle","summary":"Broncos quarterback Bo Nix says he will not hesitate to scramble on his surgically repaired right ankle this season and that when he's on the move is \"when I feel at my best\" on th…","date":"2026-08-02T16:40:16Z","url":"https://www.espn.com/nfl/story/_/id/49507138/broncos-qb-bo-nix-afraid-run-repaired-ankle"},
            {"id":"49499783","headline":"How will Broncos' Sean Payton adjust to not calling plays?","summary":"Payton has doubled as head coach and playcaller for two decades. But now he enters relatively uncharted waters after turning over playcalling duties.","date":"2026-08-01T10:00:11Z","url":"https://www.espn.com/nfl/story/_/id/49499783/sean-payton-denver-broncos-head-coach-adjust-not-calling-plays-davis-webb"},
        ],
        transactions: [
            {"date":"2026-08-02T07:00Z","description":"Waived DB Blake Cotton."},
            {"date":"2026-08-01T07:00Z","description":"Reverted DB Blake Cotton to injured reserve after clearing waivers."},
            {"date":"2026-07-31T07:00Z","description":"Signed DB Sam Webb. Waived DB Blake Cotton."},
            {"date":"2026-07-26T07:00Z","description":"Placed G Nick Gargiulo on the active/PUP list. Placed LB Jordan Tanner on the non-football injury list."},
            {"date":"2026-07-22T07:00Z","description":"Reverted WR Mike Woods to injured reserve after he cleared waivers."},
        ],
    },
    "DET": {
        news: [
            {"id":"49521507","headline":"What does Jahmyr Gibbs bring to the Lions' offense?","summary":"What does Jahmyr Gibbs bring to the Lions' offense?","date":"2026-08-03T17:03:45Z","url":"https://www.espn.com/video/clip/_/id/49521507/what-does-jahmyr-gibbs-bring-lions-offense"},
            {"id":"49419620","headline":"2026 Detroit Lions training camp: Latest intel, updates","summary":"Follow our daily updates from Lions training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T17:00:24Z","url":"https://www.espn.com/nfl/story/_/id/49419620/detroit-lions-training-camp-2026-intel-updates"},
            {"id":"49520984","headline":"Lions' Gibbs on hold-in: 'Time will tell' when I return to field","summary":"Lions running back Jahmyr Gibbs said Monday that \"only time will tell\" when he will return to practice as he seeks a contract extension.","date":"2026-08-03T17:11:32Z","url":"https://www.espn.com/nfl/story/_/id/49520984/lions-gibbs-hold-tell-return-field"},
            {"id":"49507201","headline":"Ex-All Pro LB Devin White joins Lions on 1-year deal","summary":"The Detroit Lions are signing former All-Pro linebacker Devin White to a one-year deal, the team announced Saturday.","date":"2026-08-01T22:32:08Z","url":"https://www.espn.com/nfl/story/_/id/49507201/ex-all-pro-lb-devin-white-joins-lions-1-year-deal"},
        ],
        transactions: [
            {"date":"2026-08-03T07:00Z","description":"Signed TE Nick Muse. Released WR Tarik Black."},
            {"date":"2026-08-02T07:00Z","description":"Reinstated DB Christian Izien from the active/non-football injury list."},
            {"date":"2026-08-01T07:00Z","description":"Signed LB Devin White to a 1-year contract."},
            {"date":"2026-07-31T07:00Z","description":"Signed TE Anthony Fisker to a contract. Waived TE Zach Horton. Activated G Christian Mahogany from the non-football injury list."},
            {"date":"2026-07-28T07:00Z","description":"Released DL Jay Tufele. Placed DB Christian Izien on the active/non-football illness list. Placed OL Christian Mahogany on the active/non-football injury list."},
        ],
    },
    "GB": {
        news: [
            {"id":"49376941","headline":"2026 Green Bay Packers training camp: Latest intel, updates","summary":"Follow our daily updates from Packers training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T21:30:21Z","url":"https://www.espn.com/nfl/story/_/id/49376941/green-bay-packers-training-camp-2026-intel-updates"},
            {"id":"49516001","headline":"Lukas Van Ness impresses at Packers training camp","summary":"Rob Demovsky breaks down Lukas Van Ness stepping in while Micah Parsons is out of training camp.","date":"2026-08-02T22:56:09Z","url":"https://www.espn.com/video/clip/_/id/49516001/lukas-van-ness-impresses-packers-training-camp"},
            {"id":"49514420","headline":"Packers RT changes last name to Bako-Bewele to honor heritage","summary":"Packers right tackle Zach Tom revealed Sunday he has changed his name to Zach Bako-Bewele.","date":"2026-08-02T22:32:31Z","url":"https://www.espn.com/nfl/story/_/id/49514420/packers-rt-changes-last-name-bako-bewele-honor-heritage"},
            {"id":"49500145","headline":"Why Tucker Kraft could be key player to Packers' Super Bowl window","summary":"Before his season-ending injury in 2025, Kraft was on his way to securing a spot among the NFL's elite tight ends.","date":"2026-08-01T10:47:19Z","url":"https://www.espn.com/nfl/story/_/id/49500145/green-bay-packers-tucker-kraft-returns"},
        ],
        transactions: [
            {"date":"2026-08-03T07:00Z","description":"Reinstated T Brant Banks from the active/PUP list."},
            {"date":"2026-08-02T07:00Z","description":"Reinstated DB Kamal Hadden from the active/PUP list."},
            {"date":"2026-07-31T07:00Z","description":"Signed LS Cal Adomitis and WR Kaden Prather to contracts. Released K Lenny Krieg. Waived/injured WR Brenden Rice. Activated TE Tucker Kraft from the PUP list."},
            {"date":"2026-07-29T07:00Z","description":"Reinstated G Aaron Banks and DT Nazir Stackhouse from the active/PUP list. Placed WR Brenden Rice on the active/non-football injury list."},
            {"date":"2026-07-28T07:00Z","description":"Signed K Lenny Krieg and TE Thomas Yassmin. Released EDGE Dante Barnett and K Lucas Havrisik. Placed Ts Brant Banks, LS Matt Orzech, LB Micah Parsons, DE Jordon Riley and DT Nazir Stackhouse on the active/PUP list."},
        ],
    },
    "HOU": {
        news: [
            {"id":"49523317","headline":"Houston Texans' Jalen Pitre becomes first Guardian Caps signature athlete","summary":"The Houston Texans safety is the first Guardian Caps signature athlete and wore the helmet in eight games last season.","date":"2026-08-03T21:15:26Z","url":"https://www.espn.com/nfl/story/_/id/49523317/houston-texans-jalen-pitre-nfl-guardians-cap-signature-athlete"},
            {"id":"49522327","headline":"Texans have a successful first day of practice with pads","summary":"DJ BienAime breaks down the Texans' first day of pads at training camp.","date":"2026-08-03T18:13:07Z","url":"https://www.espn.com/video/clip/_/id/49522327/texans-successful-first-day-practice-pads"},
            {"id":"49419567","headline":"2026 Houston Texans training camp: Latest intel, updates","summary":"Follow our daily updates from Houston Texans training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T18:17:51Z","url":"https://www.espn.com/nfl/story/_/id/49419567/houston-texans-training-camp-2026-intel-updates"},
            {"id":"49514656","headline":"Pass rusher Jadeveon Clowney reaches deal to reunite with Texans","summary":"Jadeveon Clowney is returning to the Texans, the team that selected him No. 1 in the 2014 NFL draft.","date":"2026-08-03T02:09:33Z","url":"https://www.espn.com/nfl/story/_/id/49514656/sources-jadeveon-clowney-reaches-deal-reunite-texans"},
        ],
        transactions: [
            {"date":"2026-08-02T07:00Z","description":"Signed DT Mario Edwards Jr. Waived T Derrick Graham and RB Evan Hull."},
            {"date":"2026-07-29T07:00Z","description":"Signed WR DJ Turner. Waived TE Louis Hansen."},
            {"date":"2026-07-28T07:00Z","description":"Placed LBs E.J. Speed and DB M.J. Stewart on the active/PUP list. Placed WR Jaylin Noel on the active/non-football injury list."},
            {"date":"2026-07-16T07:00Z","description":"Signed OL Febechi Nwaiwu to a rookie contract."},
            {"date":"2026-07-02T07:00Z","description":"Waived DB Ajani Carter and OLB Xavier Thomas from injured reserve."},
        ],
    },
    "IND": {
        news: [
            {"id":"49522576","headline":"Colts have wide receiver uncertainty in training camp","summary":"Stephen Holder breaks down the uncertainty in the Colts' wide receiver group.","date":"2026-08-03T19:27:18Z","url":"https://www.espn.com/video/clip/_/id/49522576/colts-wide-receiver-uncertainty-training-camp"},
            {"id":"49448214","headline":"2026 Indianapolis Colts training camp: Latest intel, updates","summary":"Follow our daily updates from Colts training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T18:47:46Z","url":"https://www.espn.com/nfl/story/_/id/49448214/indianapolis-colts-training-camp-2026-intel-updates"},
            {"id":"49488952","headline":"Tons at stake as Colts' Daniel Jones enters proving ground","summary":"If Jones can't recapture his early-season magic from last year, will it signal the end of QB1 status?","date":"2026-08-01T10:00:11Z","url":"https://www.espn.com/nfl/story/_/id/49488952/indianapolis-colts-daniel-jones-achilles"},
            {"id":"49471933","headline":"Colts GM sees QB room with Anthony Richardson, despite trade ask","summary":"Colts GM Chris Ballard said he envisions a final roster with all three of his top quarterbacks -- despite Anthony Richardson's trade request earlier this year.","date":"2026-07-28T18:44:57Z","url":"https://www.espn.com/nfl/story/_/id/49471933/colts-gm-sees-qb-room-anthony-richardson-trade-ask"},
        ],
        transactions: [
            {"date":"2026-08-03T07:00Z","description":"Signed CB Mekhi Rodgers. Waived/injured CB Cameron Mitchell."},
            {"date":"2026-07-31T07:00Z","description":"Activated LB C.J. Allen from the PUP list. Signed RB Roydell Williams to a contract."},
            {"date":"2026-07-30T07:00Z","description":"Signed WR Liam Clifford to a contract."},
            {"date":"2026-07-27T07:00Z","description":"Placed WR Alec Pierce and LB C.J. Allen on the PUP list. Waived RB Lincoln Pare."},
            {"date":"2026-06-09T07:00Z","description":"Placed S Reuben Lowery III on the reserve/retired list."},
        ],
    },
    "JAX": {
        news: [
            {"id":"49427691","headline":"2026 Jacksonville Jaguars training camp: Latest intel, updates","summary":"Follow our daily updates from Jaguars training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T16:42:31Z","url":"https://www.espn.com/nfl/story/_/id/49427691/jacksonville-jaguars-training-camp-2026-intel-updates"},
            {"id":"49498108","headline":"Jaguars' Travis Hunter feeling faster even with weight gain","summary":"Travis Hunter is 10 pounds heavier than his rookie season but faster than he has ever been.","date":"2026-07-31T18:40:24Z","url":"https://www.espn.com/nfl/story/_/id/49498108/jaguars-travis-hunter-feeling-faster-even-weight-gain"},
        ],
        transactions: [
            {"date":"2026-08-02T07:00Z","description":"Signed LB Jared Bartlett. Waived WR Ben Patterson."},
            {"date":"2026-07-28T07:00Z","description":"Signed CB Corey Ballentine to a contract. Placed DB Dane Jackson on the reserve/retired list."},
            {"date":"2026-07-26T07:00Z","description":"Placed Ts Cole Van Lanen and Garrett DiGiorgio on the active/PUP list."},
            {"date":"2026-06-15T07:00Z","description":"Terminated CB Keith Taylor from injured reserve with a settlement."},
            {"date":"2026-06-04T07:00Z","description":"Signed OL Trystan Colon and CB Dane Jackson to contracts. Placed CB Keith Taylor on injured reserve. Waived OL Sal Wormley."},
        ],
    },
    "KC": {
        news: [
            {"id":"49447878","headline":"2026 Kansas City Chiefs training camp: Latest intel, updates","summary":"Follow our daily updates from Chiefs training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T20:18:17Z","url":"https://www.espn.com/nfl/story/_/id/49447878/kansas-city-chiefs-training-camp-2026-intel-updates"},
            {"id":"49521237","headline":"Why Stephen A. won't count out the Chiefs as Super Bowl contenders","summary":"Why Stephen A. won't count out the Chiefs as Super Bowl contenders","date":"2026-08-03T16:10:44Z","url":"https://www.espn.com/video/clip/_/id/49521237/why-stephen-count-chiefs-super-bowl-contenders"},
            {"id":"49507020","headline":"Cyrus Allen suffers leg injury at Chiefs practice","summary":"Nate Taylor breaks down Cyrus Allen's injury he suffered at Chiefs training camp on Saturday.","date":"2026-08-01T20:19:25Z","url":"https://www.espn.com/video/clip/_/id/49507020/cyrus-allen-suffers-leg-injury-chiefs-practice"},
            {"id":"49505881","headline":"Chiefs rookie standout Cyrus Allen bruised, Xavier Worthy injured","summary":"Chiefs wide receiver Cyrus Allen sustained a shin bruise during a special teams drill, a source said, while fellow receiver Xavier Worthy also left the field early because of a sho…","date":"2026-08-02T04:20:47Z","url":"https://www.espn.com/nfl/story/_/id/49505881/chiefs-rookie-standout-cyrus-allen-helped-leg-injury"},
        ],
        transactions: [
            {"date":"2026-08-03T07:00Z","description":"Signed WR Jeff Weimer."},
            {"date":"2026-08-01T07:00Z","description":"Signed DE Ethan Hurkett."},
            {"date":"2026-07-28T07:00Z","description":"Placed LB Ethan Downs and TE John Michael Gyllenborg on injured reserve."},
            {"date":"2026-07-22T07:00Z","description":"Signed TE Mason Pline to a contract."},
            {"date":"2026-06-16T07:00Z","description":"Signed TE Mason Pline to a contract."},
        ],
    },
    "LAC": {
        news: [
            {"id":"49424976","headline":"2026 Los Angeles Chargers training camp: Latest intel, updates","summary":"Follow our daily updates from Chargers training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T20:40:59Z","url":"https://www.espn.com/nfl/story/_/id/49424976/los-angeles-chargers-training-camp-2026-intel-updates"},
            {"id":"49502842","headline":"Trey Pipkins III joins Chargers' left guard competition","summary":"Kris Rhim reports on the Chargers' competition at left guard with Trey Pipkins III joining the fray.","date":"2026-08-01T05:45:54Z","url":"https://www.espn.com/video/clip/_/id/49502842/trey-pipkins-iii-joins-chargers-left-guard-competition"},
        ],
        transactions: [
            {"date":"2026-07-28T07:00Z","description":"Signed LS Peter Bowden to a contract."},
            {"date":"2026-07-27T07:00Z","description":"Released G Ben Cleveland."},
            {"date":"2026-07-24T07:00Z","description":"Placed OT Isaiah World on the NFI list."},
            {"date":"2026-05-27T07:00Z","description":"Signed S Derwin James to a three-year contract extension."},
            {"date":"2026-05-21T07:00Z","description":"Waived DB Jerry Wilson."},
        ],
    },
    "LAR": {
        news: [
            {"id":"49434454","headline":"2026 Los Angeles Rams training camp: Latest intel, updates","summary":"Follow our daily updates from Rams training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T23:31:04Z","url":"https://www.espn.com/nfl/story/_/id/49434454/los-angeles-rams-training-camp-2026-intel-updates"},
            {"id":"49515062","headline":"Rams hold Garrett out as he deals with 'a little soreness'","summary":"Los Angeles Rams defensive end Myles Garrett is dealing with \"a little soreness in his lower half,\" Sean McVay said on Sunday, keeping the pass rusher out of practice for the third…","date":"2026-08-02T22:27:43Z","url":"https://www.espn.com/nfl/story/_/id/49515062/rams-hold-garrett-deals-little-soreness"},
            {"id":"49501604","headline":"Rams' Sean McVay: No Aaron Donald update, but 'trending upwards'","summary":"Rams coach Sean McVay says he doesn't expect defensive tackle Aaron Donald to decide about coming out of retirement until after the team returns to its facility but noted that \"thi…","date":"2026-08-01T15:24:23Z","url":"https://www.espn.com/nfl/story/_/id/49501604/rams-coach-sean-mcvay-no-update-aaron-donald-decision-going-right-direction"},
        ],
        transactions: [
            {"date":"2026-07-28T07:00Z","description":"Signed G Blake Hance to a contract."},
            {"date":"2026-07-27T07:00Z","description":"Signed DB Alex Cook and G Bill Murray to contracts."},
            {"date":"2026-07-26T07:00Z","description":"Placed G Justin Dedich on the active/non-football injury list. Placed DB Al'zillion Hamilton on the active/PUP list."},
            {"date":"2026-07-22T07:00Z","description":"Waived C Chad Lindberg."},
            {"date":"2026-06-16T07:00Z","description":"Waived/injured OL Chad Lindberg."},
        ],
    },
    "LV": {
        news: [
            {"id":"49425032","headline":"2026 Las Vegas Raiders training camp: Latest intel, updates","summary":"Follow our daily updates from Raiders training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T23:54:02Z","url":"https://www.espn.com/nfl/story/_/id/49425032/las-vegas-raiders-training-camp-2026-intel-updates"},
            {"id":"49500640","headline":"Maxx Crosby's approaching Raiders training camp with intensity","summary":"We talked to players and coaches about Maxx Crosby's first few days at Raiders training camp.","date":"2026-08-03T10:00:11Z","url":"https://www.espn.com/nfl/story/_/id/49500640/las-vegas-raiders-maxx-crosby-2026-training-camp"},
            {"id":"49518031","headline":"Raiders using Taron Johnson all over the field","summary":"Ryan McFadden lays out how the Raiders plan to utilize cornerback Taron Johnson in the coming season.","date":"2026-08-03T06:04:58Z","url":"https://www.espn.com/video/clip/_/id/49518031/raiders-using-taron-johnson-all-field"},
        ],
        transactions: [
            {"date":"2026-08-02T07:00Z","description":"Reverted RB Chris Collier to injured reserve after he cleared waivers."},
            {"date":"2026-08-01T07:00Z","description":"Signed TE Zack Kuntz."},
            {"date":"2026-07-31T07:00Z","description":"Signed TE Zack Kuntz. Waived/injured RB Chris Collier."},
            {"date":"2026-07-28T07:00Z","description":"Signed LBs Buddy Johnson and Patrick Johnson and WR Deven Thompkins. Waived WR Jonathan Brady, NT Laki Tasi and LB Christian Thomas."},
            {"date":"2026-07-27T07:00Z","description":"Signed LB Buddy Johnson, DE Patrick Johnson and WR Deven Thompson to contracts. Waived WR Jonathan Brady, LB Chris Thomas and DT Laki Tasi."},
        ],
    },
    "MIA": {
        news: [
            {"id":"49524628","headline":"Dolphins got unlikely assist in signing Clelin Ferrell","summary":"Marcel Louis-Jacques reports on the surprise factor that helped make Clelin Ferrell a Dolphin.","date":"2026-08-03T23:00:55Z","url":"https://www.espn.com/video/clip/_/id/49524628/dolphins-got-unlikely-assist-signing-clelin-ferrell"},
            {"id":"49410015","headline":"2026 Miami Dolphins training camp: Latest intel, updates","summary":"Follow our daily updates from Dolphins training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T19:16:11Z","url":"https://www.espn.com/nfl/story/_/id/49410015/miami-dolphins-training-camp-2026-intel-updates"},
            {"id":"49498144","headline":"Dolphins top pick Proctor embracing NFL learning curve","summary":"Proctor, the first draft pick under the Dolphins' new regime, is learning to be a pro, all while learning a new position.","date":"2026-08-01T10:00:11Z","url":"https://www.espn.com/nfl/story/_/id/49498144/2026-nfl-training-camp-miami-dolphins-kadyn-proctor-learning-guard"},
        ],
        transactions: [
            {"date":"2026-07-28T07:00Z","description":"Signed DE Clelin Ferrell. Waived DT Kahlil Saunders to contracts."},
            {"date":"2026-07-27T07:00Z","description":"Signed EDGE Clelin Ferrell to a contract. Waived DL Kahlil Saunders."},
            {"date":"2026-07-23T07:00Z","description":"Placed CBs Darrell Baker Jr. and Storm Duck on the PUP list."},
            {"date":"2026-07-22T07:00Z","description":"Signed ILB Jordyn Brooks to a contract extension through the 2029 season."},
            {"date":"2026-07-21T07:00Z","description":"Placed WR Chris Bell on the active/non-football injury list."},
        ],
    },
    "MIN": {
        news: [
            {"id":"49376202","headline":"2026 Minnesota Vikings training camp: Latest intel, updates","summary":"Follow our daily updates from Vikings training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T23:29:44Z","url":"https://www.espn.com/nfl/story/_/id/49376202/minnesota-vikings-training-camp-2026-intel-updates"},
            {"id":"49513333","headline":"Anniversary of Korey Stringer's death completes reconciliation for family, Vikings","summary":"The Aug. 1 anniversary marked the positives that grew out of a tragic day, including the Korey Stringer Institute.","date":"2026-08-02T19:01:09Z","url":"https://www.espn.com/nfl/story/_/id/49513333/anniversary-korey-stringer-death-completes-reconciliation-family-vikings"},
            {"id":"49480259","headline":"Why Riddick expects Kyler Murray to win the QB battle in Minnesota","summary":"Why Riddick expects Kyler Murray to win the QB battle in Minnesota","date":"2026-07-29T15:25:14Z","url":"https://www.espn.com/video/clip/_/id/49480259/why-riddick-expects-kyler-murray-win-qb-battle-minnesota"},
        ],
        transactions: [
            {"date":"2026-08-02T07:00Z","description":"Signed CB Jarod Washington. Waived RB Kejon Owens."},
            {"date":"2026-07-28T07:00Z","description":"Signed S Jamal Adams and RB Jordan Mims to contracts. Signed T Brian O'Neill to a four-year contract extension through the 2030 season."},
            {"date":"2026-07-27T07:00Z","description":"Waived LB Keli Lawson and WR Luke Wysong. Placed RB Kejon Owens on the NFI list."},
            {"date":"2026-06-16T07:00Z","description":"Waived T Caleb Etienne and DL Minkell Doodwine. Signed TE Marshall Lang and DL Jahvaree Ritzie to contracts."},
            {"date":"2026-06-04T07:00Z","description":"Waived WR Joaquin Davis. Signed WRs Trayvon Rudolph and Michael Briscoe to contracts."},
        ],
    },
    "NE": {
        news: [
            {"id":"49427703","headline":"2026 New England Patriots training camp: Latest intel, updates","summary":"Follow our daily updates from Patriots training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T22:03:31Z","url":"https://www.espn.com/nfl/story/_/id/49427703/new-england-patriots-training-camp-2026-intel-updates"},
            {"id":"49508691","headline":"Too many receivers? A look at the Patriots' crowded WR room","summary":"Which of the seven receivers are getting the most work in camp? And what New England could do about it.","date":"2026-08-02T14:39:51Z","url":"https://www.espn.com/nfl/story/_/id/49508691/new-england-patriots-receivers-kayshon-boutte-pop-douglas-aj-brown-romeo-doubs"},
        ],
        transactions: [
            {"date":"2026-08-03T07:00Z","description":"Signed DT Casey Rogers to a contract. Activated RB Terrell Jennings from the NFI list."},
            {"date":"2026-08-01T07:00Z","description":"Activated LB Gabe Jacas from the non-football injury list."},
            {"date":"2026-07-31T07:00Z","description":"Released LB Otis Reese."},
            {"date":"2026-07-26T07:00Z","description":"Signed LB Gabe Jacas to a rookie contract and placed him on the non-football injury list. Placed WR Jeremiah Webb on injured reserve."},
            {"date":"2026-07-25T07:00Z","description":"Placed WR Jimmy Kibble on injured reserve. Waived OT Sebastian Gutierrez. Claimed WR Kobe Prentice off waivers from Carolina."},
        ],
    },
    "NO": {
        news: [
            {"id":"49424731","headline":"2026 New Orleans Saints training camp: Latest intel, updates","summary":"Follow our daily updates from Saints training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T22:13:32Z","url":"https://www.espn.com/nfl/story/_/id/49424731/new-orleans-saints-training-camp-2026-intel-updates"},
            {"id":"49515016","headline":"Saints place WR Ja'Lynn Polk, 24, on reserve/retired list","summary":"Saints wide receiver Ja'Lynn Polk has been placed on the reserve/retired list, the team announced Sunday.","date":"2026-08-02T21:17:03Z","url":"https://www.espn.com/nfl/story/_/id/49515016/saints-place-wr-jalynn-polk-24-reserve-retired-list"},
            {"id":"49513248","headline":"Saints starting DT Bryan Bresee to have season-ending ACL surgery","summary":"Saints defensive tackle Bryan Bresee will undergo season-ending surgery to repair a torn ACL, coach Kellen Moore told reporters Sunday.","date":"2026-08-02T18:44:45Z","url":"https://www.espn.com/nfl/story/_/id/49513248/saints-starting-dt-bryan-bresee-season-ending-acl-surgery"},
            {"id":"49497392","headline":"Why Schefter has high hopes for the Saints this season","summary":"Why Schefter has high hopes for the Saints this season","date":"2026-07-31T16:39:01Z","url":"https://www.espn.com/video/clip/_/id/49497392/why-schefter-high-hopes-saints-season"},
        ],
        transactions: [
            {"date":"2026-08-02T07:00Z","description":"Placed WR Ja'Lynn Polk on the reserve/retired list."},
            {"date":"2026-07-31T07:00Z","description":"Activated TE Cody Hardy from the non-football illness list."},
            {"date":"2026-07-28T07:00Z","description":"Signed DB Mike Reid. Waived DB Beanie Bishop. Placed DTs Keeshawn Silver and WR Mason Tipton on the PUP list. Placed DT Zxavian Harris, and TE Cody Hardy active/non-football injury."},
            {"date":"2026-07-22T07:00Z","description":"Waived WR Damien Alford, DT Coziah Izzard, DB DaShawn Jones and K Mason Shipley. Signed K Tanner Brown, QB Hunter Dekkers, LB Cameron Jordan and WR Jalen Moreno-Cropper to contracts."},
            {"date":"2026-06-22T07:00Z","description":"Waived WR Damien Alford from injured reserve."},
        ],
    },
    "NYG": {
        news: [
            {"id":"49520884","headline":"Stephen A.: No way the Giants are making the NFL playoffs","summary":"Stephen A.: No way the Giants are making the NFL playoffs","date":"2026-08-03T15:33:45Z","url":"https://www.espn.com/video/clip/_/id/49520884/no-way-giants-making-nfl-playoffs"},
            {"id":"49434181","headline":"2026 New York Giants training camp: Latest intel, updates","summary":"Follow our daily updates from Giants training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-02T00:01:41Z","url":"https://www.espn.com/nfl/story/_/id/49434181/new-york-giants-training-camp-2026-intel-updates"},
        ],
        transactions: [
            {"date":"2026-07-30T07:00Z","description":"Signed LB Anfernee Orji to a contract. Waived DL Ben Barten."},
            {"date":"2026-07-28T07:00Z","description":"Activated TE Thomas Fidone II and DT Sam Roberts from the active/PUP list. Signed DT Marlon Davidson and TE Tyler Moore."},
            {"date":"2026-07-25T07:00Z","description":"Waived LB Cam Jones and DE C.J. Ravenell."},
            {"date":"2026-07-23T07:00Z","description":"Placed TE Thomas Fidone II and DL Sam Roberts and Roy Robertson-Harris on the PUP list."},
            {"date":"2026-07-08T07:00Z","description":"Placed CB Rico Payton on injured reserve."},
        ],
    },
    "NYJ": {
        news: [
            {"id":"49524111","headline":"How does the Jets' starting defense look?","summary":"Richard Cimini reports that Minkah Fitzpatrick picks off Geno Smith at Jets training camp.","date":"2026-08-03T21:36:29Z","url":"https://www.espn.com/video/clip/_/id/49524111/how-does-jets-starting-defense-look"},
            {"id":"49419756","headline":"2026 New York Jets training camp: Latest intel, updates","summary":"Follow our daily updates from Jets training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T17:49:20Z","url":"https://www.espn.com/nfl/story/_/id/49419756/new-york-jets-training-camp-2026-intel-updates"},
            {"id":"49489372","headline":"Jets' Glenn takes more humble approach heading into Year 2","summary":"New York's coach is heading into his second season with a different approach and set of expectations.","date":"2026-08-02T10:00:03Z","url":"https://www.espn.com/nfl/story/_/id/49489372/new-york-jets-aaron-glenn-improvement-year-2"},
            {"id":"49506513","headline":"Geno Smith shows out in practice for Jets","summary":"Rich Cimini details Geno Smith's stellar day at training camp.","date":"2026-08-01T19:09:34Z","url":"https://www.espn.com/video/clip/_/id/49506513/geno-smith-shows-practice-jets"},
        ],
        transactions: [
            {"date":"2026-08-01T07:00Z","description":"Signed DL Ben Barten. Waived S Garrison Grimes. Reverted WR Gee Scott Jr. to injured reserve after clearing waivers."},
            {"date":"2026-07-31T07:00Z","description":"Reverted WR Jalen Walthall to injured reserve after clearing waivers. Signed WR Cam Camper. Waived WR Gee Scott Jr.."},
            {"date":"2026-07-30T07:00Z","description":"Signed WR Quincy Skinner Jr. to a contract. Waived WR Jalen Walthall."},
            {"date":"2026-07-28T07:00Z","description":"Activated WR Tim Patrick from the active/PUP list. Placed LB Joseph Ossai on the active/PUP list."},
            {"date":"2026-07-13T07:00Z","description":"Waived WR Quentin Skinner from injured reserve."},
        ],
    },
    "PHI": {
        news: [
            {"id":"49434399","headline":"2026 Philadelphia Eagles training camp: Latest intel, updates","summary":"Follow our daily updates from Eagles training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T18:18:52Z","url":"https://www.espn.com/nfl/story/_/id/49434399/philadelphia-eagles-training-camp-2026-intel-updates"},
            {"id":"49506580","headline":"Eagles' first team meeting had one clear message","summary":"Sal Paolantonio breaks down Nick Sirianni's message to the Eagles after their first team meeting.","date":"2026-08-01T19:20:08Z","url":"https://www.espn.com/video/clip/_/id/49506580/eagles-first-team-meeting-had-one-clear-message"},
            {"id":"49479717","headline":"Eagles OLB Jonathan Greenard lands on PUP with pec strain","summary":"The Eagles' Jonathan Greenard will be placed on PUP after suffering a pec strain while lifting before camp. It is not expected to be a long-term issue.","date":"2026-07-29T14:15:42Z","url":"https://www.espn.com/nfl/story/_/id/49479717/eagles-olb-jonathan-greenard-lands-pup-pec-strain"},
            {"id":"49479708","headline":"What Jonathan Greenard's injury means for the Eagles","summary":"What Jonathan Greenard's injury means for the Eagles","date":"2026-07-29T13:50:28Z","url":"https://www.espn.com/video/clip/_/id/49479708/what-jonathan-greenard-injury-means-eagles"},
        ],
        transactions: [
            {"date":"2026-08-02T07:00Z","description":"Waived DE Ta'Quon Graham."},
            {"date":"2026-06-23T07:00Z","description":"Signed OT Markel Bell to a rookie contract."},
            {"date":"2026-06-16T07:00Z","description":"Placed DE Joe Tryon-Shoyinka on the reserve/retired list. Signed WR Erik Ezukanma and DB Shaun Wade to contracts. Waived DB Brandon Johnson."},
            {"date":"2026-06-10T07:00Z","description":"Signed DE A.J. Epenesa and G Michael Jordan to a contract. Waived LBs Isiah King and Chandler Martin. Released OLB Za'Darius Smith from the reserve/retired list."},
            {"date":"2026-06-05T07:00Z","description":"Signed DT Zion Wilson to a contract. Waived WR Brandon Hayes."},
        ],
    },
    "PIT": {
        news: [
            {"id":"49525126","headline":"How 'tempered' came to be the Steelers' training camp motto","summary":"Brooke Pryor chats with Steelers coach Mike McCarthy about his newest catchphrase to motivate the team.","date":"2026-08-04T00:29:03Z","url":"https://www.espn.com/video/clip/_/id/49525126/how-tempered-came-steelers-training-camp-motto"},
            {"id":"49449169","headline":"2026 Pittsburgh Steelers training camp: Latest intel, updates","summary":"Follow our daily updates from Steelers training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T21:00:18Z","url":"https://www.espn.com/nfl/story/_/id/49449169/pittsburgh-steelers-training-camp-2026-intel-updates"},
        ],
        transactions: [
            {"date":"2026-08-02T07:00Z","description":"Signed S Rayshawn Jenkins. Released S Darnell Savage."},
            {"date":"2026-08-01T07:00Z","description":"Signed S Rayshawn Jenkins."},
            {"date":"2026-07-28T07:00Z","description":"Placed DBs Donte Kent, Joey Porter Jr. and Jalen Ramsey on the active/PUP list."},
            {"date":"2026-07-24T07:00Z","description":"Signed QB Drew llar to a rookie contract."},
            {"date":"2026-07-22T07:00Z","description":"Signed LB Jacoby Windmon to a contract"},
        ],
    },
    "SEA": {
        news: [
            {"id":"49499878","headline":"What to expect from Seahawks on 'Hard Knocks' debut","summary":"From shadowboxing to Leonard Williams' hobbies to Devon Witherspoon's contract, here's what you might see.","date":"2026-08-02T10:00:12Z","url":"https://www.espn.com/nfl/story/_/id/49499878/seattle-seahawks-hard-knocks-hbo-debut-tuesday-preview"},
            {"id":"49427699","headline":"2026 Seattle Seahawks training camp: Latest intel, updates","summary":"Follow our daily updates from Seahawks training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-02T02:59:11Z","url":"https://www.espn.com/nfl/story/_/id/49427699/seattle-seahawks-training-camp-2026-intel-updates"},
            {"id":"49355501","headline":"Betting on the Seattle Seahawks in 2026: Champs among Super Bowl favorites","summary":"Examining the Seahawks' outlook for 2026, the ways to bet them and our best bet going into the NFL season.","date":"2026-07-30T10:42:26Z","url":"https://www.espn.com/espn/betting/story/_/id/49355501/seattle-seahawks-betting-outlook-2026"},
        ],
        transactions: [
            {"date":"2026-08-02T07:00Z","description":"Reverted LB Ja'Markis Weston to injured reserve after he cleared waivers."},
            {"date":"2026-08-01T07:00Z","description":"Signed LB Joseph Vaughn. Waived LB Ja'Markis Weston."},
            {"date":"2026-07-30T07:00Z","description":"Activated DT Deven Eastern from the NFI list. Signed WR Kyre Duplessis to a contract."},
            {"date":"2026-07-28T07:00Z","description":"Waived RB Kenny McIntosh."},
            {"date":"2026-07-25T07:00Z","description":"Waived WR Tyrone Broden."},
        ],
    },
    "SF": {
        news: [
            {"id":"49519976","headline":"What does 49ers' 'ominous' start mean for the season?","summary":"What does 49ers' 'ominous' start mean for the season?","date":"2026-08-03T13:49:57Z","url":"https://www.espn.com/video/clip/_/id/49519976/what-does-49ers-ominous-start-mean-season"},
            {"id":"49516913","headline":"What's next for 49ers receivers Aiyuk, Deebo and Pearsall?","summary":"When will Aiyuk be released? And will he sign with Washington? What is Samuel's role after returning to S.F.?","date":"2026-08-03T18:21:26Z","url":"https://www.espn.com/nfl/story/_/id/49516913/san-francisco-49ers-brandon-aiyuk-commanders-deebo-samuel-ricky-pearsall-fantasy"},
            {"id":"49427696","headline":"2026 San Francisco 49ers training camp: Latest intel, updates","summary":"Follow our daily updates from 49ers training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-01T23:13:50Z","url":"https://www.espn.com/nfl/story/_/id/49427696/san-francisco-49ers-training-camp-2026-intel-updates"},
            {"id":"49507290","headline":"Deebo Samuel on reunion with 49ers: 'Just matter of time'","summary":"Deebo Samuel, who left the Niners last offseason after requesting a trade, said he feels right at home back in San Francisco.","date":"2026-08-02T20:58:37Z","url":"https://www.espn.com/nfl/story/_/id/49507290/deebo-samuel-reunion-49ers-just-matter"},
        ],
        transactions: [
            {"date":"2026-08-03T07:00Z","description":"Reverted DE Mikail Kamara to injured reserve after he cleared waivers."},
            {"date":"2026-08-02T07:00Z","description":"Signed RB Khalil Herbert and DE Titus Leo. Released DB Eli Apple. Waived DE Mikail Kamara."},
            {"date":"2026-08-01T07:00Z","description":"Placed WR Ricky Pearsall on season-ending injured reserve. Signed WR Deebo Samuel. Reverted TE Tanner McLachlan to injured reserve after clearing waivers."},
            {"date":"2026-07-31T07:00Z","description":"Signed TE Josiah Deguara and WR Tenton Irwin to a one-year contracts. Waived DB Derrick Canteen and TE Tanner McLachlan. Activated DL Alfred Collins from the PUP list."},
            {"date":"2026-07-30T07:00Z","description":"Reverted DE William Bradley-King and LB Andrew Farmer to injured reserve after they cleared waivers."},
        ],
    },
    "TB": {
        news: [
            {"id":"49419613","headline":"2026 Tampa Bay Buccaneers training camp: Latest intel, updates","summary":"Follow our daily updates from Buccaneers training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T23:34:16Z","url":"https://www.espn.com/nfl/story/_/id/49419613/tampa-bay-buccaneers-training-camp-2026-intel-updates"},
            {"id":"49489537","headline":"Mayfield felt 'disrespected' and 'undervalued' by Buccaneers' offers","summary":"Buccaneers quarterback Baker Mayfield said Thursday that he felt \"disrespected a little bit\" that he and the team could not reach an agreement on a new contract before his imposed…","date":"2026-08-01T00:11:18Z","url":"https://www.espn.com/nfl/story/_/id/49489537/mayfield-felt-disrespected-undervalued-buccaneers-offers"},
        ],
        transactions: [
            {"date":"2026-07-31T07:00Z","description":"Reverted DT Haggai Chisom Ndubuisi to the PUP list."},
            {"date":"2026-07-30T07:00Z","description":"Signed CB Ifeatu Melifonwu and DT Travis Shaw to contracts. Waived DT Haggai Chisom Ndubuisi."},
            {"date":"2026-07-29T07:00Z","description":"Signed DT Travis Shaw. Waived DT Haggai Chisom Ndubuisi."},
            {"date":"2026-07-28T07:00Z","description":"Waived DB Ja'Qurious Conley. Placed DB Chase Lucas and DT Haggai Chisom Ndubuisi on the active/PUP list."},
            {"date":"2026-06-08T07:00Z","description":"Signed K B.T. Potter to a contract. Waived P Aidan Laros."},
        ],
    },
    "TEN": {
        news: [
            {"id":"49523777","headline":"Which Titans WR has stood out in camp?","summary":"Turron Davenport reports on how wide receiver Elic Ayomanor has impressed so far at Titans' camp.","date":"2026-08-03T21:18:14Z","url":"https://www.espn.com/video/clip/_/id/49523777/which-titans-wr-stood-camp"},
            {"id":"49419824","headline":"2026 Tennessee Titans training camp: Latest intel, updates","summary":"Follow our daily updates from Titans training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T20:22:18Z","url":"https://www.espn.com/nfl/story/_/id/49419824/tennessee-titans-training-camp-2026-intel-updates"},
            {"id":"49506954","headline":"Confident Will Levis OK competing for Titans' backup QB spot","summary":"Titans quarterback Will Levis, entering his fourth season, still believes he is \"a dang good quarterback\" in the NFL as he continues to battle for the team's backup position behind…","date":"2026-08-02T13:52:41Z","url":"https://www.espn.com/nfl/story/_/id/49506954/confident-levis-ok-competing-titans-backup-qb-spot"},
            {"id":"49488512","headline":"Titans WRs join Cam Ward in Miami to build chemistry","summary":"After ranking last in passing plays of 40 yards or more, Tennessee's pass catchers worked together this offseason.","date":"2026-07-30T16:07:01Z","url":"https://www.espn.com/nfl/story/_/id/49488512/tennessee-titans-cam-ward-build-chemistry-wrs-miami"},
        ],
        transactions: [
            {"date":"2026-08-02T07:00Z","description":"Signed DB Derrick Canteen, DT Khalen Saunders and NT Laki Tasi. Waived DE David Ebuka Agoha, DB Hudson Clark and DT Cam Horsley."},
            {"date":"2026-08-01T07:00Z","description":"Signed CB Mario Goodrich. Waived CB Jeadyn Lukus."},
            {"date":"2026-07-31T07:00Z","description":"Reverted DB Sanoussi Kane to the injured reserve list after clearing waivers."},
            {"date":"2026-07-30T07:00Z","description":"Signed S Hudson Clark to a contract. Waived/injured S Sanoussi Kane. Activated OT JC Latham from the PUP list."},
            {"date":"2026-07-28T07:00Z","description":"Activated DB Amani Hooker from the active/PUP list."},
        ],
    },
    "WAS": {
        news: [
            {"id":"49523402","headline":"Commanders' receivers compete amid Stefon Diggs rumors","summary":"John Keim breaks down the Commanders' wide receiver group during training camp.","date":"2026-08-03T22:54:04Z","url":"https://www.espn.com/video/clip/_/id/49523402/commanders-receivers-compete-amid-stefon-diggs-rumors"},
            {"id":"49448046","headline":"2026 Washington Commanders training camp: Latest intel, updates","summary":"Follow our daily updates from Commanders training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-03T17:26:40Z","url":"https://www.espn.com/nfl/story/_/id/49448046/washington-commanders-training-camp-2026-intel-updates"},
        ],
        transactions: [
            {"date":"2026-08-03T07:00Z","description":"Reinstated LB Kain Medrano from the active/PUP list. Reverted DB Tre Hawkins III to injured reserve after he cleared waivers."},
            {"date":"2026-08-02T07:00Z","description":"Signed C Trey Hill. Released CB Tre Hawkins."},
            {"date":"2026-07-29T07:00Z","description":"Signed P Matt Haack and WR River Cracraft. Released OLB Andre Carter and TE Anthony Firkser. Reinstated CB Fred Davis from the active/non-football injury list. Placed P Tress Way on the active/non-football injury list. Placed LB Kain Medrano on the active/PUP list."},
            {"date":"2026-07-27T07:00Z","description":"Signed CB Rasul Douglas to a contract. Placed LB Nick Bellore on the retired list."},
            {"date":"2026-06-02T07:00Z","description":"Signed TE Anthony Firkser to a contract. Released WR Ja'Corey Brooks."},
        ],
    },
};

export const getOffseasonNews = (abbr) => offseasonNews[abbr] || { news: [], transactions: [] };
