// Auto-generated by scripts/updateOffseason.js — do not edit by hand.
// Source: ESPN public NFL news + transactions feeds, read 2026-08-22T00:17:30.734Z.
// Refresh with: npm run offseason
//
// Hand-curated coaching/moves/key points live in offseasonData.js.
// This file carries live headlines and roster transactions only.

export const OFFSEASON_NEWS_UPDATED_AT = "2026-08-22T00:17:30.734Z";

export const offseasonNews = {
    "ARI": {
        news: [
            {"id":"49683212","headline":"Massachusetts to investigate Cardinals exec's alleged betting","summary":"A second investigation has been opened related to former Arizona Cardinals scout Ryan Gold's alleged betting activity.","date":"2026-08-21T19:14:36Z","url":"https://www.espn.com/nfl/story/_/id/49683212/massachusetts-investigate-cardinals-exec-alleged-betting"},
            {"id":"49674964","headline":"MHJ is all smiles so far through Cardinals preseason","summary":"Harrison has played well in August and hopes his first 1,000-yard receiving season is right around the corner.","date":"2026-08-21T10:00:21Z","url":"https://www.espn.com/nfl/story/_/id/49674964/arizona-cardinals-marvin-harrison-jr-outlook"},
            {"id":"49634102","headline":"Sources: Cardinals RB Love likely to sit rest of preseason","summary":"Rookie running back Jeremiyah Love, who played 23 snaps Thursday against the Las Vegas Raiders, is dealing with a high ankle sprain and is unlikely to play the rest of the preseaso…","date":"2026-08-17T01:36:41Z","url":"https://www.espn.com/nfl/story/_/id/49634102/cardinals-rb-love-likely-sit-rest-preseason"},
            {"id":"49619508","headline":"Cardinals rookie RB Love to miss a week due to sore ankle","summary":"Cardinals rookie running back Jeremiyah Love will miss the next week to let a sore ankle he injured Thursday night against the Raiders heal, coach Mike LaFleur said.","date":"2026-08-15T20:28:36Z","url":"https://www.espn.com/nfl/story/_/id/49619508/cardinals-rookie-rb-love-miss-week-due-sore-ankle"},
        ],
        transactions: [
            {"date":"2026-08-20T07:00Z","description":"Activated CB Garrett Williams from the PUP list."},
            {"date":"2026-08-16T07:00Z","description":"Signed RB Tre Stewart."},
            {"date":"2026-08-15T07:00Z","description":"Signed TE Baylor Cupp, DL Keveion'ta Spears and RB Tre Stewart. Placed OL Chase Bisontis, TE Jameson Geers and LB Austin Keys on injured reserve."},
            {"date":"2026-08-12T07:00Z","description":"Waived DT PJ Mustipher."},
            {"date":"2026-08-11T07:00Z","description":"Released DT PJ Mustipher from injured reserve with a settlement."},
        ],
    },
    "ATL": {
        news: [
            {"id":"49673266","headline":"As season opener nears, Falcons still don't have a QB1","summary":"Michael Penix Jr. hasn't been cleared to fully practice, and Tua Tagovailoa has struggled. Not ideal for Atlanta.","date":"2026-08-21T10:03:25Z","url":"https://www.espn.com/nfl/story/_/id/49673266/tua-tagovailoa-michael-penix-jr-nfl-season-opener-nears-atlanta-falcons-dont-qb1"},
            {"id":"49648078","headline":"Falcons sign veteran Za'Darius Smith to aid pass rush","summary":"Za'Darius Smith has signed a one-year deal with the Falcons to help bolster their pass rush after losing Jalon Walker and James Pearce Jr. for an extended period.","date":"2026-08-18T13:46:19Z","url":"https://www.espn.com/nfl/story/_/id/49648078/falcons-sign-veteran-zadarius-smith-bolster-pass-rush"},
            {"id":"49614782","headline":"Tua Tagovailoa says Falcons' play 'not up to standard' in loss","summary":"Falcons quarterback Tua Tagovailoa said he was \"frustrated and disappointed\" after a preseason loss to the Broncos, during which he played two series and was 3-of-5 passing for 22…","date":"2026-08-17T15:36:11Z","url":"https://www.espn.com/nfl/story/_/id/49614782/falcons-qb-tua-tagovailoa-frustrated-disappointed-play-preseason-loss-broncos"},
        ],
        transactions: [
            {"date":"2026-08-21T07:00Z","description":"Signed DT Eric Johnson."},
            {"date":"2026-08-18T07:00Z","description":"Placed RB Trey Sermon on injured reserve."},
            {"date":"2026-08-17T07:00Z","description":"Signed WR Beaux Collins. Waived WR Le'Meke Brockington, P Matthew Hayball and G Layden Robinson. Released WR Kristian Wilkerson."},
            {"date":"2026-08-14T07:00Z","description":"Waived OT Jack Nelson with an injury settlement."},
            {"date":"2026-08-12T07:00Z","description":"Reverted DT Le'Meke Brockington and S Malik Verdon to injured reserve after they cleared waivers."},
        ],
    },
    "BAL": {
        news: [
            {"id":"49673480","headline":"Ravens center Pinter to miss 'extended time' with leg injury","summary":"Ravens starting center Danny Pinter is expected to miss \"an extended amount of time\" after injuring his right leg during joint practices with the Vikings, coach Jesse Minter said T…","date":"2026-08-20T20:29:59Z","url":"https://www.espn.com/nfl/story/_/id/49673480/ravens-center-pinter-miss-extended-leg-injury"},
        ],
        transactions: [
            {"date":"2026-08-18T07:00Z","description":"Reverted RB Jahquez Robinson to injured reserve after he cleared waivers."},
            {"date":"2026-08-16T07:00Z","description":"Signed RB Jonathan Ward."},
            {"date":"2026-08-14T07:00Z","description":"Placed OT Kendall Lamm on the reserve/retire list."},
            {"date":"2026-08-12T07:00Z","description":"Signed QB Austin Reed. Placed QB Skylar Thompson on injured reserve."},
            {"date":"2026-08-09T07:00Z","description":"Waived DB Matthew McDoom."},
        ],
    },
    "BUF": {
        news: [
            {"id":"49434544","headline":"2026 Buffalo Bills training camp: Latest intel, updates","summary":"Follow our updates from Bills training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-20T22:05:42Z","url":"https://www.espn.com/nfl/story/_/id/49434544/buffalo-bills-training-camp-2026-intel-updates"},
            {"id":"49643423","headline":"New grass field held up well in opener, Bills president says","summary":"When the Bills opened Highmark Stadium last week, the field showed signs of wear in a preseason win over the Panthers, but president Pete Guelli told The Associated Press on Monday…","date":"2026-08-18T00:10:25Z","url":"https://www.espn.com/nfl/story/_/id/49643423/new-grass-field-held-well-opener-bills-president-says"},
            {"id":"49621171","headline":"Josh Allen gets comfortable in Bills' new stadium with TD pass in 29-14 preseason win over Panthers","summary":"— New head coach. New Buffalo Bills stadium.","date":"2026-08-15T22:28:28Z","url":"http://www.espn.com/nfl/recap?gameId=401873282"},
            {"id":"49611988","headline":"Bills' Phidarian Mathis banned 3 games for substance abuse violation","summary":"Bills defensive tackle Phidarian Mathis has been suspended for the first three games of the season for violating the NFL's substance abuse policy.","date":"2026-08-15T00:27:33Z","url":"https://www.espn.com/nfl/story/_/id/49611988/bills-phidarian-mathis-banned-3-games-substance-abuse-violation"},
        ],
        transactions: [
            {"date":"2026-08-20T07:00Z","description":"Waived DT Tommy Akingbesote."},
            {"date":"2026-08-18T07:00Z","description":"Signed DT Greg Gaines. Waived DT Tommy Akingbesote."},
            {"date":"2026-08-17T07:00Z","description":"Signed LB Otis Reese. Released FB Jackson Acker."},
            {"date":"2026-08-14T07:00Z","description":"Signed DB Wande Owens. Waived LB Otis Reese."},
            {"date":"2026-08-12T07:00Z","description":"Signed DB Anthony Kendall. Waived DT Kody Huisman."},
        ],
    },
    "CAR": {
        news: [
            {"id":"49661957","headline":"Bryce Young, Tetairoa McMillan shine in Panthers joint practice vs. Jags","summary":"Mike Kaye breaks down how the Panthers did in joint practices vs. the Jaguars.","date":"2026-08-19T19:08:17Z","url":"https://www.espn.com/video/clip/_/id/49661957/bryce-young-tetairoa-mcmillan-shine-panthers-joint-practice-vs-jags"},
            {"id":"49377273","headline":"2026 Carolina Panthers training camp: Latest intel, updates","summary":"Catch up on our updates from Panthers training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-20T04:00:47Z","url":"https://www.espn.com/nfl/story/_/id/49377273/carolina-panthers-training-camp-2026-intel-updates"},
            {"id":"49643331","headline":"Devin Lloyd wears green dot as badge of honor for Panthers' defense","summary":"The ability to speak efficiently in the huddle is vital, and the fifth-year linebacker has impressed so far.","date":"2026-08-19T13:32:43Z","url":"https://www.espn.com/nfl/story/_/id/49643331/devin-lloyd-carolina-panthers-defense-2026-wears-green-dot-helmet-badge-honor"},
            {"id":"49621729","headline":"New defensive additions shine for Panthers in preseason debut","summary":"Mike Kaye breaks down impressive debuts for Devin Lloyd and Jaelan Phillips with the Panthers.","date":"2026-08-19T13:39:27Z","url":"https://www.espn.com/video/clip/_/id/49621729/new-defensive-additions-shine-panthers-preseason-debut"},
        ],
        transactions: [
            {"date":"2026-08-18T07:00Z","description":"Waived G Joshua Gray and LB Nick Hampton."},
            {"date":"2026-08-17T07:00Z","description":"Signed TE Darren Waller. Waived G Joshua Gray and LB Nick Hampton."},
            {"date":"2026-08-12T07:00Z","description":"Released WR Malick Meiga from injured reserve with a settlement."},
            {"date":"2026-08-10T07:00Z","description":"Signed G Joshua Gray. Waived TE Chamon Metayer. Reverted LB Nick Hampton and WR Malick Meiga to injured reserve after they cleared waivers."},
            {"date":"2026-08-09T07:00Z","description":"Signed QB Kyle Trask and LB Jeremiah Moon. Waived/injured LBs Nick Hampton and Malick Meiga."},
        ],
    },
    "CHI": {
        news: [
            {"id":"49652191","headline":"Why Ben Johnson's Bears offense works and 2026 expectations","summary":"While Chicago's success will always be tied to its quarterback, a deeper look unveils the beauty of Johnson's offensive system and what really makes it go.","date":"2026-08-19T13:14:01Z","url":"https://www.espn.com/nfl/story/_/id/49652191/chicago-bears-coach-ben-johnson-offense-caleb-williams"},
            {"id":"49643703","headline":"Johnson: Bears RB Kyle Monangai week-to-week after knee injury","summary":"Chicago Bears running back Kyle Monangai will be week-to-week after sustaining a knee injury during practice on Sunday, coach Ben Johnson confirmed on Tuesday.","date":"2026-08-18T17:15:34Z","url":"https://www.espn.com/nfl/story/_/id/49643703/bears-rb-kyle-monangai-knee-expected-miss-multiple-weeks-source-says"},
            {"id":"49448378","headline":"2026 Chicago Bears training camp: Latest intel, updates","summary":"Catch up on our daily updates from Bears training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-16T21:24:49Z","url":"https://www.espn.com/nfl/story/_/id/49448378/chicago-bears-training-camp-2026-intel-updates"},
            {"id":"49631637","headline":"LT Ozzy Trapilo (knee) now eligible to practice with Bears","summary":"The Bears activated Ozzy Trapilo off the physically unable to perform list on Sunday, seven months after the left tackle ruptured his patellar tendon in the postseason.","date":"2026-08-16T20:57:23Z","url":"https://www.espn.com/nfl/story/_/id/49631637/lt-ozzy-trapilo-knee-now-eligible-practice-bears"},
        ],
        transactions: [
            {"date":"2026-08-18T07:00Z","description":"Waived RB Coleman Bennett. Reverted TE Nikola Kalinic to injured reserve after he cleared waivers."},
            {"date":"2026-08-17T07:00Z","description":"Signed DE Marcus Davenport and DB Deantre Prince. Waived RB Coleman Bennett. Waived/injured TE Nikola Kalinic."},
            {"date":"2026-08-16T07:00Z","description":"Reinstated LT Ozzy Trapilo. Waived DBs K.C. Eziomume, Gervarrius Owens and WR Kyron Hudson with injury settlements."},
            {"date":"2026-08-12T07:00Z","description":"Waived S Brandon Hill."},
            {"date":"2026-08-11T07:00Z","description":"Signed OL Wesley French to a contract. Waived DB Brandon Hill."},
        ],
    },
    "CIN": {
        news: [
            {"id":"49680496","headline":"Jordan Rodgers: Joe Burrow is not the problem at the Bengals","summary":"Jordan Rodgers: Joe Burrow is not the problem at the Bengals","date":"2026-08-21T12:53:19Z","url":"https://www.espn.com/video/clip/_/id/49680496/joe-burrow-not-problem-bengals"},
            {"id":"49673743","headline":"'This is it': Bengals' Joe Burrow tired of waiting, targets Super Bowl","summary":"The Bengals improved their defense after missing the playoffs a third straight year. Will it be enough?","date":"2026-08-20T21:52:32Z","url":"https://www.espn.com/nfl/story/_/id/49673743/this-bengals-joe-burrow-tired-waiting-targets-super-bowl"},
            {"id":"49642143","headline":"DB Wright leaves Bengals preseason to pursue acting","summary":"Rookie Ceyair Wright -- who starred alongside LeBron James in 'Space Jam: A New Legacy' -- is giving new meaning to dual threat.","date":"2026-08-17T22:59:13Z","url":"https://www.espn.com/nfl/story/_/id/49642143/ceyair-wright-cincinnati-bengals-space-jam-2-actor-opportunity"},
            {"id":"49639534","headline":"Orlovsky: 'Everything's on the line' for the Bengals this season","summary":"Orlovsky: 'Everything's on the line' for the Bengals this season","date":"2026-08-17T16:29:03Z","url":"https://www.espn.com/video/clip/_/id/49639534/everything-line-bengals-season"},
        ],
        transactions: [
            {"date":"2026-08-15T07:00Z","description":"Signed CB Matthew McDoom. Placed CB Ceyair Wright on the exempt/left list. Reinstated DT B.J. Hill from the physically unable to perform list."},
            {"date":"2026-08-06T07:00Z","description":"Activated TE Josh Kattus from the NFI list."},
            {"date":"2026-08-04T07:00Z","description":"Waived S Isaiah Nwokobia."},
            {"date":"2026-07-25T07:00Z","description":"Placed DT B.J. Hill on the pup list. Placed TE Josh Jattus on the non-football injury list."},
            {"date":"2026-06-09T07:00Z","description":"Signed DE Cashius Howell to a rookie contract."},
        ],
    },
    "CLE": {
        news: [
            {"id":"49449000","headline":"2026 Cleveland Browns training camp: Latest intel, updates","summary":"Follow our updates from Browns training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-20T22:25:06Z","url":"https://www.espn.com/nfl/story/_/id/49449000/cleveland-browns-training-camp-2026-intel-updates"},
            {"id":"49670914","headline":"Jordan Rodgers adamant Shedeur Sanders should be starting in preseason for Browns","summary":"Jordan Rodgers adamant Shedeur Sanders should be starting in preseason for Browns","date":"2026-08-20T15:34:50Z","url":"https://www.espn.com/video/clip/_/id/49670914/jordan-rodgers-adamant-shedeur-sanders-starting-preseason-browns"},
            {"id":"49660991","headline":"Shedeur Sanders not feeling pressure about Browns' QB decision","summary":"With a decision at starting quarterback looming, Browns quarterback Shedeur Sanders said Wednesday he's not feeling pressure ahead of joint practice with the Bills on Thursday and…","date":"2026-08-20T10:44:08Z","url":"https://www.espn.com/nfl/story/_/id/49660991/shedeur-sanders-not-worried-browns-qb-decision"},
            {"id":"49648092","headline":"What is the state of the Browns' QB competition?","summary":"What is the state of the Browns' QB competition?","date":"2026-08-18T13:58:09Z","url":"https://www.espn.com/video/clip/_/id/49648092/what-state-browns-qb-competition"},
        ],
        transactions: [
            {"date":"2026-08-20T07:00Z","description":"Signed TE Drew Biber. Placed TE Jack Stoll on injured reserve. Waived DB Jeadyn Lukus."},
            {"date":"2026-08-18T07:00Z","description":"Signed DE Jamil Muhammad. Waived CB Jeadyn Lukus."},
            {"date":"2026-08-17T07:00Z","description":"Signed TE Jermaine Terry. Waived TE Brenden Bates."},
            {"date":"2026-08-14T07:00Z","description":"Placed DB Tyron Herring on injured reserve."},
            {"date":"2026-08-13T07:00Z","description":"Signed CB Jeremiah McClendon. Waived CB Tyron Herring with an injury designation."},
        ],
    },
    "DAL": {
        news: [
            {"id":"49684724","headline":"What to watch for: Cowboys preseason Game 2","summary":"Todd Archer details what to watch for in the Cowboys' second preseason game vs. the Cardinals.","date":"2026-08-21T21:58:00Z","url":"https://www.espn.com/video/clip/_/id/49684724/cowboys-preseason-game-2"},
            {"id":"49675309","headline":"Cowboys expecting a massive season from George Pickens","summary":"Todd Archer reports on the Cowboys' expectations for WR George Pickens.","date":"2026-08-21T00:17:29Z","url":"https://www.espn.com/video/clip/_/id/49675309/cowboys-expecting-massive-season-george-pickens"},
            {"id":"49376535","headline":"2026 Dallas Cowboys training camp: Latest intel, updates","summary":"Catch up on our daily updates from Cowboys training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-20T23:13:28Z","url":"https://www.espn.com/nfl/story/_/id/49376535/dallas-cowboys-training-camp-2026-intel-updates"},
            {"id":"49673882","headline":"Cowboys, Saints fined $500K each for brawls in joint practice","summary":"The NFL has fined the Cowboys and Saints $500,000 each after multiple fights broke out between the two teams during Tuesday's joint practice.","date":"2026-08-20T22:02:07Z","url":"https://www.espn.com/nfl/story/_/id/49673882/cowboys-saints-fined-500k-brawls-joint-practices"},
        ],
        transactions: [
            {"date":"2026-08-18T07:00Z","description":"Signed OLB Von Miller. Waived WR Traeshon Holden."},
            {"date":"2026-08-17T07:00Z","description":"Waived WR Traeshon Holden."},
            {"date":"2026-08-09T07:00Z","description":"Waived RB Dominic Richardson and DE Charles Snowden."},
            {"date":"2026-08-08T07:00Z","description":"Signed RB Jashaun Corbin. Waived RB Dominic Richardson and DE Charles Snowden."},
            {"date":"2026-08-07T07:00Z","description":"Signed RB Jashaun Corbin to a contract. Waived RB Dominic Richardson."},
        ],
    },
    "DEN": {
        news: [
            {"id":"49379469","headline":"2026 Denver Broncos training camp: Latest intel, updates","summary":"Catch up on our daily updates from Broncos training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-19T20:54:43Z","url":"https://www.espn.com/nfl/story/_/id/49379469/denver-broncos-training-camp-2026-intel-updates"},
            {"id":"49643341","headline":"Who will fill the Broncos' DT spot next to Zach Allen?","summary":"Allen and John Franklin-Myers collapsed pockets up the middle last season, but Denver now has to replace JFM. Can Allen keep up his elite play without him?","date":"2026-08-19T17:35:15Z","url":"https://www.espn.com/nfl/story/_/id/49643341/broncos-need-defensive-tackle-start-next-all-pro-zach-allen-2026-season"},
        ],
        transactions: [
            {"date":"2026-08-20T07:00Z","description":"Waived/injured LB Levelle Bailey. Signed DB Taylor Rapp."},
            {"date":"2026-08-13T07:00Z","description":"Signed OL Lecitus Smith."},
            {"date":"2026-08-10T07:00Z","description":"Reinstated LB Jordan Turner from the active/non-football injury list."},
            {"date":"2026-08-08T07:00Z","description":"Placed DE Matt Henningsen on injured reserve. Released DB Sam Webb. Signed WRs Kyre Duplessis and Kyrese Rowan. Signed DB Ricardo Hallman."},
            {"date":"2026-08-02T07:00Z","description":"Waived DB Blake Cotton."},
        ],
    },
    "DET": {
        news: [
            {"id":"49673062","headline":"Rapoport tells McAfee about the 'renewed focus' he has noticed with the Lions","summary":"Rapoport tells McAfee about the 'renewed focus' he has noticed with the Lions","date":"2026-08-20T19:44:13Z","url":"https://www.espn.com/video/clip/_/id/49673062/rapoport-tells-mcafee-renewed-focus-noticed-lions"},
            {"id":"49672143","headline":"Sam LaPorta's status uncertain for Lions' season opener","summary":"Sam LaPorta's status for the Lions' regular-season opener is unclear after the star tight end suffered a hip injury.","date":"2026-08-20T19:19:55Z","url":"https://www.espn.com/nfl/story/_/id/49672143/sam-laporta-status-uncertain-lions-season-opener"},
            {"id":"49651690","headline":"Why Lions, NFL coaches believe Super Bowl chances are real","summary":"If you don't believe Campbell & Co. that the Lions will be contenders, ask Sean McVay, Matt LaFleur and others.","date":"2026-08-21T15:51:53Z","url":"https://www.espn.com/nfl/story/_/id/49651690/detroit-lions-super-bowl-window-opportunity-2026"},
            {"id":"49661850","headline":"Lions starters expected to play in preseason Week 2 vs. Commanders","summary":"Eric Woodyard reports the Lions are expected to give starters plenty of playing time in their next preseason game.","date":"2026-08-19T18:53:58Z","url":"https://www.espn.com/video/clip/_/id/49661850/lions-starters-expected-play-preseason-week-2-vs-commanders"},
        ],
        transactions: [
            {"date":"2026-08-20T07:00Z","description":"Waived DB Loren Strickland."},
            {"date":"2026-08-18T07:00Z","description":"Waived DB Loren Strickland with an injury settlement."},
            {"date":"2026-08-17T07:00Z","description":"Waived DT Aidan Keanaaina. Reverted RB Kye Robichaux and DB Loren Strickland to injured reserve after they cleared waivers."},
            {"date":"2026-08-16T07:00Z","description":"Signed RB Trayveon Williams and CB Ekow Boye-Doe. Waived RB Kye Robichaux and DB Loren Strickland."},
            {"date":"2026-08-12T07:00Z","description":"Waived TE Miles Kitselman."},
        ],
    },
    "GB": {
        news: [
            {"id":"49681049","headline":"Jordan Morgan gets his shot at the Packers' left tackle job -- finally","summary":"The 2024 first-round pick is ready to step in to protect quarterback Jordan Love for Green Bay.","date":"2026-08-21T15:30:12Z","url":"https://www.espn.com/nfl/story/_/id/49681049/jordan-morgan-gets-shot-packers-left-tackle-job-finally"},
            {"id":"49675141","headline":"Packers starters set to play again vs. Broncos","summary":"Rob Demovsky reports on Green Bay's starters being expected to play in Friday's preseason matchup against Denver.","date":"2026-08-20T23:50:53Z","url":"https://www.espn.com/video/clip/_/id/49675141/packers-starters-set-play-again-vs-broncos"},
            {"id":"49376941","headline":"2026 Green Bay Packers training camp: Latest intel, updates","summary":"Catch up on our daily updates from Packers training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-19T22:49:10Z","url":"https://www.espn.com/nfl/story/_/id/49376941/green-bay-packers-training-camp-2026-intel-updates"},
            {"id":"49653405","headline":"Brenton Cox Jr. filling pass-rushing void for Packers","summary":"Rob Demovsky details how Brenton Cox Jr. has stepped up as Micah Parsons recovers from his ACL injury.","date":"2026-08-19T01:33:24Z","url":"https://www.espn.com/video/clip/_/id/49653405/brenton-cox-jr-filling-pass-rushing-void-packers"},
        ],
        transactions: [
            {"date":"2026-08-15T07:00Z","description":"Released QB Kyron Drones."},
            {"date":"2026-08-14T07:00Z","description":"Waived TE RJ Maryland."},
            {"date":"2026-08-12T07:00Z","description":"Waived G Karsen Barnhart and TE Drew Biber. Released TE Luke Lachey from injured reserve with a settlement."},
            {"date":"2026-08-11T07:00Z","description":"Signed Ss Trey Dean III and Tra Fluellen. Released TE Drew Biber and G Karsen Barnhart."},
            {"date":"2026-08-10T07:00Z","description":"Claimed WR Chris Hilton Jr. off waivers from Washington. Reverted DBs Johnathan Baldwin and Marlon Jones to injured reserve after they cleared waivers."},
        ],
    },
    "HOU": {
        news: [
            {"id":"49677495","headline":"What was missing from Texans in Week 2 of preseason","summary":"DJ Bien-Aime recaps the Texans' second preseason game of 2026.","date":"2026-08-21T05:34:06Z","url":"https://www.espn.com/video/clip/_/id/49677495/what-was-missing-texans-week-2-preseason"},
            {"id":"49676628","headline":"Fernando Mendoza throws a pick-6, struggles in 1st half of Raiders' 22-20 preseason win over Texans","summary":"— Top pick Fernando Mendoza is finding out quickly that he has a lot of work to do as he begins his NFL career.","date":"2026-08-21T04:37:28Z","url":"http://www.espn.com/nfl/recap?gameId=401873286"},
            {"id":"49676595","headline":"Las Vegas Raiders vs. Houston Texans: Game Highlights","summary":"Las Vegas Raiders vs. Houston Texans: Game Highlights","date":"2026-08-21T03:19:02Z","url":"https://www.espn.com/video/clip/_/id/49676595/game-highlights"},
        ],
        transactions: [
            {"date":"2026-08-17T07:00Z","description":"Signed DB Bryce Hall."},
            {"date":"2026-08-16T07:00Z","description":"Signed TE Louis Hansen."},
            {"date":"2026-08-15T07:00Z","description":"Signed QB Brett Rypien. Placed QB Graham Mertz and RB Josh Pitsenberger on injured reserve."},
            {"date":"2026-08-14T07:00Z","description":"Waived K Chris Freeman."},
            {"date":"2026-08-12T07:00Z","description":"Waived WR Montrell Washington. Signed K Chris Freeman."},
        ],
    },
    "IND": {
        news: [
            {"id":"49675410","headline":"Colts shine in joint practice against Falcons","summary":"Stephen Holder breaks down the Colts' improvements in practice.","date":"2026-08-21T00:37:12Z","url":"https://www.espn.com/video/clip/_/id/49675410/colts-shine-joint-practice-falcons"},
            {"id":"49671931","headline":"Keenan Allen to McAfee: Signing with Colts an 'easy decision'","summary":"Keenan Allen to McAfee: Signing with Colts an 'easy decision'","date":"2026-08-20T17:06:01Z","url":"https://www.espn.com/video/clip/_/id/49671931/signing-colts-easy-decision"},
            {"id":"49665945","headline":"Colts excited for the addition of Keenan Allen","summary":"Stephen Holder breaks down the Colts' expectations for Keenan Allen.","date":"2026-08-20T03:02:47Z","url":"https://www.espn.com/video/clip/_/id/49665945/colts-excited-addition-keenan-allen"},
            {"id":"49664278","headline":"Colts TE Tyler Warren injures groin in practice","summary":"Colts star tight end Tyler Warren sustained a groin injury in Wednesday's joint practice and did not return.","date":"2026-08-20T02:45:00Z","url":"https://www.espn.com/nfl/story/_/id/49664278/colts-tight-end-tyler-warren-injures-groin-practice"},
        ],
        transactions: [
            {"date":"2026-08-21T07:00Z","description":"Signed TE JJ Galbreath. Waived CB Jai'Onte' McMillan."},
            {"date":"2026-08-20T07:00Z","description":"Waived RB Roydell Williams."},
            {"date":"2026-08-18T07:00Z","description":"Signed WR Keenan Allen. Waived RB Roydell Williams."},
            {"date":"2026-08-09T07:00Z","description":"Signed WR D.J. Montgomery. Waived WR Liam Clifford."},
            {"date":"2026-08-07T07:00Z","description":"Signed TE Pharaoh Brown to a contract."},
        ],
    },
    "JAX": {
        news: [
            {"id":"49671935","headline":"Jaguars OT Cole Van Lanen activated after Week 18 injury","summary":"The Jaguars have activated offensive tackle Cole Van Lanen from the PUP list as he makes his return from a knee injury that forced him to miss Jacksonville's playoff loss last seas…","date":"2026-08-20T16:59:20Z","url":"https://www.espn.com/nfl/story/_/id/49671935/jaguars-ot-cole-van-lanen-activated-week-18-injury"},
            {"id":"49662349","headline":"Breaking down the Jaguars' success in joint practice with Panthers","summary":"Michael DiRocco breaks down if the Jaguars' starters will play vs. the Panthers in preseason.","date":"2026-08-19T19:57:55Z","url":"https://www.espn.com/video/clip/_/id/49662349/breaking-jaguars-success-joint-practice-panthers"},
            {"id":"49427691","headline":"2026 Jacksonville Jaguars training camp: Latest intel, updates","summary":"Catch up on our daily updates from Jaguars training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-19T19:43:11Z","url":"https://www.espn.com/nfl/story/_/id/49427691/jacksonville-jaguars-training-camp-2026-intel-updates"},
            {"id":"49659019","headline":"Giants trade Daniel Faalele to Jaguars for 6th-round draft pick","summary":"The Giants have traded guard Daniel Faalele to the Jaguars for a sixth-round draft pick in 2027.","date":"2026-08-20T15:54:52Z","url":"https://www.espn.com/nfl/story/_/id/49659019/sources-giants-agree-trade-daniel-faalele-jaguars"},
        ],
        transactions: [
            {"date":"2026-08-21T07:00Z","description":"Signed OL Timothy McKay. Released DT Quinton Bohanna."},
            {"date":"2026-08-20T07:00Z","description":"Released DT Quinton Bohanna. Waived T Timothy McKay. Activated T Cole Van lanen from the PUP list."},
            {"date":"2026-08-18T07:00Z","description":"Acquired OL Daniel Faalele from the New York Giants in exchange for a 2027 sixth-round draft pick. Waived OL Timothy McKay."},
            {"date":"2026-08-17T07:00Z","description":"Signed LB Baylon Spector and T Timothy McKay. Waived TE Ethan Conner. Placed LB Parker Hughes on injured reserve."},
            {"date":"2026-08-12T07:00Z","description":"Waived CB Keni-H Lovely."},
        ],
    },
    "KC": {
        news: [
            {"id":"49447878","headline":"2026 Kansas City Chiefs training camp: Latest intel, updates","summary":"Catch up on our updates from Chiefs training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-20T18:25:25Z","url":"https://www.espn.com/nfl/story/_/id/49447878/kansas-city-chiefs-training-camp-2026-intel-updates"},
            {"id":"49651105","headline":"Chiefs' Bieniemy: Wife 'on a great road to recovery'","summary":"Chiefs' Bieniemy: Wife 'on a great road to recovery'","date":"2026-08-18T19:41:45Z","url":"https://www.espn.com/video/clip/_/id/49651105/wife-great-road-recovery"},
            {"id":"49650737","headline":"Chiefs' Bieniemy: Wife to make full recovery after being shot","summary":"Chiefs offensive coordinator Eric Bieniemy said Tuesday that his wife, Mia, is on track to make a full recovery after she was allegedly shot by the couple's son last month in the f…","date":"2026-08-18T19:43:52Z","url":"https://www.espn.com/nfl/story/_/id/49650737/chiefs-bieniemy-wife-make-full-recovery-being-shot"},
            {"id":"49622454","headline":"First-round pick Ty Simpson throws 2 TD passes, rallies Rams past Chiefs 20-12 in preseason debut","summary":"— There were a whole bunch of raised eyebrows when the Los Angeles Rams drafted Ty Simpson in the first round in April.","date":"2026-08-16T00:06:32Z","url":"http://www.espn.com/nfl/recap?gameId=401873283"},
        ],
        transactions: [
            {"date":"2026-08-20T07:00Z","description":"Waived/injured T Matt Waletzko. Waived DE Anthony Dunn. Signed T Kellen Diesch."},
            {"date":"2026-08-18T07:00Z","description":"Signed LB Cam Jones. Waived CB Anthony Dunn."},
            {"date":"2026-08-14T07:00Z","description":"Waived DB Bryce Phillips."},
            {"date":"2026-08-13T07:00Z","description":"Signed DE Emmanuel Ogbah."},
            {"date":"2026-08-03T07:00Z","description":"Signed WR Jeff Weimer."},
        ],
    },
    "LAC": {
        news: [
            {"id":"49662894","headline":"Chargers rookie Akheem Mesidor paving way for Ottawa NFL players","summary":"Ottawa is having a moment in the NFL. And the city's first first-rounder Akheem Mesidor hopes to usher in the next generation.","date":"2026-08-21T13:49:02Z","url":"https://www.espn.com/nfl/story/_/id/49662894/los-angeles-chargers-akheem-mesidor-ottawa-canada-nfl-players"},
            {"id":"49677368","headline":"Cowing returns punt for TD to spark the 49ers in 41-17 preseason win over the Chargers","summary":"— Jacob Cowing let out a season's worth of frustration with one electric play.","date":"2026-08-21T06:24:29Z","url":"http://www.espn.com/nfl/recap?gameId=401873285"},
            {"id":"49677343","headline":"San Francisco 49ers vs. Los Angeles Chargers: Game Highlights","summary":"San Francisco 49ers vs. Los Angeles Chargers: Game Highlights","date":"2026-08-21T05:12:08Z","url":"https://www.espn.com/video/clip/_/id/49677343/game-highlights"},
            {"id":"49662233","headline":"What are the Chargers' takeaways from their joint practice with the 49ers?","summary":"Kris Rhim breaks down the takeaways from the Chargers' joint practice with the 49ers.","date":"2026-08-20T03:44:16Z","url":"https://www.espn.com/video/clip/_/id/49662233/what-chargers-takeaways-their-joint-practice-49ers"},
        ],
        transactions: [
            {"date":"2026-08-20T07:00Z","description":"Placed WR Luke Grimm on injured reserve."},
            {"date":"2026-08-18T07:00Z","description":"Signed WR Liam Clifford. Waived/injured WR Luke Grimm."},
            {"date":"2026-08-10T07:00Z","description":"Signed OLB Andre Carter II. Waived WR Mante Morrow."},
            {"date":"2026-07-28T07:00Z","description":"Signed LS Peter Bowden to a contract."},
            {"date":"2026-07-27T07:00Z","description":"Released G Ben Cleveland."},
        ],
    },
    "LAR": {
        news: [
            {"id":"49673878","headline":"Aaron Donald to continue workouts with Rams as decision looms","summary":"Rams head coach Sean McVay said he anticipates more workouts from Aaron Donald before the defensive tackle decides whether to come out of retirement.","date":"2026-08-20T21:13:05Z","url":"https://www.espn.com/nfl/story/_/id/49673878/aaron-donald-continue-workouts-rams-decision-looms"},
            {"id":"49641695","headline":"Rams not looking to rush WR Puka Nacua, DE Myles Garrett back to practice","summary":"The Rams want Puka Nacua and Myles Garrett to be 100% healthy before they return from injuries, coach Sean McVay said.","date":"2026-08-17T20:43:12Z","url":"https://www.espn.com/nfl/story/_/id/49641695/rams-not-looking-rush-wr-puka-nacua-de-myles-garrett-back-practice"},
            {"id":"49631972","headline":"Retired Aaron Donald works out for Rams for second time","summary":"Aaron Donald worked out for the Los Angeles Rams on Saturday as he continues his process to determine whether he wants to come out of retirement.","date":"2026-08-16T21:20:48Z","url":"https://www.espn.com/nfl/story/_/id/49631972/retired-aaron-donald-works-rams-second"},
        ],
        transactions: [
            {"date":"2026-08-18T07:00Z","description":"Reverted WR Mario Williams to injured reserve after he cleared waivers."},
            {"date":"2026-08-16T07:00Z","description":"Signed P Jack Bouwmeester."},
            {"date":"2026-08-13T07:00Z","description":"Signed LB Monty Rice."},
            {"date":"2026-08-10T07:00Z","description":"Signed CB Zech McPhearson. Waived DB Drey Norwood."},
            {"date":"2026-08-09T07:00Z","description":"Placed S Drey Norwood on injured reserve."},
        ],
    },
    "LV": {
        news: [
            {"id":"49681247","headline":"Why Swagu is picking Cousins as Raiders' starting QB, for now","summary":"Why Swagu is picking Cousins as Raiders' starting QB, for now","date":"2026-08-21T14:34:24Z","url":"https://www.espn.com/video/clip/_/id/49681247/why-swagu-picking-cousins-raiders-starting-qb-now"},
            {"id":"49679288","headline":"Raiders' QB1 still undecided","summary":"Ryan McFadden details Klint Kubiak not ready to name a Week 1 starter.","date":"2026-08-21T10:26:05Z","url":"https://www.espn.com/video/clip/_/id/49679288/raiders-qb1-undecided"},
            {"id":"49677418","headline":"Kubiak keeps Raiders' QB race going: 'We got another week'","summary":"With one week left in the preseason, Raiders coach Klint Kubiak said he wasn't prepared to name a starting quarterback, adding \"I don't want anyone to be comfortable in their job.\"","date":"2026-08-21T05:55:41Z","url":"https://www.espn.com/nfl/story/_/id/49677418/kubiak-keeps-raiders-qb-race-going-got-another-week"},
            {"id":"49676628","headline":"Fernando Mendoza throws a pick-6, struggles in 1st half of Raiders' 22-20 preseason win over Texans","summary":"— Top pick Fernando Mendoza is finding out quickly that he has a lot of work to do as he begins his NFL career.","date":"2026-08-21T04:37:28Z","url":"http://www.espn.com/nfl/recap?gameId=401873286"},
        ],
        transactions: [
            {"date":"2026-08-17T07:00Z","description":"Signed WR Noah Brown. Released DT Benito Jones."},
            {"date":"2026-08-15T07:00Z","description":"Signed DT Folorunso Fatukasi. Placed LB Brennan Jackson on injured reserve."},
            {"date":"2026-08-13T07:00Z","description":"Placed G Justin Pickett on injured reserve"},
            {"date":"2026-08-12T07:00Z","description":"Signed OL Braeden Daniels. Waived G Justin Pickett with an injury designation."},
            {"date":"2026-08-06T07:00Z","description":"Signed RB Dare Ogunbowale to a contract."},
        ],
    },
    "MIA": {
        news: [
            {"id":"49675355","headline":"Dolphins less interested in winning joint practice than improving","summary":"The Dolphins had some highlights against the Giants, but coach Jeff Hafley had his eyes on one-on-one battles.","date":"2026-08-21T10:00:27Z","url":"https://www.espn.com/nfl/story/_/id/49675355/miami-dolphins-joint-practice-new-york-giants"},
            {"id":"49675025","headline":"Breaking down the Giants-Dolphins joint practice","summary":"Marcel Louis-Jacques discusses the up-and-down day for the Dolphins during their joint practice with the Giants.","date":"2026-08-20T23:24:42Z","url":"https://www.espn.com/video/clip/_/id/49675025/breaking-giants-dolphins-joint-practice"},
            {"id":"49672671","headline":"Players pulled from fight-filled Giants-Dolphins practice","summary":"Multiple players from Thursday's joint practice between the Dolphins and Giants were pulled for throwing punches or their physical actions during a fight-filled workout.","date":"2026-08-21T04:45:14Z","url":"https://www.espn.com/nfl/story/_/id/49672671/players-pulled-fight-filled-giants-dolphins-practice"},
            {"id":"49638440","headline":"Dolphins activate rookie Chris Bell ahead of practice debut","summary":"The Dolphins activated rookie wide receiver Chris Bell from the active/non-football injury list Monday, paving the way for him to make his practice debut.","date":"2026-08-17T15:58:10Z","url":"https://www.espn.com/nfl/story/_/id/49638440/dolphins-activate-chris-bell-paving-way-practice-debut"},
        ],
        transactions: [
            {"date":"2026-08-21T07:00Z","description":"Signed LB Stephen Dix. Jr.. Waived OL James Ester with an injury settlement."},
            {"date":"2026-08-18T07:00Z","description":"Released K Zane Gonzalez from injured reserve. Reverted EDGE Mason Reiger to injured reserve after he cleared waivers."},
            {"date":"2026-08-17T07:00Z","description":"Reinstated WR Chris Bell from the active/non-football injury list. Signed DT Cam Rice. Waived DB Tanner Wall. Reverted DB Ethan Robinson to injured reserve after he cleared waivers."},
            {"date":"2026-08-16T07:00Z","description":"Signed QB Mark Gronowski and LB Cam Riley. Waived DB Ethan Robinson. Placed G Jamaree Salyer on injured reserve."},
            {"date":"2026-08-12T07:00Z","description":"Waived DT Omar Brown."},
        ],
    },
    "MIN": {
        news: [
            {"id":"49675098","headline":"Vikings defense looks dominant in joint practice","summary":"Kevin Seifert breaks down expectations for the Vikings' defense this season.","date":"2026-08-20T23:37:17Z","url":"https://www.espn.com/video/clip/_/id/49675098/vikings-defense-looks-dominant-joint-practice"},
            {"id":"49376202","headline":"2026 Minnesota Vikings training camp: Latest intel, updates","summary":"Catch up on our daily updates from Vikings training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-20T21:36:43Z","url":"https://www.espn.com/nfl/story/_/id/49376202/minnesota-vikings-training-camp-2026-intel-updates"},
            {"id":"49664625","headline":"QB2 still undecided for the Vikings","summary":"Kevin Seifert breaks down the QB2 battle in Minnesota.","date":"2026-08-20T00:10:44Z","url":"https://www.espn.com/video/clip/_/id/49664625/qb2-undecided-vikings"},
            {"id":"49650193","headline":"Coach Carter brings old-school toughness to Vikings' O-line","summary":"Minnesota's new offensive line coach is pushing players beyond their comfort zone -- and they're buying in.","date":"2026-08-19T12:16:15Z","url":"https://www.espn.com/nfl/story/_/id/49650193/nfl-minnesota-vikings-keith-carter-offensive-line-darrisaw"},
        ],
        transactions: [
            {"date":"2026-08-18T07:00Z","description":"Signed G Joshua Gray. Released DL Eric Johnson II."},
            {"date":"2026-08-17T07:00Z","description":"Signed DB Bryce Phillips and LB Kenny Dyson. Waived DE Arden Walker. Placed LB Jamal Adams on injured reserve."},
            {"date":"2026-08-12T07:00Z","description":"Signed RB Jermar Jefferson. Waived RB Jordan Mims."},
            {"date":"2026-08-02T07:00Z","description":"Signed CB Jarod Washington. Waived RB Kejon Owens."},
            {"date":"2026-07-28T07:00Z","description":"Signed S Jamal Adams and RB Jordan Mims to contracts. Signed T Brian O'Neill to a four-year contract extension through the 2030 season."},
        ],
    },
    "NE": {
        news: [
            {"id":"49674444","headline":"Drake Maye-A.J. Brown connection growing at Patriots camp","summary":"Drake Maye-A.J. Brown connection growing at Patriots camp","date":"2026-08-20T21:58:34Z","url":"https://www.espn.com/video/clip/_/id/49674444/drake-maye-aj-brown-connection-growing-patriots-camp"},
            {"id":"49427703","headline":"2026 New England Patriots training camp: Latest intel, updates","summary":"Catch up on our daily updates from Patriots training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-20T20:07:59Z","url":"https://www.espn.com/nfl/story/_/id/49427703/new-england-patriots-training-camp-2026-intel-updates"},
            {"id":"49661851","headline":"Patriots' Brown professes 'love' for Hurts, Eagles after practice","summary":"Patriots receiver A.J. Brown said he has nothing but \"love\" for the Eagles and former teammate Jalen Hurts following the two teams' joint practice.","date":"2026-08-19T20:04:02Z","url":"https://www.espn.com/nfl/story/_/id/49661851/patriots-brown-professes-love-hurts-eagles-practice"},
            {"id":"49648149","headline":"How will the Patriots respond in 2026 to the Super Bowl loss?","summary":"After an eventful offseason with much roster turnover, New England is again focusing on identity to combat a harder schedule this season.","date":"2026-08-19T16:04:53Z","url":"https://www.espn.com/nfl/story/_/id/49648149/new-england-patriots-how-respond-super-bowl-loss-2026-season"},
        ],
        transactions: [
            {"date":"2026-08-21T07:00Z","description":"Waived G Andrew Rupcich with an injury settlement."},
            {"date":"2026-08-20T07:00Z","description":"Waived T Andrew Rupcich from injured reserve with a settlement."},
            {"date":"2026-08-18T07:00Z","description":"Signed OL Greg Van Roten. Waived TE Mitch Van Vooren."},
            {"date":"2026-08-15T07:00Z","description":"Signed OLs Darrian Dalcourt and Joe Michalski. Waived LS Niko Lalos. Placed G Andrew Rupcich on injured reserve. Waived RB Terrell Jennings with an injury settlement."},
            {"date":"2026-08-13T07:00Z","description":"Signed RB JaMycal Hasty. Placed RB Terrell Jennings on injured reserve."},
        ],
    },
    "NO": {
        news: [
            {"id":"49673882","headline":"Cowboys, Saints fined $500K each for brawls in joint practice","summary":"The NFL has fined the Cowboys and Saints $500,000 each after multiple fights broke out between the two teams during Tuesday's joint practice.","date":"2026-08-20T22:02:07Z","url":"https://www.espn.com/nfl/story/_/id/49673882/cowboys-saints-fined-500k-brawls-joint-practices"},
            {"id":"49658952","headline":"Source: Saints RB Kamara out at least 1 month with MCL sprain","summary":"Saints RB Alvin Kamara is expected to be sidelined for at least the next month due to a sprained MCL, a source told ESPN's Adam Schefter.","date":"2026-08-19T21:45:46Z","url":"https://www.espn.com/nfl/story/_/id/49658952/source-saints-rb-kamara-least-month-mcl-sprain"},
            {"id":"49653675","headline":"Multiple brawls mar Saints-Cowboys joint practice session","summary":"The Cowboys and Saints had so many fights during their joint session Tuesday that the coaches of each team discussed whether they needed to cancel the practice.","date":"2026-08-20T20:44:55Z","url":"https://www.espn.com/nfl/story/_/id/49653675/multiple-brawls-mar-saints-cowboys-joint-practice-session"},
            {"id":"49647746","headline":"How Jordyn Tyson's injury could impact the Saints this season","summary":"How Jordyn Tyson's injury could impact the Saints this season","date":"2026-08-18T12:32:47Z","url":"https://www.espn.com/video/clip/_/id/49647746/how-jordyn-tyson-injury-impact-saints-season"},
        ],
        transactions: [
            {"date":"2026-08-18T07:00Z","description":"Waived DT KeeShawn Silver."},
            {"date":"2026-08-17T07:00Z","description":"Waived DT Keeshawn Silver."},
            {"date":"2026-08-12T07:00Z","description":"Signed DT Kahlil Saunders. Placed OL Dillon Radunz on injured reserve, ending his season."},
            {"date":"2026-08-09T07:00Z","description":"Waived DT Zxavian Harris."},
            {"date":"2026-08-08T07:00Z","description":"Reverted DT Keeshawn Silver to injured reserve after clearing waivers. Signed LB Deion Jones, DT Brien Taylor, and DE Malakai Williams. Waived DT Zxavian Harris."},
        ],
    },
    "NYG": {
        news: [
            {"id":"49665736","headline":"Cam Skattebo still top option in crowded Giants backfield","summary":"With the addition of Najee Harris, it's difficult to predict New York's backfield carries at this point.","date":"2026-08-21T10:00:12Z","url":"https://www.espn.com/nfl/story/_/id/49665736/cam-skattebo-najee-harris-new-york-giants-top-option-crowded-backfield"},
            {"id":"49675123","headline":"Jaxson Dart shines as Giants dominate joint practice with Dolphins","summary":"Dart went 17/23 with several completions downfield as the Giants' offense and defense impressed against Miami.","date":"2026-08-21T10:42:39Z","url":"https://www.espn.com/video/clip/_/id/49675123/jaxson-dart-shines-giants-dominate-joint-practice-dolphins"},
            {"id":"49434181","headline":"2026 New York Giants training camp: Latest intel, updates","summary":"Catch up on our updates from Giants training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-20T20:39:57Z","url":"https://www.espn.com/nfl/story/_/id/49434181/new-york-giants-training-camp-2026-intel-updates"},
            {"id":"49672671","headline":"Players pulled from fight-filled Giants-Dolphins practice","summary":"Multiple players from Thursday's joint practice between the Dolphins and Giants were pulled for throwing punches or their physical actions during a fight-filled workout.","date":"2026-08-21T04:45:14Z","url":"https://www.espn.com/nfl/story/_/id/49672671/players-pulled-fight-filled-giants-dolphins-practice"},
        ],
        transactions: [
            {"date":"2026-08-18T07:00Z","description":"Claimed DT Ben Barten off waivers from the New York Jets."},
            {"date":"2026-08-17T07:00Z","description":"Signed QB Jake Haener and LB Chandler Martin. Waived/injured RB Dante Miller."},
            {"date":"2026-08-16T07:00Z","description":"Placed CB Sam Webb on the reserve/retired list."},
            {"date":"2026-08-14T07:00Z","description":"Placed DB DJ James on injured reserve. Waived WR Beaux Collins with an injury settlement."},
            {"date":"2026-08-13T07:00Z","description":"Signed DBs Ugo Amadi and Sam Webb."},
        ],
    },
    "NYJ": {
        news: [
            {"id":"49673504","headline":"Jets owner Woody Johnson buys stake in Aston Martin F1 team","summary":"New York Jets chairman Woody Johnson has acquired a minority stake in the Aston Martin Aramco Formula 1 racing team and will join the company's board of directors as vice chairman,…","date":"2026-08-20T20:16:03Z","url":"https://www.espn.com/nfl/story/_/id/49673504/jets-owner-woody-johnson-buys-stake-aston-martin-f1-team"},
            {"id":"49649540","headline":"Can Adonai Mitchell be 'Robin' that Jets are searching for?","summary":"New York has struggled to find a complement to Garrett Wilson since drafting him in 2022.","date":"2026-08-20T14:07:35Z","url":"https://www.espn.com/nfl/story/_/id/49649540/new-york-jets-adonai-mitchell-wr2-answer-garrett-wilson"},
            {"id":"49663595","headline":"Who will be the Jets' starting QB this week against the Steelers?","summary":"Rich Cimini reports the latest on Geno Smith's ankle injury and how Aaron Glenn is handling the quarterback room this preseason.","date":"2026-08-19T22:09:24Z","url":"https://www.espn.com/video/clip/_/id/49663595/who-jets-starting-qb-week-steelers"},
            {"id":"49419756","headline":"2026 New York Jets training camp: Latest intel, updates","summary":"Catch up on our updates from Jets training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-19T20:17:44Z","url":"https://www.espn.com/nfl/story/_/id/49419756/new-york-jets-training-camp-2026-intel-updates"},
        ],
        transactions: [
            {"date":"2026-08-21T07:00Z","description":"Waived WR D.T. Sheffield with an injury settlement."},
            {"date":"2026-08-20T07:00Z","description":"Placed WR D.T. Sheffield on injured reserve."},
            {"date":"2026-08-18T07:00Z","description":"Signed WR Junior Bergen. Waived/injured WR DT Sheffield. Reverted EDGE Kingsley Jonathan to injured reserve after he cleared waivers."},
            {"date":"2026-08-14T07:00Z","description":"Waived DE Eric Watts."},
            {"date":"2026-08-06T07:00Z","description":"Claimed DL Junior Tafuna off waivers from Houston. Waived DL Patrick Jenkins"},
        ],
    },
    "PHI": {
        news: [
            {"id":"49674522","headline":"Riq Woolen impresses at Eagles' practice","summary":"Tim McManus breaks down cornerback Riq Woolen's performance at Eagles-Patriots joint practice.","date":"2026-08-20T22:02:55Z","url":"https://www.espn.com/video/clip/_/id/49674522/riq-woolen-impresses-eagles-practice"},
            {"id":"49434399","headline":"2026 Philadelphia Eagles training camp: Latest intel, updates","summary":"Catch up on our updates from Eagles training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-20T20:16:31Z","url":"https://www.espn.com/nfl/story/_/id/49434399/philadelphia-eagles-training-camp-2026-intel-updates"},
            {"id":"49673017","headline":"'I hate joint practices,' Eagles star Saquon Barkley says","summary":"Eagles running back Saquon Barkley said he hates back-to-back days of joint practices, adding \"one day is good\" to avoid skirmishes that regularly occur during the sessions.","date":"2026-08-20T19:40:06Z","url":"https://www.espn.com/nfl/story/_/id/49673017/i-hate-joint-practices-says-eagles-star-saquon-barkley"},
        ],
        transactions: [
            {"date":"2026-08-21T07:00Z","description":"Signed C Zeke Correll and WR Brandon Hayes. Placed CB Tariq Castro-Fields on injured reserve. Waived WR Johnny Wilson with an injury settlement."},
            {"date":"2026-08-18T07:00Z","description":"Waived T Hollin Pierce."},
            {"date":"2026-08-17T07:00Z","description":"Signed DB Isaiah Bolden. Waived T Hollin Pierce."},
            {"date":"2026-08-15T07:00Z","description":"Signed LB Brandon George. Waived WR Brandon Hayes."},
            {"date":"2026-08-10T07:00Z","description":"Signed DT David Blay Jr., RB Ja'Quinden Jackson and OLB Tarron Jackson. Waived G Jaeden Roberts and TE Dae'Quan Wright. Placed RB Elijah Mitchell on injured reserve."},
        ],
    },
    "PIT": {
        news: [
            {"id":"49660895","headline":"Howard, Allar to get all of Steelers' QB reps vs. Jets","summary":"The Steelers will start second-year quarterback Will Howard against the Jets on Friday while 2026 fourth-round pick Drew Allar will follow.","date":"2026-08-20T10:43:51Z","url":"https://www.espn.com/nfl/story/_/id/49660895/howard-allar-get-all-steelers-qb-reps-vs-jets"},
            {"id":"49449169","headline":"2026 Pittsburgh Steelers training camp: Latest intel, updates","summary":"Catch up on our daily updates from Steelers training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-17T19:18:18Z","url":"https://www.espn.com/nfl/story/_/id/49449169/pittsburgh-steelers-training-camp-2026-intel-updates"},
            {"id":"49614342","headline":"Steelers' Keeanu Benton agrees to 4-year, $72M extension, sources say","summary":"The Steelers and defensive tackle Keeanu Benton have agreed to a four-year, $72 million extension, sources told NFL Network's Ian Rapoport.","date":"2026-08-15T13:38:54Z","url":"https://www.espn.com/nfl/story/_/id/49614342/steelers-keeanu-benton-agrees-4-year-72m-extension-sources-say"},
        ],
        transactions: [
            {"date":"2026-08-15T07:00Z","description":"Agreed to terms with DT Keeanu Benton on a four-year contract extension."},
            {"date":"2026-08-14T07:00Z","description":"Waived OT Lorenzo Thompson with an injury settlement."},
            {"date":"2026-08-13T07:00Z","description":"Signed LB Elandon Roberts."},
            {"date":"2026-08-10T07:00Z","description":"Signed WRs Cornell Powell and Isaiah Winstead. Waived T Lorenzo Thompson."},
            {"date":"2026-08-09T07:00Z","description":"Waived WR Colton Dowell."},
        ],
    },
    "SEA": {
        news: [
            {"id":"49427699","headline":"2026 Seattle Seahawks training camp: Latest intel, updates","summary":"Catch up on our daily updates from Seahawks training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-20T20:19:15Z","url":"https://www.espn.com/nfl/story/_/id/49427699/seattle-seahawks-training-camp-2026-intel-updates"},
            {"id":"49661802","headline":"Source: CB Trevon Diggs signing 1-year deal with Seahawks","summary":"Former Cowboys Pro Bowl cornerback Trevon Diggs plans to sign a one-year deal with the Seahawks, a source told ESPN's Adam Schefter on Wednesday.","date":"2026-08-19T22:02:15Z","url":"https://www.espn.com/nfl/story/_/id/49661802/source-seahawks-sign-former-pro-bowl-cb-trevon-diggs"},
            {"id":"49649996","headline":"Sources: Seahawks still plan on signing Terrion Arnold","summary":"The Seattle Seahawks are still planning to sign cornerback Terrion Arnold, but it will take a while, as they are working through the timing, sources told NFL Network.","date":"2026-08-18T23:31:43Z","url":"https://www.espn.com/nfl/story/_/id/49649996/sources-seahawks-plan-signing-terrion-arnold"},
        ],
        transactions: [
            {"date":"2026-08-20T07:00Z","description":"Waived WR Julian Hicks."},
            {"date":"2026-08-18T07:00Z","description":"Signed CB Trevon Diggs. Waived WR Julian Hicks."},
            {"date":"2026-08-17T07:00Z","description":"Signed LB Power Echols, RB Anthony Hankerson and WR Julian Hicks. Waived RBs T.J. Harden and Justin Jones. Placed DB Shemar Jean-Charles on injured reserve."},
            {"date":"2026-08-15T07:00Z","description":"Agreed to terms with CB Devon Witherspoon on a four-year contract extension."},
            {"date":"2026-08-14T07:00Z","description":"Waived DB Brandon Johnson with an injury settlement."},
        ],
    },
    "SF": {
        news: [
            {"id":"49677368","headline":"Cowing returns punt for TD to spark the 49ers in 41-17 preseason win over the Chargers","summary":"— Jacob Cowing let out a season's worth of frustration with one electric play.","date":"2026-08-21T06:24:29Z","url":"http://www.espn.com/nfl/recap?gameId=401873285"},
            {"id":"49677343","headline":"San Francisco 49ers vs. Los Angeles Chargers: Game Highlights","summary":"San Francisco 49ers vs. Los Angeles Chargers: Game Highlights","date":"2026-08-21T05:12:08Z","url":"https://www.espn.com/video/clip/_/id/49677343/game-highlights"},
            {"id":"49651267","headline":"49ers return their 'bullies' in Deebo Samuel, Dre Greenlaw","summary":"Greenlaw and Samuel are back in key roles for the 49ers. How will Greenlaw slot in at linebacker? Will Samuel be a rushing threat again?","date":"2026-08-20T13:57:58Z","url":"https://www.espn.com/nfl/story/_/id/49651267/san-francisco-49ers-deebo-samuel-dre-greenlaw-return"},
            {"id":"49666480","headline":"49ers ready for the Chargers","summary":"Nick Wagoner breaks down the 49ers' preparation for the Chargers.","date":"2026-08-20T04:15:59Z","url":"https://www.espn.com/video/clip/_/id/49666480/49ers-ready-chargers"},
        ],
        transactions: [
            {"date":"2026-08-20T07:00Z","description":"Signed RB Khalil Herbert. Placed RB Patrick Taylor on injured reserve."},
            {"date":"2026-08-18T07:00Z","description":"Reverted DL Titus Leo to injured reserve after he cleared waivers."},
            {"date":"2026-08-17T07:00Z","description":"Signed LB Victor Dimukeje and G Nick Zakelj. Released RB Khalil Herbert and G Kion Smith."},
            {"date":"2026-08-13T07:00Z","description":"Placed DE KJ Henry on injured reserve."},
            {"date":"2026-08-12T07:00Z","description":"Signed CB Eli Apple, RB Zamir White and DE Xavier Thomas. Waived LB Junior Bergen and WR Jack Bouwmeester and DE K.J. Henry (injured)."},
        ],
    },
    "TB": {
        news: [
            // none
        ],
        transactions: [
            {"date":"2026-08-20T07:00Z","description":"Waived DB Marcus Banks from injured reserve with a settlement."},
            {"date":"2026-08-18T07:00Z","description":"Reverted DB Marcus Banks and RB Kadarius Calloway to injured reserve after they cleared waivers."},
            {"date":"2026-08-17T07:00Z","description":"Signed RB Barika Kpeenu and DB Robert McDaniel. Waived/injured DB Marcus Banks and RB Kadarius Calloway."},
            {"date":"2026-08-10T07:00Z","description":"Signed CB Roman Parodie. Placed DB Kemon Hall on injured reserve."},
            {"date":"2026-07-31T07:00Z","description":"Reverted DT Haggai Chisom Ndubuisi to the PUP list."},
        ],
    },
    "TEN": {
        news: [
            {"id":"49684971","headline":"Titans offense efficient in joint practice with Seahawks","summary":"Turron Davenport recaps the Titans' joint practice with the Seahawks Friday afternoon.","date":"2026-08-21T22:37:20Z","url":"https://www.espn.com/video/clip/_/id/49684971/titans-offense-efficient-joint-practice-seahawks"},
            {"id":"49619516","headline":"Why Titans believe Daboll can maximize Ward's potential","summary":"The Titans are looking for the Cam Ward-Brian Daboll relationship to be as effective as what Daboll enjoyed in Buffalo.","date":"2026-08-16T10:00:03Z","url":"https://www.espn.com/nfl/story/_/id/49619516/why-titans-believe-brian-daboll-maximize-cam-ward-potential"},
            {"id":"49605904","headline":"Cam Ward struggles in the Titans' 19-13 preseason win over the 49ers","summary":"— Cam Ward struggled in three drives for Tennessee against San Francisco's backup defense and the...","date":"2026-08-14T15:43:29Z","url":"http://www.espn.com/nfl/recap?gameId=401874392"},
            {"id":"49419824","headline":"2026 Tennessee Titans training camp: Latest intel, updates","summary":"Catch up on our daily updates from Titans training camp, including intel on QBs, position battles and potential breakouts.","date":"2026-08-13T19:51:58Z","url":"https://www.espn.com/nfl/story/_/id/49419824/tennessee-titans-training-camp-2026-intel-updates"},
        ],
        transactions: [
            {"date":"2026-08-21T07:00Z","description":"Signed LB Milo Eifler and DE Tanoh Kpassagnon. Waived LB Sean Brown with an injury settlement. Released TE Matt Lauter. Placed DB Nazeeh Johnson on injured reserve."},
            {"date":"2026-08-20T07:00Z","description":"Waived RB Dominic Richardson."},
            {"date":"2026-08-18T07:00Z","description":"Signed RB D'Ernest Johnson. Waived RB Dominic Richardson."},
            {"date":"2026-08-17T07:00Z","description":"Signed DB Corey Mayfield. Waived/injured LB Sean Brown."},
            {"date":"2026-08-16T07:00Z","description":"Signed TE Matt Lauter and RB Dominic Richardson. Placed LB Jaylen Harrell and TE Jaren Kanak on injured reserve."},
        ],
    },
    "WAS": {
        news: [
            {"id":"49674003","headline":"Commanders need to show how far they've come vs. Lions","summary":"Third-year QB Jayden Daniels is looking like he did in 2024, but can a revamped defense hold up its end?","date":"2026-08-21T10:00:02Z","url":"https://www.espn.com/nfl/story/_/id/49674003/washington-commanders-jayden-daniels-accuracy"},
            {"id":"49673283","headline":"Commanders' O-line faces early concerns","summary":"John Keim reports on the Commanders' O-line injuries and backup options.","date":"2026-08-20T19:46:50Z","url":"https://www.espn.com/video/clip/_/id/49673283/commanders-o-line-faces-early-concerns"},
            {"id":"49666395","headline":"Sonny Styles' goal for Commanders' second preseason game","summary":"John Keim discusses Sonny Styles' recent play in practice leading up to the Commanders' second preseason game.","date":"2026-08-20T04:16:55Z","url":"https://www.espn.com/video/clip/_/id/49666395/sonny-styles-goal-commanders-second-preseason-game"},
            {"id":"49665858","headline":"Source: Commanders DL Newton has surgery to repair torn pec","summary":"Commanders defensive lineman Jer'Zhan Newton underwent surgery Wednesday to repair a torn pectoral muscle, a source confirmed.","date":"2026-08-20T19:33:07Z","url":"https://www.espn.com/nfl/story/_/id/49665858/source-commanders-dl-newton-surgery-repair-torn-pec"},
        ],
        transactions: [
            {"date":"2026-08-18T07:00Z","description":"Signed LB Krys Barnes, DT Maurice Hurst II, TE Tre McKitty and RB Craig Reynolds. Waived K Jake Moody. Released P Matt Haack. Placed WR River Cracraft and RB Jerome Ford on injured reserve."},
            {"date":"2026-08-12T07:00Z","description":"Waived G Sala Aumavae-Laulu and S Rob McDaniel."},
            {"date":"2026-08-11T07:00Z","description":"Signed DT Byron Cowart. Released G Sala Aumavae-Laulu and S Rob McDaniel. Signed LB Curtis Jacobs to a contract."},
            {"date":"2026-08-09T07:00Z","description":"Waived G Timothy McKay."},
            {"date":"2026-08-08T07:00Z","description":"Placed DT D.J. Davidson on the retired list. Signed C Daniel Brunskill, T Nicholas Petit-Frere, and G Max Scharping. Waived WR Chris Hilton and T Timothy McKay."},
        ],
    },
};

export const getOffseasonNews = (abbr) => offseasonNews[abbr] || { news: [], transactions: [] };
