// Auto-generated from scripts/rawTierList2026.txt (2026 season default board).
// To regenerate after editing the raw file, run: node scripts/generatePlayerDatabase.js
// Headshots fall back to initials in the UI when a photo is missing.

const PLACEHOLDER_PHOTO =
    "https://www.shutterstock.com/image-vector/vector-flat-illustration-grayscale-avatar-600nw-2264922221.jpg";

const dstLogo = (team) => `https://a.espncdn.com/i/teamlogos/nfl/500/${team === "jac" ? "jax" : team}.png`;

export const playerDatabase = {
    "bijan-robinson": { id: "bijan-robinson", name: "Bijan Robinson", position: "RB", team: "ATL", photo: "https://sleepercdn.com/content/nfl/players/thumb/9509.jpg", tier: 1, ecr: 1, adp: 2 },
    "jahmyr-gibbs": { id: "jahmyr-gibbs", name: "Jahmyr Gibbs", position: "RB", team: "DET", photo: "https://sleepercdn.com/content/nfl/players/thumb/9221.jpg", tier: 1, ecr: 2, adp: 1 },
    "jamarr-chase": { id: "jamarr-chase", name: "Ja'Marr Chase", position: "WR", team: "CIN", photo: "https://sleepercdn.com/content/nfl/players/thumb/7564.jpg", tier: 1, ecr: 3, adp: 3 },
    "puka-nacua": { id: "puka-nacua", name: "Puka Nacua", position: "WR", team: "LAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/9493.jpg", tier: 1, ecr: 4, adp: 4 },
    "jaxon-smith-njigba": { id: "jaxon-smith-njigba", name: "Jaxon Smith-Njigba", position: "WR", team: "SEA", photo: "https://sleepercdn.com/content/nfl/players/thumb/9488.jpg", tier: 1, ecr: 5, adp: 5 },
    "amon-ra-st-brown": { id: "amon-ra-st-brown", name: "Amon-Ra St. Brown", position: "WR", team: "DET", photo: "https://sleepercdn.com/content/nfl/players/thumb/7547.jpg", tier: 1, ecr: 6, adp: 8 },
    "christian-mccaffrey": { id: "christian-mccaffrey", name: "Christian McCaffrey", position: "RB", team: "SF", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3117251.png", tier: 1, ecr: 7, adp: 6 },

    "ceedee-lamb": { id: "ceedee-lamb", name: "CeeDee Lamb", position: "WR", team: "DAL", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4241389.png", tier: 2, ecr: 8, adp: 11 },
    "jonathan-taylor": { id: "jonathan-taylor", name: "Jonathan Taylor", position: "RB", team: "IND", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4242335.png", tier: 2, ecr: 9, adp: 7 },
    "justin-jefferson": { id: "justin-jefferson", name: "Justin Jefferson", position: "WR", team: "MIN", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4262921.png", tier: 2, ecr: 10, adp: 9 },
    "james-cook-iii": { id: "james-cook-iii", name: "James Cook III", position: "RB", team: "BUF", photo: "https://sleepercdn.com/content/nfl/players/thumb/8138.jpg", tier: 2, ecr: 11, adp: 10 },
    "ashton-jeanty": { id: "ashton-jeanty", name: "Ashton Jeanty", position: "RB", team: "LV", photo: "https://sleepercdn.com/content/nfl/players/thumb/12527.jpg", tier: 2, ecr: 12, adp: 12 },
    "drake-london": { id: "drake-london", name: "Drake London", position: "WR", team: "ATL", photo: "https://sleepercdn.com/content/nfl/players/thumb/8112.jpg", tier: 2, ecr: 13, adp: 21 },
    "devon-achane": { id: "devon-achane", name: "De'Von Achane", position: "RB", team: "MIA", photo: "https://sleepercdn.com/content/nfl/players/thumb/9226.jpg", tier: 2, ecr: 14, adp: 15 },
    "nico-collins": { id: "nico-collins", name: "Nico Collins", position: "WR", team: "HOU", photo: "https://sleepercdn.com/content/nfl/players/thumb/7569.jpg", tier: 2, ecr: 15, adp: 23 },

    "saquon-barkley": { id: "saquon-barkley", name: "Saquon Barkley", position: "RB", team: "PHI", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3929630.png", tier: 3, ecr: 16, adp: 13 },
    "brock-bowers": { id: "brock-bowers", name: "Brock Bowers", position: "TE", team: "LV", photo: "https://sleepercdn.com/content/nfl/players/thumb/11604.jpg", tier: 3, ecr: 17, adp: 16 },
    "chase-brown": { id: "chase-brown", name: "Chase Brown", position: "RB", team: "CIN", photo: "https://sleepercdn.com/content/nfl/players/thumb/9224.jpg", tier: 3, ecr: 18, adp: 17 },
    "aj-brown": { id: "aj-brown", name: "A.J. Brown", position: "WR", team: "NE", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4047646.png", tier: 3, ecr: 19, adp: 20 },
    "omarion-hampton": { id: "omarion-hampton", name: "Omarion Hampton", position: "RB", team: "LAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/12507.jpg", tier: 3, ecr: 20, adp: 14 },
    "george-pickens": { id: "george-pickens", name: "George Pickens", position: "WR", team: "DAL", photo: "https://sleepercdn.com/content/nfl/players/thumb/8137.jpg", tier: 3, ecr: 21, adp: 25 },
    "trey-mcbride": { id: "trey-mcbride", name: "Trey McBride", position: "TE", team: "ARI", photo: "https://sleepercdn.com/content/nfl/players/thumb/8130.jpg", tier: 3, ecr: 22, adp: 19 },
    "derrick-henry": { id: "derrick-henry", name: "Derrick Henry", position: "RB", team: "BAL", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3043078.png", tier: 3, ecr: 23, adp: 22 },
    "kenneth-walker-iii": { id: "kenneth-walker-iii", name: "Kenneth Walker III", position: "RB", team: "KC", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/2971595.png", tier: 3, ecr: 24, adp: 18 },
    "chris-olave": { id: "chris-olave", name: "Chris Olave", position: "WR", team: "NO", photo: "https://sleepercdn.com/content/nfl/players/thumb/8144.jpg", tier: 3, ecr: 25, adp: 27 },
    "josh-allen": { id: "josh-allen", name: "Josh Allen", position: "QB", team: "BUF", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/17102.png", tier: 3, ecr: 26, adp: 24 },
    "rashee-rice": { id: "rashee-rice", name: "Rashee Rice", position: "WR", team: "KC", photo: "https://sleepercdn.com/content/nfl/players/thumb/10229.jpg", tier: 3, ecr: 27, adp: 28 },

    "devonta-smith": { id: "devonta-smith", name: "DeVonta Smith", position: "WR", team: "PHI", photo: "https://sleepercdn.com/content/nfl/players/thumb/7525.jpg", tier: 4, ecr: 28, adp: 29 },
    "jeremiyah-love": { id: "jeremiyah-love", name: "Jeremiyah Love", position: "RB", team: "ARI", photo: "https://sleepercdn.com/content/nfl/players/thumb/13287.jpg", tier: 4, ecr: 29, adp: 26 },
    "tetairoa-mcmillan": { id: "tetairoa-mcmillan", name: "Tetairoa McMillan", position: "WR", team: "CAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/12526.jpg", tier: 4, ecr: 30, adp: 41 },
    "tee-higgins": { id: "tee-higgins", name: "Tee Higgins", position: "WR", team: "CIN", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4239993.png", tier: 4, ecr: 31, adp: 37 },
    "kyren-williams": { id: "kyren-williams", name: "Kyren Williams", position: "RB", team: "LAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/8150.jpg", tier: 4, ecr: 32, adp: 30 },
    "zay-flowers": { id: "zay-flowers", name: "Zay Flowers", position: "WR", team: "BAL", photo: "https://sleepercdn.com/content/nfl/players/thumb/9997.jpg", tier: 4, ecr: 33, adp: 35 },
    "lamar-jackson": { id: "lamar-jackson", name: "Lamar Jackson", position: "QB", team: "BAL", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3916387.png", tier: 4, ecr: 34, adp: 43 },
    "drake-maye": { id: "drake-maye", name: "Drake Maye", position: "QB", team: "NE", photo: "https://sleepercdn.com/content/nfl/players/thumb/11564.jpg", tier: 4, ecr: 35, adp: 56 },
    "breece-hall": { id: "breece-hall", name: "Breece Hall", position: "RB", team: "NYJ", photo: "https://sleepercdn.com/content/nfl/players/thumb/8155.jpg", tier: 4, ecr: 36, adp: 31 },
    "malik-nabers": { id: "malik-nabers", name: "Malik Nabers", position: "WR", team: "NYG", photo: "https://sleepercdn.com/content/nfl/players/thumb/11632.jpg", tier: 4, ecr: 37, adp: 39 },
    "josh-jacobs": { id: "josh-jacobs", name: "Josh Jacobs", position: "RB", team: "GB", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4047365.png", tier: 4, ecr: 38, adp: 38 },
    "garrett-wilson": { id: "garrett-wilson", name: "Garrett Wilson", position: "WR", team: "NYJ", photo: "https://sleepercdn.com/content/nfl/players/thumb/8146.jpg", tier: 4, ecr: 39, adp: 44 },
    "colston-loveland": { id: "colston-loveland", name: "Colston Loveland", position: "TE", team: "CHI", photo: "https://sleepercdn.com/content/nfl/players/thumb/12517.jpg", tier: 4, ecr: 40, adp: 34 },
    "ladd-mcconkey": { id: "ladd-mcconkey", name: "Ladd McConkey", position: "WR", team: "LAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/11635.jpg", tier: 4, ecr: 41, adp: 42 },
    "javonte-williams": { id: "javonte-williams", name: "Javonte Williams", position: "RB", team: "DAL", photo: "https://sleepercdn.com/content/nfl/players/thumb/7588.jpg", tier: 4, ecr: 42, adp: 32 },
    "emeka-egbuka": { id: "emeka-egbuka", name: "Emeka Egbuka", position: "WR", team: "TB", photo: "https://sleepercdn.com/content/nfl/players/thumb/12514.jpg", tier: 4, ecr: 43, adp: 36 },
    "jaylen-waddle": { id: "jaylen-waddle", name: "Jaylen Waddle", position: "WR", team: "DEN", photo: "https://sleepercdn.com/content/nfl/players/thumb/7526.jpg", tier: 4, ecr: 44, adp: 51 },
    "travis-etienne-jr": { id: "travis-etienne-jr", name: "Travis Etienne Jr.", position: "RB", team: "NO", photo: "https://sleepercdn.com/content/nfl/players/thumb/7543.jpg", tier: 4, ecr: 45, adp: 33 },
    "joe-burrow": { id: "joe-burrow", name: "Joe Burrow", position: "QB", team: "CIN", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3915511.png", tier: 4, ecr: 46, adp: 49 },
    "terry-mclaurin": { id: "terry-mclaurin", name: "Terry McLaurin", position: "WR", team: "WAS", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3121422.png", tier: 4, ecr: 47, adp: 53 },

    "luther-burden-iii": { id: "luther-burden-iii", name: "Luther Burden III", position: "WR", team: "CHI", photo: "https://sleepercdn.com/content/nfl/players/thumb/12519.jpg", tier: 5, ecr: 48, adp: 45 },
    "davante-adams": { id: "davante-adams", name: "Davante Adams", position: "WR", team: "LAR", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/16800.png", tier: 5, ecr: 49, adp: 54 },
    "cam-skattebo": { id: "cam-skattebo", name: "Cam Skattebo", position: "RB", team: "NYG", photo: "https://sleepercdn.com/content/nfl/players/thumb/12481.jpg", tier: 5, ecr: 50, adp: 40 },
    "jameson-williams": { id: "jameson-williams", name: "Jameson Williams", position: "WR", team: "DET", photo: "https://sleepercdn.com/content/nfl/players/thumb/8148.jpg", tier: 5, ecr: 51, adp: 58 },
    "bucky-irving": { id: "bucky-irving", name: "Bucky Irving", position: "RB", team: "TB", photo: "https://sleepercdn.com/content/nfl/players/thumb/11584.jpg", tier: 5, ecr: 52, adp: 59 },
    "dandre-swift": { id: "dandre-swift", name: "D'Andre Swift", position: "RB", team: "CHI", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4259545.png", tier: 5, ecr: 53, adp: 52 },
    "quinshon-judkins": { id: "quinshon-judkins", name: "Quinshon Judkins", position: "RB", team: "CLE", photo: "https://sleepercdn.com/content/nfl/players/thumb/12512.jpg", tier: 5, ecr: 54, adp: 48 },
    "mike-evans": { id: "mike-evans", name: "Mike Evans", position: "WR", team: "SF", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/16737.png", tier: 5, ecr: 55, adp: 57 },
    "tyler-warren": { id: "tyler-warren", name: "Tyler Warren", position: "TE", team: "IND", photo: "https://sleepercdn.com/content/nfl/players/thumb/12518.jpg", tier: 5, ecr: 56, adp: 50 },
    "christian-watson": { id: "christian-watson", name: "Christian Watson", position: "WR", team: "GB", photo: "https://sleepercdn.com/content/nfl/players/thumb/8167.jpg", tier: 5, ecr: 57, adp: 64 },
    "treveyon-henderson": { id: "treveyon-henderson", name: "TreVeyon Henderson", position: "RB", team: "NE", photo: "https://sleepercdn.com/content/nfl/players/thumb/12529.jpg", tier: 5, ecr: 58, adp: 55 },
    "jayden-daniels": { id: "jayden-daniels", name: "Jayden Daniels", position: "QB", team: "WAS", photo: "https://sleepercdn.com/content/nfl/players/thumb/11566.jpg", tier: 5, ecr: 59, adp: 61 },
    "dj-moore": { id: "dj-moore", name: "DJ Moore", position: "WR", team: "BUF", photo: "https://sleepercdn.com/content/nfl/players/thumb/4961.jpg", tier: 5, ecr: 60, adp: 46 },
    "jalen-hurts": { id: "jalen-hurts", name: "Jalen Hurts", position: "QB", team: "PHI", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4040715.png", tier: 5, ecr: 61, adp: 66 },
    "rome-odunze": { id: "rome-odunze", name: "Rome Odunze", position: "WR", team: "CHI", photo: "https://sleepercdn.com/content/nfl/players/thumb/11620.jpg", tier: 5, ecr: 62, adp: 63 },
    "david-montgomery": { id: "david-montgomery", name: "David Montgomery", position: "RB", team: "HOU", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4035538.png", tier: 5, ecr: 63, adp: 47 },
    "bhayshul-tuten": { id: "bhayshul-tuten", name: "Bhayshul Tuten", position: "RB", team: "JAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/12490.jpg", tier: 5, ecr: 64, adp: 60 },
    "tucker-kraft": { id: "tucker-kraft", name: "Tucker Kraft", position: "TE", team: "GB", photo: "https://sleepercdn.com/content/nfl/players/thumb/9484.jpg", tier: 5, ecr: 65, adp: 68 },
    "carnell-tate": { id: "carnell-tate", name: "Carnell Tate", position: "WR", team: "TEN", photo: "https://sleepercdn.com/content/nfl/players/thumb/13279.jpg", tier: 5, ecr: 66, adp: 69 },
    "caleb-williams": { id: "caleb-williams", name: "Caleb Williams", position: "QB", team: "CHI", photo: "https://sleepercdn.com/content/nfl/players/thumb/11560.jpg", tier: 5, ecr: 67, adp: 65 },

    "justin-herbert": { id: "justin-herbert", name: "Justin Herbert", position: "QB", team: "LAC", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4038941.png", tier: 6, ecr: 68, adp: 82 },
    "jadarian-price": { id: "jadarian-price", name: "Jadarian Price", position: "RB", team: "SEA", photo: "https://sleepercdn.com/content/nfl/players/thumb/13286.jpg", tier: 6, ecr: 69, adp: 62 },
    "jaylen-warren": { id: "jaylen-warren", name: "Jaylen Warren", position: "RB", team: "PIT", photo: "https://sleepercdn.com/content/nfl/players/thumb/8228.jpg", tier: 6, ecr: 70, adp: 72 },
    "marvin-harrison-jr": { id: "marvin-harrison-jr", name: "Marvin Harrison Jr.", position: "WR", team: "ARI", photo: "https://sleepercdn.com/content/nfl/players/thumb/11628.jpg", tier: 6, ecr: 71, adp: 73 },
    "alec-pierce": { id: "alec-pierce", name: "Alec Pierce", position: "WR", team: "IND", photo: "https://sleepercdn.com/content/nfl/players/thumb/8142.jpg", tier: 6, ecr: 72, adp: 84 },
    "trevor-lawrence": { id: "trevor-lawrence", name: "Trevor Lawrence", position: "QB", team: "JAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/7523.jpg", tier: 6, ecr: 73, adp: 81 },
    "dk-metcalf": { id: "dk-metcalf", name: "DK Metcalf", position: "WR", team: "PIT", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4047650.png", tier: 6, ecr: 74, adp: 86 },
    "rhamondre-stevenson": { id: "rhamondre-stevenson", name: "Rhamondre Stevenson", position: "RB", team: "NE", photo: "https://sleepercdn.com/content/nfl/players/thumb/7611.jpg", tier: 6, ecr: 75, adp: 74 },
    "chuba-hubbard": { id: "chuba-hubbard", name: "Chuba Hubbard", position: "RB", team: "CAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/7594.jpg", tier: 6, ecr: 76, adp: 76 },
    "tony-pollard": { id: "tony-pollard", name: "Tony Pollard", position: "RB", team: "TEN", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3916148.png", tier: 6, ecr: 77, adp: 71 },
    "harold-fannin-jr": { id: "harold-fannin-jr", name: "Harold Fannin Jr.", position: "TE", team: "CLE", photo: "https://sleepercdn.com/content/nfl/players/thumb/12506.jpg", tier: 6, ecr: 78, adp: 77 },
    "courtland-sutton": { id: "courtland-sutton", name: "Courtland Sutton", position: "WR", team: "DEN", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3128429.png", tier: 6, ecr: 79, adp: 87 },
    "rico-dowdle": { id: "rico-dowdle", name: "Rico Dowdle", position: "RB", team: "PIT", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4038815.png", tier: 6, ecr: 80, adp: 85 },
    "brian-thomas-jr": { id: "brian-thomas-jr", name: "Brian Thomas Jr.", position: "WR", team: "JAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/11631.jpg", tier: 6, ecr: 81, adp: 67 },
    "dak-prescott": { id: "dak-prescott", name: "Dak Prescott", position: "QB", team: "DAL", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/2577417.png", tier: 6, ecr: 82, adp: 70 },
    "kyle-pitts-sr": { id: "kyle-pitts-sr", name: "Kyle Pitts Sr.", position: "TE", team: "ATL", photo: "https://sleepercdn.com/content/nfl/players/thumb/7553.jpg", tier: 6, ecr: 83, adp: 75 },
    "sam-laporta": { id: "sam-laporta", name: "Sam LaPorta", position: "TE", team: "DET", photo: "https://sleepercdn.com/content/nfl/players/thumb/10859.jpg", tier: 6, ecr: 84, adp: 80 },
    "jaxson-dart": { id: "jaxson-dart", name: "Jaxson Dart", position: "QB", team: "NYG", photo: "https://sleepercdn.com/content/nfl/players/thumb/12508.jpg", tier: 6, ecr: 85, adp: 91 },
    "chris-godwin-jr": { id: "chris-godwin-jr", name: "Chris Godwin Jr.", position: "WR", team: "TB", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3116165.png", tier: 6, ecr: 86, adp: 92 },
    "jordyn-tyson": { id: "jordyn-tyson", name: "Jordyn Tyson", position: "WR", team: "NO", photo: "https://sleepercdn.com/content/nfl/players/thumb/13281.jpg", tier: 6, ecr: 87, adp: 79 },
    "rj-harvey": { id: "rj-harvey", name: "RJ Harvey", position: "RB", team: "DEN", photo: "https://sleepercdn.com/content/nfl/players/thumb/12489.jpg", tier: 6, ecr: 88, adp: 83 },
    "parker-washington": { id: "parker-washington", name: "Parker Washington", position: "WR", team: "JAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/9487.jpg", tier: 6, ecr: 89, adp: 78 },
    "brock-purdy": { id: "brock-purdy", name: "Brock Purdy", position: "QB", team: "SF", photo: "https://sleepercdn.com/content/nfl/players/thumb/8183.jpg", tier: 6, ecr: 90, adp: 98 },
    "michael-wilson": { id: "michael-wilson", name: "Michael Wilson", position: "WR", team: "ARI", photo: "https://sleepercdn.com/content/nfl/players/thumb/10232.jpg", tier: 6, ecr: 91, adp: 89 },
    "kyle-monangai": { id: "kyle-monangai", name: "Kyle Monangai", position: "RB", team: "CHI", photo: "https://sleepercdn.com/content/nfl/players/thumb/12534.jpg", tier: 6, ecr: 92, adp: 90 },
    "makai-lemon": { id: "makai-lemon", name: "Makai Lemon", position: "WR", team: "PHI", photo: "https://sleepercdn.com/content/nfl/players/thumb/13294.jpg", tier: 6, ecr: 93, adp: 94 },
    "blake-corum": { id: "blake-corum", name: "Blake Corum", position: "RB", team: "LAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/11586.jpg", tier: 6, ecr: 94, adp: 99 },
    "michael-pittman-jr": { id: "michael-pittman-jr", name: "Michael Pittman Jr.", position: "WR", team: "PIT", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4035687.png", tier: 6, ecr: 95, adp: 105 },

    "jk-dobbins": { id: "jk-dobbins", name: "J.K. Dobbins", position: "RB", team: "DEN", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4241985.png", tier: 7, ecr: 96, adp: 97 },
    "patrick-mahomes-ii": { id: "patrick-mahomes-ii", name: "Patrick Mahomes II", position: "QB", team: "KC", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3139477.png", tier: 7, ecr: 97, adp: 95 },
    "jakobi-meyers": { id: "jakobi-meyers", name: "Jakobi Meyers", position: "WR", team: "JAC", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3916433.png", tier: 7, ecr: 98, adp: 112 },
    "bo-nix": { id: "bo-nix", name: "Bo Nix", position: "QB", team: "DEN", photo: "https://sleepercdn.com/content/nfl/players/thumb/11563.jpg", tier: 7, ecr: 99, adp: 104 },
    "kenny-gainwell": { id: "kenny-gainwell", name: "Kenny Gainwell", position: "RB", team: "TB", photo: "https://sleepercdn.com/content/nfl/players/thumb/7567.jpg", tier: 7, ecr: 100, adp: 102 },
    "quentin-johnston": { id: "quentin-johnston", name: "Quentin Johnston", position: "WR", team: "LAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/9754.jpg", tier: 7, ecr: 101, adp: 93 },
    "travis-kelce": { id: "travis-kelce", name: "Travis Kelce", position: "TE", team: "KC", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/15847.png", tier: 7, ecr: 102, adp: 107 },
    "matthew-stafford": { id: "matthew-stafford", name: "Matthew Stafford", position: "QB", team: "LAR", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/12483.png", tier: 7, ecr: 103, adp: 88 },
    "jordan-addison": { id: "jordan-addison", name: "Jordan Addison", position: "WR", team: "MIN", photo: "https://sleepercdn.com/content/nfl/players/thumb/9756.jpg", tier: 7, ecr: 104, adp: 108 },
    "ricky-pearsall": { id: "ricky-pearsall", name: "Ricky Pearsall", position: "WR", team: "SF", photo: "https://sleepercdn.com/content/nfl/players/thumb/11638.jpg", tier: 7, ecr: 105, adp: 111 },
    "wandale-robinson": { id: "wandale-robinson", name: "Wan'Dale Robinson", position: "WR", team: "TEN", photo: "https://sleepercdn.com/content/nfl/players/thumb/8126.jpg", tier: 7, ecr: 106, adp: 109 },
    "aaron-jones-sr": { id: "aaron-jones-sr", name: "Aaron Jones Sr.", position: "RB", team: "MIN", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3042519.png", tier: 7, ecr: 107, adp: 124 },
    "dalton-kincaid": { id: "dalton-kincaid", name: "Dalton Kincaid", position: "TE", team: "BUF", photo: "https://sleepercdn.com/content/nfl/players/thumb/10236.jpg", tier: 7, ecr: 108, adp: 114 },
    "rachaad-white": { id: "rachaad-white", name: "Rachaad White", position: "RB", team: "WAS", photo: "https://sleepercdn.com/content/nfl/players/thumb/8136.jpg", tier: 7, ecr: 109, adp: 113 },
    "jared-goff": { id: "jared-goff", name: "Jared Goff", position: "QB", team: "DET", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3046779.png", tier: 7, ecr: 110, adp: 100 },
    "jayden-reed": { id: "jayden-reed", name: "Jayden Reed", position: "WR", team: "GB", photo: "https://sleepercdn.com/content/nfl/players/thumb/10222.jpg", tier: 7, ecr: 111, adp: 103 },
    "george-kittle": { id: "george-kittle", name: "George Kittle", position: "TE", team: "SF", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3040151.png", tier: 7, ecr: 112, adp: 96 },
    "kyler-murray": { id: "kyler-murray", name: "Kyler Murray", position: "QB", team: "MIN", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3917315.png", tier: 7, ecr: 113, adp: 116 },
    "josh-downs": { id: "josh-downs", name: "Josh Downs", position: "WR", team: "IND", photo: "https://sleepercdn.com/content/nfl/players/thumb/9500.jpg", tier: 7, ecr: 114, adp: 110 },
    "jacory-croskey-merritt": { id: "jacory-croskey-merritt", name: "Jacory Croskey-Merritt", position: "RB", team: "WAS", photo: "https://sleepercdn.com/content/nfl/players/thumb/12533.jpg", tier: 7, ecr: 115, adp: 125 },
    "jake-ferguson": { id: "jake-ferguson", name: "Jake Ferguson", position: "TE", team: "DAL", photo: "https://sleepercdn.com/content/nfl/players/thumb/8110.jpg", tier: 7, ecr: 116, adp: 119 },
    "isaiah-likely": { id: "isaiah-likely", name: "Isaiah Likely", position: "TE", team: "NYG", photo: "https://sleepercdn.com/content/nfl/players/thumb/8131.jpg", tier: 7, ecr: 117, adp: 101 },
    "dallas-goedert": { id: "dallas-goedert", name: "Dallas Goedert", position: "TE", team: "PHI", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3121023.png", tier: 7, ecr: 118, adp: 117 },
    "jordan-mason": { id: "jordan-mason", name: "Jordan Mason", position: "RB", team: "MIN", photo: "https://sleepercdn.com/content/nfl/players/thumb/8408.jpg", tier: 7, ecr: 119, adp: 118 },
    "jordan-love": { id: "jordan-love", name: "Jordan Love", position: "QB", team: "GB", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4036378.png", tier: 7, ecr: 120, adp: 120 },
    "xavier-worthy": { id: "xavier-worthy", name: "Xavier Worthy", position: "WR", team: "KC", photo: "https://sleepercdn.com/content/nfl/players/thumb/11624.jpg", tier: 7, ecr: 121, adp: 115 },
    "baker-mayfield": { id: "baker-mayfield", name: "Baker Mayfield", position: "QB", team: "TB", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3052587.png", tier: 7, ecr: 122, adp: 122 },
    "jayden-higgins": { id: "jayden-higgins", name: "Jayden Higgins", position: "WR", team: "HOU", photo: "https://sleepercdn.com/content/nfl/players/thumb/12484.jpg", tier: 7, ecr: 123, adp: 133 },
    "tyrone-tracy-jr": { id: "tyrone-tracy-jr", name: "Tyrone Tracy Jr.", position: "RB", team: "NYG", photo: "https://sleepercdn.com/content/nfl/players/thumb/11655.jpg", tier: 7, ecr: 124, adp: 131 },
    "tyler-shough": { id: "tyler-shough", name: "Tyler Shough", position: "QB", team: "NO", photo: "https://sleepercdn.com/content/nfl/players/thumb/12545.jpg", tier: 7, ecr: 125, adp: 123 },
    "khalil-shakir": { id: "khalil-shakir", name: "Khalil Shakir", position: "WR", team: "BUF", photo: "https://sleepercdn.com/content/nfl/players/thumb/8134.jpg", tier: 7, ecr: 126, adp: 129 },
    "mark-andrews": { id: "mark-andrews", name: "Mark Andrews", position: "TE", team: "BAL", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3116365.png", tier: 7, ecr: 127, adp: 121 },
    "romeo-doubs": { id: "romeo-doubs", name: "Romeo Doubs", position: "WR", team: "NE", photo: "https://sleepercdn.com/content/nfl/players/thumb/8121.jpg", tier: 7, ecr: 128, adp: 127 },
    "chris-rodriguez-jr": { id: "chris-rodriguez-jr", name: "Chris Rodriguez Jr.", position: "RB", team: "JAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/10219.jpg", tier: 7, ecr: 129, adp: 136 },

    "kc-concepcion": { id: "kc-concepcion", name: "KC Concepcion", position: "WR", team: "CLE", photo: "https://sleepercdn.com/content/nfl/players/thumb/13298.jpg", tier: 8, ecr: 130, adp: 128 },
    "malik-willis": { id: "malik-willis", name: "Malik Willis", position: "QB", team: "MIA", photo: "https://sleepercdn.com/content/nfl/players/thumb/8161.jpg", tier: 8, ecr: 131, adp: 130 },
    "zach-charbonnet": { id: "zach-charbonnet", name: "Zach Charbonnet", position: "RB", team: "SEA", photo: "https://sleepercdn.com/content/nfl/players/thumb/9753.jpg", tier: 8, ecr: 132, adp: 142 },
    "tyler-allgeier": { id: "tyler-allgeier", name: "Tyler Allgeier", position: "RB", team: "ARI", photo: "https://sleepercdn.com/content/nfl/players/thumb/8132.jpg", tier: 8, ecr: 133, adp: 155 },
    "jonathon-brooks": { id: "jonathon-brooks", name: "Jonathon Brooks", position: "RB", team: "CAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/11583.jpg", tier: 8, ecr: 134, adp: 106 },
    "jalen-coker": { id: "jalen-coker", name: "Jalen Coker", position: "WR", team: "CAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/11646.jpg", tier: 8, ecr: 135, adp: 137 },
    "matthew-golden": { id: "matthew-golden", name: "Matthew Golden", position: "WR", team: "GB", photo: "https://sleepercdn.com/content/nfl/players/thumb/12501.jpg", tier: 8, ecr: 136, adp: 126 },
    "woody-marks": { id: "woody-marks", name: "Woody Marks", position: "RB", team: "HOU", photo: "https://sleepercdn.com/content/nfl/players/thumb/12474.jpg", tier: 8, ecr: 137, adp: 139 },
    "isiah-pacheco": { id: "isiah-pacheco", name: "Isiah Pacheco", position: "RB", team: "DET", photo: "https://sleepercdn.com/content/nfl/players/thumb/8205.jpg", tier: 8, ecr: 138, adp: 143 },
    "juwan-johnson": { id: "juwan-johnson", name: "Juwan Johnson", position: "TE", team: "NO", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3929645.png", tier: 8, ecr: 139, adp: 140 },
    "tyjae-spears": { id: "tyjae-spears", name: "Tyjae Spears", position: "RB", team: "TEN", photo: "https://sleepercdn.com/content/nfl/players/thumb/9508.jpg", tier: 8, ecr: 140, adp: 150 },
    "dylan-sampson": { id: "dylan-sampson", name: "Dylan Sampson", position: "RB", team: "CLE", photo: "https://sleepercdn.com/content/nfl/players/thumb/12469.jpg", tier: 8, ecr: 141, adp: 165 },
    "cj-stroud": { id: "cj-stroud", name: "C.J. Stroud", position: "QB", team: "HOU", photo: "https://sleepercdn.com/content/nfl/players/thumb/9758.jpg", tier: 8, ecr: 142, adp: 141 },
    "brenton-strange": { id: "brenton-strange", name: "Brenton Strange", position: "TE", team: "JAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/9480.jpg", tier: 8, ecr: 143, adp: 138 },
    "hunter-henry": { id: "hunter-henry", name: "Hunter Henry", position: "TE", team: "NE", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3046439.png", tier: 8, ecr: 144, adp: 147 },
    "oronde-gadsden-ii": { id: "oronde-gadsden-ii", name: "Oronde Gadsden II", position: "TE", team: "LAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/12493.jpg", tier: 8, ecr: 145, adp: 145 },
    "rashid-shaheed": { id: "rashid-shaheed", name: "Rashid Shaheed", position: "WR", team: "SEA", photo: "https://sleepercdn.com/content/nfl/players/thumb/8676.jpg", tier: 8, ecr: 146, adp: 135 },
    "keaton-mitchell": { id: "keaton-mitchell", name: "Keaton Mitchell", position: "RB", team: "LAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/9511.jpg", tier: 8, ecr: 147, adp: 148 },
    "sam-darnold": { id: "sam-darnold", name: "Sam Darnold", position: "QB", team: "SEA", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3912547.png", tier: 8, ecr: 148, adp: 132 },
    "cam-ward": { id: "cam-ward", name: "Cam Ward", position: "QB", team: "TEN", photo: "https://sleepercdn.com/content/nfl/players/thumb/12522.jpg", tier: 8, ecr: 149, adp: 144 },
    "brian-robinson-jr": { id: "brian-robinson-jr", name: "Brian Robinson Jr.", position: "RB", team: "ATL", photo: "https://sleepercdn.com/content/nfl/players/thumb/8154.jpg", tier: 8, ecr: 150, adp: 162 },
    "alvin-kamara": { id: "alvin-kamara", name: "Alvin Kamara", position: "RB", team: "NO", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3054850.png", tier: 8, ecr: 151, adp: 161 },
    "omar-cooper-jr": { id: "omar-cooper-jr", name: "Omar Cooper Jr.", position: "WR", team: "NYJ", photo: "https://sleepercdn.com/content/nfl/players/thumb/13276.jpg", tier: 8, ecr: 152, adp: 159 },
    "jerry-jeudy": { id: "jerry-jeudy", name: "Jerry Jeudy", position: "WR", team: "CLE", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4241463.png", tier: 8, ecr: 153, adp: 171 },
    "tank-bigsby": { id: "tank-bigsby", name: "Tank Bigsby", position: "RB", team: "PHI", photo: "https://sleepercdn.com/content/nfl/players/thumb/9225.jpg", tier: 8, ecr: 154, adp: 166 },
    "chig-okonkwo": { id: "chig-okonkwo", name: "Chig Okonkwo", position: "TE", team: "WAS", photo: "https://sleepercdn.com/content/nfl/players/thumb/8210.jpg", tier: 8, ecr: 155, adp: 134 },
    "jauan-jennings": { id: "jauan-jennings", name: "Jauan Jennings", position: "WR", team: "MIN", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3886598.png", tier: 8, ecr: 156, adp: 158 },
    "jonah-coleman": { id: "jonah-coleman", name: "Jonah Coleman", position: "RB", team: "DEN", photo: "https://sleepercdn.com/content/nfl/players/thumb/13345.jpg", tier: 8, ecr: 157, adp: 154 },
    "denzel-boston": { id: "denzel-boston", name: "Denzel Boston", position: "WR", team: "CLE", photo: "https://sleepercdn.com/content/nfl/players/thumb/13346.jpg", tier: 8, ecr: 158, adp: 160 },
    "daniel-jones": { id: "daniel-jones", name: "Daniel Jones", position: "QB", team: "IND", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3917792.png", tier: 8, ecr: 159, adp: 149 },
    "jalen-mcmillan": { id: "jalen-mcmillan", name: "Jalen McMillan", position: "WR", team: "TB", photo: "https://sleepercdn.com/content/nfl/players/thumb/11618.jpg", tier: 8, ecr: 160, adp: 152 },
    "dalton-schultz": { id: "dalton-schultz", name: "Dalton Schultz", position: "TE", team: "HOU", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3117256.png", tier: 8, ecr: 161, adp: 163 },
    "adonai-mitchell": { id: "adonai-mitchell", name: "Adonai Mitchell", position: "WR", team: "NYJ", photo: "https://sleepercdn.com/content/nfl/players/thumb/11625.jpg", tier: 8, ecr: 162, adp: 181 },
    "travis-hunter": { id: "travis-hunter", name: "Travis Hunter", position: "WR", team: "JAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/12530.jpg", tier: 8, ecr: 163, adp: 205 },
    "bryce-young": { id: "bryce-young", name: "Bryce Young", position: "QB", team: "CAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/9228.jpg", tier: 8, ecr: 164, adp: 157 },
    "braelon-allen": { id: "braelon-allen", name: "Braelon Allen", position: "RB", team: "NYJ", photo: "https://sleepercdn.com/content/nfl/players/thumb/11576.jpg", tier: 8, ecr: 165, adp: 193 },

    "kayshon-boutte": { id: "kayshon-boutte", name: "Kayshon Boutte", position: "WR", team: "NE", photo: "https://sleepercdn.com/content/nfl/players/thumb/9504.jpg", tier: 9, ecr: 166, adp: 199 },
    "tre-tucker": { id: "tre-tucker", name: "Tre Tucker", position: "WR", team: "LV", photo: "https://sleepercdn.com/content/nfl/players/thumb/10213.jpg", tier: 9, ecr: 167, adp: 167 },
    "kenyon-sadiq": { id: "kenyon-sadiq", name: "Kenyon Sadiq", position: "TE", team: "NYJ", photo: "https://sleepercdn.com/content/nfl/players/thumb/13330.jpg", tier: 9, ecr: 168, adp: 153 },
    "tre-harris": { id: "tre-harris", name: "Tre' Harris", position: "WR", team: "LAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/12509.jpg", tier: 9, ecr: 169, adp: 185 },
    "ryan-flournoy": { id: "ryan-flournoy", name: "Ryan Flournoy", position: "WR", team: "DAL", photo: "https://sleepercdn.com/content/nfl/players/thumb/11783.jpg", tier: 9, ecr: 170, adp: 183 },
    "troy-franklin": { id: "troy-franklin", name: "Troy Franklin", position: "WR", team: "DEN", photo: "https://sleepercdn.com/content/nfl/players/thumb/11627.jpg", tier: 9, ecr: 171, adp: 220 },
    "tj-hockenson": { id: "tj-hockenson", name: "T.J. Hockenson", position: "TE", team: "MIN", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4036133.png", tier: 9, ecr: 172, adp: 156 },
    "aj-barner": { id: "aj-barner", name: "AJ Barner", position: "TE", team: "SEA", photo: "https://sleepercdn.com/content/nfl/players/thumb/11603.jpg", tier: 9, ecr: 173, adp: 175 },
    "emanuel-wilson": { id: "emanuel-wilson", name: "Emanuel Wilson", position: "RB", team: "SEA", photo: "https://sleepercdn.com/content/nfl/players/thumb/11435.jpg", tier: 9, ecr: 174, adp: 212 },
    "isaac-teslaa": { id: "isaac-teslaa", name: "Isaac TeSlaa", position: "WR", team: "DET", photo: "https://sleepercdn.com/content/nfl/players/thumb/12535.jpg", tier: 9, ecr: 175, adp: 178 },
    "james-conner": { id: "james-conner", name: "James Conner", position: "RB", team: "ARI", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3045147.png", tier: 9, ecr: 176, adp: 221 },
    "calvin-ridley": { id: "calvin-ridley", name: "Calvin Ridley", position: "WR", team: "TEN", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3925357.png", tier: 9, ecr: 177, adp: 176 },
    "kimani-vidal": { id: "kimani-vidal", name: "Kimani Vidal", position: "RB", team: "LAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/11647.jpg", tier: 9, ecr: 178, adp: 208 },
    "stefon-diggs": { id: "stefon-diggs", name: "Stefon Diggs", position: "WR", team: "FA", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/2976212.png", tier: 9, ecr: 179, adp: 146 },
    "jaylin-noel": { id: "jaylin-noel", name: "Jaylin Noel", position: "WR", team: "HOU", photo: "https://sleepercdn.com/content/nfl/players/thumb/12536.jpg", tier: 9, ecr: 180, adp: 235 },
    "hou-dst": { id: "hou-dst", name: "Houston Texans", position: "DST", team: "HOU", photo: dstLogo("hou"), tier: 9, ecr: 181 },
    "ray-davis": { id: "ray-davis", name: "Ray Davis", position: "RB", team: "BUF", photo: "https://sleepercdn.com/content/nfl/players/thumb/11575.jpg", tier: 9, ecr: 182, adp: 200 },
    "jacoby-brissett": { id: "jacoby-brissett", name: "Jacoby Brissett", position: "QB", team: "ARI", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/2578570.png", tier: 9, ecr: 183, adp: 169 },
    "pat-bryant": { id: "pat-bryant", name: "Pat Bryant", position: "WR", team: "DEN", photo: "https://sleepercdn.com/content/nfl/players/thumb/12492.jpg", tier: 9, ecr: 184, adp: 240 },
    "emmett-johnson": { id: "emmett-johnson", name: "Emmett Johnson", position: "RB", team: "KC", photo: "https://sleepercdn.com/content/nfl/players/thumb/13337.jpg", tier: 9, ecr: 185, adp: 189 },
    "darnell-mooney": { id: "darnell-mooney", name: "Darnell Mooney", position: "WR", team: "NYG", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4040655.png", tier: 9, ecr: 186, adp: 218 },
    "gunnar-helm": { id: "gunnar-helm", name: "Gunnar Helm", position: "TE", team: "TEN", photo: "https://sleepercdn.com/content/nfl/players/thumb/12502.jpg", tier: 9, ecr: 187, adp: 179 },
    "deebo-samuel-sr": { id: "deebo-samuel-sr", name: "Deebo Samuel Sr.", position: "WR", team: "FA", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3126486.png", tier: 9, ecr: 188, adp: 172 },
    "mike-washington-jr": { id: "mike-washington-jr", name: "Mike Washington Jr.", position: "RB", team: "LV", photo: "https://sleepercdn.com/content/nfl/players/thumb/13305.jpg", tier: 9, ecr: 189, adp: 190 },
    "sean-tucker": { id: "sean-tucker", name: "Sean Tucker", position: "RB", team: "TB", photo: "https://sleepercdn.com/content/nfl/players/thumb/9506.jpg", tier: 9, ecr: 190, adp: 184 },
    "jalen-nailor": { id: "jalen-nailor", name: "Jalen Nailor", position: "WR", team: "LV", photo: "https://sleepercdn.com/content/nfl/players/thumb/8180.jpg", tier: 9, ecr: 191, adp: 151 },
    "dezhaun-stribling": { id: "dezhaun-stribling", name: "De'Zhaun Stribling", position: "WR", team: "SF", photo: "https://sleepercdn.com/content/nfl/players/thumb/13417.jpg", tier: 9, ecr: 192, adp: 192 },
    "den-dst": { id: "den-dst", name: "Denver Broncos", position: "DST", team: "DEN", photo: dstLogo("den"), tier: 9, ecr: 193 },
    "sea-dst": { id: "sea-dst", name: "Seattle Seahawks", position: "DST", team: "SEA", photo: dstLogo("sea"), tier: 9, ecr: 194 },
    "malik-washington": { id: "malik-washington", name: "Malik Washington", position: "WR", team: "MIA", photo: "https://sleepercdn.com/content/nfl/players/thumb/11610.jpg", tier: 9, ecr: 195, adp: 177 },
    "lar-dst": { id: "lar-dst", name: "Los Angeles Rams", position: "DST", team: "LAR", photo: dstLogo("lar"), tier: 9, ecr: 196 },
    "pat-freiermuth": { id: "pat-freiermuth", name: "Pat Freiermuth", position: "TE", team: "PIT", photo: "https://sleepercdn.com/content/nfl/players/thumb/7600.jpg", tier: 9, ecr: 197, adp: 194 },
    "david-njoku": { id: "david-njoku", name: "David Njoku", position: "TE", team: "LAC", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3123076.png", tier: 9, ecr: 198, adp: 182 },
    "phi-dst": { id: "phi-dst", name: "Philadelphia Eagles", position: "DST", team: "PHI", photo: dstLogo("phi"), tier: 9, ecr: 199 },
    "terrance-ferguson": { id: "terrance-ferguson", name: "Terrance Ferguson", position: "TE", team: "LAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/12487.jpg", tier: 9, ecr: 200, adp: 198 },
    "nicholas-singleton": { id: "nicholas-singleton", name: "Nicholas Singleton", position: "RB", team: "TEN", photo: "https://sleepercdn.com/content/nfl/players/thumb/13288.jpg", tier: 9, ecr: 201, adp: 188 },
    "pit-dst": { id: "pit-dst", name: "Pittsburgh Steelers", position: "DST", team: "PIT", photo: dstLogo("pit"), tier: 9, ecr: 202 },
    "jac-dst": { id: "jac-dst", name: "Jacksonville Jaguars", position: "DST", team: "JAC", photo: dstLogo("jac"), tier: 9, ecr: 203 },
    "kaimi-fairbairn": { id: "kaimi-fairbairn", name: "Ka'imi Fairbairn", position: "K", team: "HOU", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/2971573.png", tier: 9, ecr: 204 },
    "ted-hurst-iii": { id: "ted-hurst-iii", name: "Ted Hurst III", position: "WR", team: "TB", photo: "https://sleepercdn.com/content/nfl/players/thumb/13317.jpg", tier: 9, ecr: 205, adp: 228 },
    "chimere-dike": { id: "chimere-dike", name: "Chimere Dike", position: "WR", team: "TEN", photo: "https://sleepercdn.com/content/nfl/players/thumb/12540.jpg", tier: 9, ecr: 206, adp: 249 },
    "cameron-dicker": { id: "cameron-dicker", name: "Cameron Dicker", position: "K", team: "LAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/8259.jpg", tier: 9, ecr: 207 },
    "brandon-aubrey": { id: "brandon-aubrey", name: "Brandon Aubrey", position: "K", team: "DAL", photo: "https://sleepercdn.com/content/nfl/players/thumb/11533.jpg", tier: 9, ecr: 208 },
    "ne-dst": { id: "ne-dst", name: "New England Patriots", position: "DST", team: "NE", photo: dstLogo("ne"), tier: 9, ecr: 209 },
    "min-dst": { id: "min-dst", name: "Minnesota Vikings", position: "DST", team: "MIN", photo: dstLogo("min"), tier: 9, ecr: 210 },
    "cade-otton": { id: "cade-otton", name: "Cade Otton", position: "TE", team: "TB", photo: "https://sleepercdn.com/content/nfl/players/thumb/8111.jpg", tier: 9, ecr: 211, adp: 180 },

    "cam-little": { id: "cam-little", name: "Cam Little", position: "K", team: "JAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/11786.jpg", tier: 10, ecr: 212 },
    "dontayvion-wicks": { id: "dontayvion-wicks", name: "Dontayvion Wicks", position: "WR", team: "PHI", photo: "https://sleepercdn.com/content/nfl/players/thumb/9486.jpg", tier: 10, ecr: 213, adp: 211 },
    "jason-myers": { id: "jason-myers", name: "Jason Myers", position: "K", team: "SEA", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/2473037.png", tier: 10, ecr: 214 },
    "brandon-aiyuk": { id: "brandon-aiyuk", name: "Brandon Aiyuk", position: "WR", team: "SF", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4360438.png", tier: 10, ecr: 215, adp: 191 },
    "germie-bernard": { id: "germie-bernard", name: "Germie Bernard", position: "WR", team: "PIT", photo: "https://sleepercdn.com/content/nfl/players/thumb/13274.jpg", tier: 10, ecr: 216, adp: 203 },
    "lac-dst": { id: "lac-dst", name: "Los Angeles Chargers", position: "DST", team: "LAC", photo: dstLogo("lac"), tier: 10, ecr: 217 },
    "antonio-williams": { id: "antonio-williams", name: "Antonio Williams", position: "WR", team: "WAS", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4040629.png", tier: 10, ecr: 218, adp: 173 },
    "kaytron-allen": { id: "kaytron-allen", name: "Kaytron Allen", position: "RB", team: "WAS", photo: "https://sleepercdn.com/content/nfl/players/thumb/13405.jpg", tier: 10, ecr: 219, adp: 197 },
    "jaylen-wright": { id: "jaylen-wright", name: "Jaylen Wright", position: "RB", team: "MIA", photo: "https://sleepercdn.com/content/nfl/players/thumb/11643.jpg", tier: 10, ecr: 220, adp: 226 },
    "tank-dell": { id: "tank-dell", name: "Tank Dell", position: "WR", team: "HOU", photo: "https://sleepercdn.com/content/nfl/players/thumb/9502.jpg", tier: 10, ecr: 221, adp: 195 },
    "eddy-pineiro": { id: "eddy-pineiro", name: "Eddy Pineiro", position: "K", team: "SF", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4034949.png", tier: 10, ecr: 222 },
    "rashod-bateman": { id: "rashod-bateman", name: "Rashod Bateman", position: "WR", team: "BAL", photo: "https://sleepercdn.com/content/nfl/players/thumb/7571.jpg", tier: 10, ecr: 223, adp: 236 },
    "ollie-gordon-ii": { id: "ollie-gordon-ii", name: "Ollie Gordon II", position: "RB", team: "MIA", photo: "https://sleepercdn.com/content/nfl/players/thumb/12495.jpg", tier: 10, ecr: 224, adp: 261 },
    "tyler-loop": { id: "tyler-loop", name: "Tyler Loop", position: "K", team: "BAL", photo: "https://sleepercdn.com/content/nfl/players/thumb/12711.jpg", tier: 10, ecr: 225 },
    "aaron-rodgers": { id: "aaron-rodgers", name: "Aaron Rodgers", position: "QB", team: "PIT", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/8439.png", tier: 10, ecr: 226, adp: 164 },
    "geno-smith": { id: "geno-smith", name: "Geno Smith", position: "QB", team: "NYJ", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/15864.png", tier: 10, ecr: 227, adp: 174 },
    "cooper-kupp": { id: "cooper-kupp", name: "Cooper Kupp", position: "WR", team: "SEA", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/2977187.png", tier: 10, ecr: 228, adp: 213 },
    "kc-dst": { id: "kc-dst", name: "Kansas City Chiefs", position: "DST", team: "KC", photo: dstLogo("kc"), tier: 10, ecr: 229 },
    "bal-dst": { id: "bal-dst", name: "Baltimore Ravens", position: "DST", team: "BAL", photo: dstLogo("bal"), tier: 10, ecr: 230 },
    "colby-parkinson": { id: "colby-parkinson", name: "Colby Parkinson", position: "TE", team: "LAR", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4242557.png", tier: 10, ecr: 231, adp: 222 },
    "zachariah-branch": { id: "zachariah-branch", name: "Zachariah Branch", position: "WR", team: "ATL", photo: "https://sleepercdn.com/content/nfl/players/thumb/13320.jpg", tier: 10, ecr: 232, adp: 186 },
    "gb-dst": { id: "gb-dst", name: "Green Bay Packers", position: "DST", team: "GB", photo: dstLogo("gb"), tier: 10, ecr: 233 },
    "cairo-santos": { id: "cairo-santos", name: "Cairo Santos", position: "K", team: "CHI", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/17427.png", tier: 10, ecr: 234 },
    "marshawn-lloyd": { id: "marshawn-lloyd", name: "MarShawn Lloyd", position: "RB", team: "GB", photo: "https://sleepercdn.com/content/nfl/players/thumb/11581.jpg", tier: 10, ecr: 235, adp: 202 },
    "jake-bates": { id: "jake-bates", name: "Jake Bates", position: "K", team: "DET", photo: "https://sleepercdn.com/content/nfl/players/thumb/11539.jpg", tier: 10, ecr: 236 },
    "evan-mcpherson": { id: "evan-mcpherson", name: "Evan McPherson", position: "K", team: "CIN", photo: "https://sleepercdn.com/content/nfl/players/thumb/7839.jpg", tier: 10, ecr: 237 },
    "seth-mcgowan": { id: "seth-mcgowan", name: "Seth McGowan", position: "RB", team: "IND", photo: "https://sleepercdn.com/content/nfl/players/thumb/13424.jpg", tier: 10, ecr: 238, adp: 308 },
    "elic-ayomanor": { id: "elic-ayomanor", name: "Elic Ayomanor", position: "WR", team: "TEN", photo: "https://sleepercdn.com/content/nfl/players/thumb/12499.jpg", tier: 10, ecr: 239, adp: 283 },
    "andy-borregales": { id: "andy-borregales", name: "Andy Borregales", position: "K", team: "NE", photo: "https://sleepercdn.com/content/nfl/players/thumb/12713.jpg", tier: 10, ecr: 240 },
    "fernando-mendoza": { id: "fernando-mendoza", name: "Fernando Mendoza", position: "QB", team: "LV", photo: "https://sleepercdn.com/content/nfl/players/thumb/13269.jpg", tier: 10, ecr: 241, adp: 168 },
    "det-dst": { id: "det-dst", name: "Detroit Lions", position: "DST", team: "DET", photo: dstLogo("det"), tier: 10, ecr: 242 },
    "justice-hill": { id: "justice-hill", name: "Justice Hill", position: "RB", team: "BAL", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4038441.png", tier: 10, ecr: 243, adp: 209 },
    "buf-dst": { id: "buf-dst", name: "Buffalo Bills", position: "DST", team: "BUF", photo: dstLogo("buf"), tier: 10, ecr: 244 },
    "jack-bech": { id: "jack-bech", name: "Jack Bech", position: "WR", team: "LV", photo: "https://sleepercdn.com/content/nfl/players/thumb/12483.jpg", tier: 10, ecr: 245, adp: 251 },
    "cle-dst": { id: "cle-dst", name: "Cleveland Browns", position: "DST", team: "CLE", photo: dstLogo("cle"), tier: 10, ecr: 246 },
    "eli-stowers": { id: "eli-stowers", name: "Eli Stowers", position: "TE", team: "PHI", photo: "https://sleepercdn.com/content/nfl/players/thumb/13349.jpg", tier: 10, ecr: 247, adp: 201 },
    "chase-mclaughlin": { id: "chase-mclaughlin", name: "Chase McLaughlin", position: "K", team: "TB", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3150744.png", tier: 10, ecr: 248 },
    "keon-coleman": { id: "keon-coleman", name: "Keon Coleman", position: "WR", team: "BUF", photo: "https://sleepercdn.com/content/nfl/players/thumb/11637.jpg", tier: 10, ecr: 249, adp: 227 },
    "harrison-mevis": { id: "harrison-mevis", name: "Harrison Mevis", position: "K", team: "LAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/12015.jpg", tier: 10, ecr: 250 },
    "malik-davis": { id: "malik-davis", name: "Malik Davis", position: "RB", team: "DAL", photo: "https://sleepercdn.com/content/nfl/players/thumb/8800.jpg", tier: 10, ecr: 251, adp: 279 },
    "elijah-sarratt": { id: "elijah-sarratt", name: "Elijah Sarratt", position: "WR", team: "BAL", photo: "https://sleepercdn.com/content/nfl/players/thumb/13268.jpg", tier: 10, ecr: 252, adp: 237 },
    "christian-kirk": { id: "christian-kirk", name: "Christian Kirk", position: "WR", team: "SF", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3895856.png", tier: 10, ecr: 253, adp: 210 },
    "tory-horton": { id: "tory-horton", name: "Tory Horton", position: "WR", team: "SEA", photo: "https://sleepercdn.com/content/nfl/players/thumb/12497.jpg", tier: 10, ecr: 254, adp: 245 },
    "oscar-delp": { id: "oscar-delp", name: "Oscar Delp", position: "TE", team: "NO", photo: "https://sleepercdn.com/content/nfl/players/thumb/13319.jpg", tier: 10, ecr: 255, adp: 276 },
    "evan-engram": { id: "evan-engram", name: "Evan Engram", position: "TE", team: "DEN", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3051876.png", tier: 10, ecr: 256, adp: 225 },
    "tyreek-hill": { id: "tyreek-hill", name: "Tyreek Hill", position: "WR", team: "FA", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3116406.png", tier: 10, ecr: 257, adp: 187 },
    "harrison-butker": { id: "harrison-butker", name: "Harrison Butker", position: "K", team: "KC", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3055899.png", tier: 10, ecr: 258 },
    "ty-johnson": { id: "ty-johnson", name: "Ty Johnson", position: "RB", team: "BUF", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3915411.png", tier: 10, ecr: 259, adp: 241 },
    "chris-brooks": { id: "chris-brooks", name: "Chris Brooks", position: "RB", team: "GB", photo: "https://sleepercdn.com/content/nfl/players/thumb/11370.jpg", tier: 10, ecr: 260, adp: 253 },
    "chris-boswell": { id: "chris-boswell", name: "Chris Boswell", position: "K", team: "PIT", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/17372.png", tier: 10, ecr: 261 },
    "jordan-james": { id: "jordan-james", name: "Jordan James", position: "RB", team: "SF", photo: "https://sleepercdn.com/content/nfl/players/thumb/12467.jpg", tier: 10, ecr: 262, adp: 207 },
    "chris-bell": { id: "chris-bell", name: "Chris Bell", position: "WR", team: "MIA", photo: "https://sleepercdn.com/content/nfl/players/thumb/13311.jpg", tier: 10, ecr: 263, adp: 224 },
    "malachi-fields": { id: "malachi-fields", name: "Malachi Fields", position: "WR", team: "NYG", photo: "https://sleepercdn.com/content/nfl/players/thumb/13285.jpg", tier: 10, ecr: 264, adp: 206 },
    "dj-giddens": { id: "dj-giddens", name: "DJ Giddens", position: "RB", team: "IND", photo: "https://sleepercdn.com/content/nfl/players/thumb/12471.jpg", tier: 10, ecr: 265, adp: 243 },
    "devin-neal": { id: "devin-neal", name: "Devin Neal", position: "RB", team: "NO", photo: "https://sleepercdn.com/content/nfl/players/thumb/12476.jpg", tier: 10, ecr: 266, adp: 281 },
    "jaydon-blue": { id: "jaydon-blue", name: "Jaydon Blue", position: "RB", team: "DAL", photo: "https://sleepercdn.com/content/nfl/players/thumb/12457.jpg", tier: 10, ecr: 267, adp: 204 },
    "samaje-perine": { id: "samaje-perine", name: "Samaje Perine", position: "RB", team: "CIN", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3116389.png", tier: 10, ecr: 268, adp: 238 },
    "tua-tagovailoa": { id: "tua-tagovailoa", name: "Tua Tagovailoa", position: "QB", team: "ATL", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4241479.png", tier: 10, ecr: 269, adp: 196 },
    "kaleb-johnson": { id: "kaleb-johnson", name: "Kaleb Johnson", position: "RB", team: "PIT", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/2582406.png", tier: 10, ecr: 270, adp: 270 },
    "michael-penix-jr": { id: "michael-penix-jr", name: "Michael Penix Jr.", position: "QB", team: "ATL", photo: "https://sleepercdn.com/content/nfl/players/thumb/11559.jpg", tier: 10, ecr: 271, adp: 219 },
    "demond-claiborne": { id: "demond-claiborne", name: "Demond Claiborne", position: "RB", team: "MIN", photo: "https://sleepercdn.com/content/nfl/players/thumb/13347.jpg", tier: 10, ecr: 272, adp: 214 },
    "george-holani": { id: "george-holani", name: "George Holani", position: "RB", team: "SEA", photo: "https://sleepercdn.com/content/nfl/players/thumb/12048.jpg", tier: 10, ecr: 273, adp: 215 },

    "marvin-mims-jr": { id: "marvin-mims-jr", name: "Marvin Mims Jr.", position: "WR", team: "DEN", photo: "https://sleepercdn.com/content/nfl/players/thumb/9494.jpg", tier: 11, ecr: 274, adp: 298 },
    "tyquan-thornton": { id: "tyquan-thornton", name: "Tyquan Thornton", position: "WR", team: "KC", photo: "https://sleepercdn.com/content/nfl/players/thumb/8188.jpg", tier: 11, ecr: 275, adp: 234 },
    "trey-benson": { id: "trey-benson", name: "Trey Benson", position: "RB", team: "ARI", photo: "https://sleepercdn.com/content/nfl/players/thumb/11589.jpg", tier: 11, ecr: 276, adp: 340 },
    "chris-brazzell-ii": { id: "chris-brazzell-ii", name: "Chris Brazzell II", position: "WR", team: "CAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/13353.jpg", tier: 11, ecr: 277, adp: 233 },
    "wil-lutz": { id: "wil-lutz", name: "Wil Lutz", position: "K", team: "DEN", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/2985659.png", tier: 11, ecr: 278 },
    "mason-taylor": { id: "mason-taylor", name: "Mason Taylor", position: "TE", team: "NYJ", photo: "https://sleepercdn.com/content/nfl/players/thumb/12498.jpg", tier: 11, ecr: 279, adp: 265 },
    "theo-johnson": { id: "theo-johnson", name: "Theo Johnson", position: "TE", team: "NYG", photo: "https://sleepercdn.com/content/nfl/players/thumb/11597.jpg", tier: 11, ecr: 280, adp: 247 },
    "isaiah-davis": { id: "isaiah-davis", name: "Isaiah Davis", position: "RB", team: "NYJ", photo: "https://sleepercdn.com/content/nfl/players/thumb/11571.jpg", tier: 11, ecr: 281, adp: 299 },
    "devaughn-vele": { id: "devaughn-vele", name: "Devaughn Vele", position: "WR", team: "NO", photo: "https://sleepercdn.com/content/nfl/players/thumb/11834.jpg", tier: 11, ecr: 282, adp: 231 },
    "lequint-allen-jr": { id: "lequint-allen-jr", name: "LeQuint Allen Jr.", position: "RB", team: "JAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/12544.jpg", tier: 11, ecr: 283, adp: 262 },
    "shedeur-sanders": { id: "shedeur-sanders", name: "Shedeur Sanders", position: "QB", team: "CLE", photo: "https://sleepercdn.com/content/nfl/players/thumb/12524.jpg", tier: 11, ecr: 284, adp: 217 },
    "devin-singletary": { id: "devin-singletary", name: "Devin Singletary", position: "RB", team: "NYG", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4040761.png", tier: 11, ecr: 285, adp: 258 },
    "atl-dst": { id: "atl-dst", name: "Atlanta Falcons", position: "DST", team: "ATL", photo: dstLogo("atl"), tier: 11, ecr: 286 },
    "darius-slayton": { id: "darius-slayton", name: "Darius Slayton", position: "WR", team: "NYG", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3916945.png", tier: 11, ecr: 287, adp: 266 },
    "xavier-legette": { id: "xavier-legette", name: "Xavier Legette", position: "WR", team: "CAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/11626.jpg", tier: 11, ecr: 288, adp: 285 },
    "will-reichard": { id: "will-reichard", name: "Will Reichard", position: "K", team: "MIN", photo: "https://sleepercdn.com/content/nfl/players/thumb/11792.jpg", tier: 11, ecr: 289 },
    "brashard-smith": { id: "brashard-smith", name: "Brashard Smith", position: "RB", team: "KC", photo: "https://sleepercdn.com/content/nfl/players/thumb/12455.jpg", tier: 11, ecr: 290, adp: 386 },
    "emari-demercado": { id: "emari-demercado", name: "Emari Demercado", position: "RB", team: "KC", photo: "https://sleepercdn.com/content/nfl/players/thumb/11199.jpg", tier: 11, ecr: 291, adp: 257 },
    "kirk-cousins": { id: "kirk-cousins", name: "Kirk Cousins", position: "QB", team: "LV", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/14880.png", tier: 11, ecr: 292, adp: 230 },
    "kendre-miller": { id: "kendre-miller", name: "Kendre Miller", position: "RB", team: "NO", photo: "https://sleepercdn.com/content/nfl/players/thumb/9757.jpg", tier: 11, ecr: 293 },
    "greg-dulcich": { id: "greg-dulcich", name: "Greg Dulcich", position: "TE", team: "MIA", photo: "https://sleepercdn.com/content/nfl/players/thumb/8172.jpg", tier: 11, ecr: 294, adp: 170 },
    "kyle-williams": { id: "kyle-williams", name: "Kyle Williams", position: "WR", team: "NE", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/9720.png", tier: 11, ecr: 295, adp: 290 },
    "keenan-allen": { id: "keenan-allen", name: "Keenan Allen", position: "WR", team: "LAC", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/15818.png", tier: 11, ecr: 296, adp: 244 },
    "hollywood-brown": { id: "hollywood-brown", name: "Hollywood Brown", position: "WR", team: "PHI", photo: PLACEHOLDER_PHOTO, tier: 11, ecr: 297, adp: 256 },
    "mack-hollins": { id: "mack-hollins", name: "Mack Hollins", position: "WR", team: "NE", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/2991662.png", tier: 11, ecr: 298, adp: 316 },
    "jerome-ford": { id: "jerome-ford", name: "Jerome Ford", position: "RB", team: "WAS", photo: "https://sleepercdn.com/content/nfl/players/thumb/8143.jpg", tier: 11, ecr: 299, adp: 363 },
    "najee-harris": { id: "najee-harris", name: "Najee Harris", position: "RB", team: "LAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/7528.jpg", tier: 11, ecr: 300, adp: 278 },
    "deshaun-watson": { id: "deshaun-watson", name: "Deshaun Watson", position: "QB", team: "CLE", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3122840.png", tier: 11, ecr: 301, adp: 216 },
    "kaelon-black": { id: "kaelon-black", name: "Kaelon Black", position: "RB", team: "SF", photo: "https://sleepercdn.com/content/nfl/players/thumb/13414.jpg", tier: 11, ecr: 302, adp: 232 },
    "sf-dst": { id: "sf-dst", name: "San Francisco 49ers", position: "DST", team: "SF", photo: dstLogo("sf"), tier: 11, ecr: 303 },
    "adam-randall": { id: "adam-randall", name: "Adam Randall", position: "RB", team: "BAL", photo: "https://sleepercdn.com/content/nfl/players/thumb/13302.jpg", tier: 11, ecr: 304, adp: 260 },
    "mike-gesicki": { id: "mike-gesicki", name: "Mike Gesicki", position: "TE", team: "CIN", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3116164.png", tier: 11, ecr: 305, adp: 223 },
    "ind-dst": { id: "ind-dst", name: "Indianapolis Colts", position: "DST", team: "IND", photo: dstLogo("ind"), tier: 11, ecr: 306 },
    "charlie-smyth": { id: "charlie-smyth", name: "Charlie Smyth", position: "K", team: "NO", photo: "https://sleepercdn.com/content/nfl/players/thumb/11653.jpg", tier: 11, ecr: 307 },
    "trevor-etienne": { id: "trevor-etienne", name: "Trevor Etienne", position: "RB", team: "CAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/12531.jpg", tier: 11, ecr: 308, adp: 327 },
    "isaiah-bond": { id: "isaiah-bond", name: "Isaiah Bond", position: "WR", team: "CLE", photo: "https://sleepercdn.com/content/nfl/players/thumb/12503.jpg", tier: 11, ecr: 309, adp: 294 },
    "isaac-guerendo": { id: "isaac-guerendo", name: "Isaac Guerendo", position: "RB", team: "SF", photo: "https://sleepercdn.com/content/nfl/players/thumb/11651.jpg", tier: 11, ecr: 310, adp: 350 },
    "jaleel-mclaughlin": { id: "jaleel-mclaughlin", name: "Jaleel McLaughlin", position: "RB", team: "DEN", photo: "https://sleepercdn.com/content/nfl/players/thumb/11439.jpg", tier: 11, ecr: 311 },
    "tahj-brooks": { id: "tahj-brooks", name: "Tahj Brooks", position: "RB", team: "CIN", photo: "https://sleepercdn.com/content/nfl/players/thumb/12543.jpg", tier: 11, ecr: 312, adp: 310 },
    "skyler-bell": { id: "skyler-bell", name: "Skyler Bell", position: "WR", team: "BUF", photo: "https://sleepercdn.com/content/nfl/players/thumb/13402.jpg", tier: 11, ecr: 313, adp: 254 },
    "jake-tonges": { id: "jake-tonges", name: "Jake Tonges", position: "TE", team: "SF", photo: "https://sleepercdn.com/content/nfl/players/thumb/8698.jpg", tier: 11, ecr: 314, adp: 229 },
    "joe-mixon": { id: "joe-mixon", name: "Joe Mixon", position: "RB", team: "FA", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3116385.png", tier: 11, ecr: 315, adp: 259 },
    "jakobi-lane": { id: "jakobi-lane", name: "Ja'Kobi Lane", position: "WR", team: "BAL", photo: "https://sleepercdn.com/content/nfl/players/thumb/13293.jpg", tier: 11, ecr: 316, adp: 248 },
    "jarquez-hunter": { id: "jarquez-hunter", name: "Jarquez Hunter", position: "RB", team: "LAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/11569.jpg", tier: 11, ecr: 317, adp: 354 },

    "audric-estime": { id: "audric-estime", name: "Audric Estime", position: "RB", team: "NO", photo: "https://sleepercdn.com/content/nfl/players/thumb/11579.jpg", tier: 12, ecr: 318 },
    "no-dst": { id: "no-dst", name: "New Orleans Saints", position: "DST", team: "NO", photo: dstLogo("no"), tier: 12, ecr: 319 },
    "kareem-hunt": { id: "kareem-hunt", name: "Kareem Hunt", position: "RB", team: "FA", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3059915.png", tier: 12, ecr: 320, adp: 267 },
    "andrei-iosivas": { id: "andrei-iosivas", name: "Andrei Iosivas", position: "WR", team: "CIN", photo: "https://sleepercdn.com/content/nfl/players/thumb/10226.jpg", tier: 12, ecr: 321, adp: 263 },
    "darnell-washington": { id: "darnell-washington", name: "Darnell Washington", position: "TE", team: "PIT", photo: "https://sleepercdn.com/content/nfl/players/thumb/9479.jpg", tier: 12, ecr: 322, adp: 242 },
    "cedric-tillman": { id: "cedric-tillman", name: "Cedric Tillman", position: "WR", team: "CLE", photo: "https://sleepercdn.com/content/nfl/players/thumb/10444.jpg", tier: 12, ecr: 323, adp: 399 },
    "chi-dst": { id: "chi-dst", name: "Chicago Bears", position: "DST", team: "CHI", photo: dstLogo("chi"), tier: 12, ecr: 324 },
    "jj-mccarthy": { id: "jj-mccarthy", name: "J.J. McCarthy", position: "QB", team: "MIN", photo: "https://sleepercdn.com/content/nfl/players/thumb/11565.jpg", tier: 12, ecr: 325, adp: 282 },
    "will-shipley": { id: "will-shipley", name: "Will Shipley", position: "RB", team: "PHI", photo: "https://sleepercdn.com/content/nfl/players/thumb/11577.jpg", tier: 12, ecr: 326, adp: 369 },
    "jalen-royals": { id: "jalen-royals", name: "Jalen Royals", position: "WR", team: "KC", photo: "https://sleepercdn.com/content/nfl/players/thumb/12505.jpg", tier: 12, ecr: 327, adp: 324 },
    "jahan-dotson": { id: "jahan-dotson", name: "Jahan Dotson", position: "WR", team: "ATL", photo: "https://sleepercdn.com/content/nfl/players/thumb/8119.jpg", tier: 12, ecr: 328, adp: 264 },
    "calvin-austin-iii": { id: "calvin-austin-iii", name: "Calvin Austin III", position: "WR", team: "NYG", photo: "https://sleepercdn.com/content/nfl/players/thumb/8125.jpg", tier: 12, ecr: 329, adp: 306 },
    "tez-johnson": { id: "tez-johnson", name: "Tez Johnson", position: "WR", team: "TB", photo: "https://sleepercdn.com/content/nfl/players/thumb/12485.jpg", tier: 12, ecr: 330, adp: 289 },
    "luke-mccaffrey": { id: "luke-mccaffrey", name: "Luke McCaffrey", position: "WR", team: "WAS", photo: "https://sleepercdn.com/content/nfl/players/thumb/11650.jpg", tier: 12, ecr: 331, adp: 319 },
    "max-klare": { id: "max-klare", name: "Max Klare", position: "TE", team: "LAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/13278.jpg", tier: 12, ecr: 332, adp: 304 },
    "konata-mumpfield": { id: "konata-mumpfield", name: "Konata Mumpfield", position: "WR", team: "LAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/12718.jpg", tier: 12, ecr: 333, adp: 337 },
    "caleb-douglas": { id: "caleb-douglas", name: "Caleb Douglas", position: "WR", team: "MIA", photo: "https://sleepercdn.com/content/nfl/players/thumb/13296.jpg", tier: 12, ecr: 334, adp: 252 },
    "olamide-zaccheaus": { id: "olamide-zaccheaus", name: "Olamide Zaccheaus", position: "WR", team: "ATL", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3917914.png", tier: 12, ecr: 335, adp: 322 },
    "jalen-tolbert": { id: "jalen-tolbert", name: "Jalen Tolbert", position: "WR", team: "MIA", photo: "https://sleepercdn.com/content/nfl/players/thumb/8117.jpg", tier: 12, ecr: 336, adp: 250 },
    "mac-jones": { id: "mac-jones", name: "Mac Jones", position: "QB", team: "SF", photo: "https://sleepercdn.com/content/nfl/players/thumb/7527.jpg", tier: 12, ecr: 337, adp: 296 },
    "noah-gray": { id: "noah-gray", name: "Noah Gray", position: "TE", team: "KC", photo: "https://sleepercdn.com/content/nfl/players/thumb/7828.jpg", tier: 12, ecr: 338, adp: 323 },
    "elijah-arroyo": { id: "elijah-arroyo", name: "Elijah Arroyo", position: "TE", team: "SEA", photo: "https://sleepercdn.com/content/nfl/players/thumb/12521.jpg", tier: 12, ecr: 339, adp: 273 },
    "bam-knight": { id: "bam-knight", name: "Bam Knight", position: "RB", team: "ARI", photo: PLACEHOLDER_PHOTO, tier: 12, ecr: 340 },
    "cole-kmet": { id: "cole-kmet", name: "Cole Kmet", position: "TE", team: "CHI", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4258595.png", tier: 12, ecr: 341, adp: 286 },
    "tyler-higbee": { id: "tyler-higbee", name: "Tyler Higbee", position: "TE", team: "LAR", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/2573401.png", tier: 12, ecr: 342, adp: 376 },
    "xavier-hutchinson": { id: "xavier-hutchinson", name: "Xavier Hutchinson", position: "WR", team: "HOU", photo: "https://sleepercdn.com/content/nfl/players/thumb/10218.jpg", tier: 12, ecr: 343, adp: 325 },
    "eli-heidenreich": { id: "eli-heidenreich", name: "Eli Heidenreich", position: "RB", team: "PIT", photo: "https://sleepercdn.com/content/nfl/players/thumb/13423.jpg", tier: 12, ecr: 344, adp: 315 },
    "dawson-knox": { id: "dawson-knox", name: "Dawson Knox", position: "TE", team: "BUF", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3930086.png", tier: 12, ecr: 345, adp: 272 },
    "donte-thornton-jr": { id: "donte-thornton-jr", name: "Dont'e Thornton Jr.", position: "WR", team: "LV", photo: "https://sleepercdn.com/content/nfl/players/thumb/12541.jpg", tier: 12, ecr: 346, adp: 330 },
    "jmari-taylor": { id: "jmari-taylor", name: "J'Mari Taylor", position: "RB", team: "JAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/13348.jpg", tier: 12, ecr: 347, adp: 339 },
    "michael-mayer": { id: "michael-mayer", name: "Michael Mayer", position: "TE", team: "LV", photo: "https://sleepercdn.com/content/nfl/players/thumb/9482.jpg", tier: 12, ecr: 348, adp: 246 },
    "joshua-palmer": { id: "joshua-palmer", name: "Joshua Palmer", position: "WR", team: "BUF", photo: "https://sleepercdn.com/content/nfl/players/thumb/7670.jpg", tier: 12, ecr: 349, adp: 301 },
    "brenen-thompson": { id: "brenen-thompson", name: "Brenen Thompson", position: "WR", team: "LAC", photo: "https://sleepercdn.com/content/nfl/players/thumb/13380.jpg", tier: 12, ecr: 350, adp: 284 },
    "jatavion-sanders": { id: "jatavion-sanders", name: "Ja'Tavion Sanders", position: "TE", team: "CAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/11600.jpg", tier: 12, ecr: 351, adp: 274 },
    "carson-beck": { id: "carson-beck", name: "Carson Beck", position: "QB", team: "ARI", photo: "https://sleepercdn.com/content/nfl/players/thumb/13272.jpg", tier: 12, ecr: 352, adp: 255 },
    "jawhar-jordan": { id: "jawhar-jordan", name: "Jawhar Jordan", position: "RB", team: "HOU", photo: "https://sleepercdn.com/content/nfl/players/thumb/11588.jpg", tier: 12, ecr: 353, adp: 380 },
    "nick-chubb": { id: "nick-chubb", name: "Nick Chubb", position: "RB", team: "FA", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3128720.png", tier: 12, ecr: 354 },
    "demario-douglas": { id: "demario-douglas", name: "DeMario Douglas", position: "WR", team: "NE", photo: "https://sleepercdn.com/content/nfl/players/thumb/9501.jpg", tier: 12, ecr: 355, adp: 335 },
    "john-metchie-iii": { id: "john-metchie-iii", name: "John Metchie III", position: "WR", team: "CAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/8147.jpg", tier: 12, ecr: 356, adp: 366 },
    "car-dst": { id: "car-dst", name: "Carolina Panthers", position: "DST", team: "CAR", photo: dstLogo("car"), tier: 12, ecr: 357 },
    "ty-simpson": { id: "ty-simpson", name: "Ty Simpson", position: "QB", team: "LAR", photo: "https://sleepercdn.com/content/nfl/players/thumb/13275.jpg", tier: 12, ecr: 358, adp: 318 },
    "bryce-lance": { id: "bryce-lance", name: "Bryce Lance", position: "WR", team: "NO", photo: "https://sleepercdn.com/content/nfl/players/thumb/13420.jpg", tier: 12, ecr: 359, adp: 288 },
    "kendrick-bourne": { id: "kendrick-bourne", name: "Kendrick Bourne", position: "WR", team: "ARI", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3045523.png", tier: 12, ecr: 360, adp: 287 },
    "justin-fields": { id: "justin-fields", name: "Justin Fields", position: "QB", team: "KC", photo: "https://sleepercdn.com/content/nfl/players/thumb/7591.jpg", tier: 12, ecr: 361, adp: 275 },
    "michael-carter": { id: "michael-carter", name: "Michael Carter", position: "RB", team: "TEN", photo: "https://sleepercdn.com/content/nfl/players/thumb/7607.jpg", tier: 12, ecr: 362, adp: 395 },
    "treylon-burks": { id: "treylon-burks", name: "Treylon Burks", position: "WR", team: "WAS", photo: "https://sleepercdn.com/content/nfl/players/thumb/8135.jpg", tier: 12, ecr: 363, adp: 295 },
    "noah-fant": { id: "noah-fant", name: "Noah Fant", position: "TE", team: "NO", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/4036131.png", tier: 12, ecr: 364, adp: 367 },
    "nick-westbrook-ikhine": { id: "nick-westbrook-ikhine", name: "Nick Westbrook-Ikhine", position: "WR", team: "IND", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3929785.png", tier: 12, ecr: 365, adp: 333 },
    "kalif-raymond": { id: "kalif-raymond", name: "Kalif Raymond", position: "WR", team: "CHI", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/2973405.png", tier: 12, ecr: 366, adp: 332 },
    "raheim-sanders": { id: "raheim-sanders", name: "Raheim Sanders", position: "RB", team: "CLE", photo: "https://sleepercdn.com/content/nfl/players/thumb/12472.jpg", tier: 12, ecr: 367 },
    "anthony-richardson-sr": { id: "anthony-richardson-sr", name: "Anthony Richardson Sr.", position: "QB", team: "IND", photo: "https://sleepercdn.com/content/nfl/players/thumb/9229.jpg", tier: 12, ecr: 368, adp: 305 },
    "justin-joly": { id: "justin-joly", name: "Justin Joly", position: "TE", team: "DEN", photo: "https://sleepercdn.com/content/nfl/players/thumb/13400.jpg", tier: 12, ecr: 369, adp: 303 },
    "austin-ekeler": { id: "austin-ekeler", name: "Austin Ekeler", position: "RB", team: "FA", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3068267.png", tier: 12, ecr: 370, adp: 239 },
    "jaylin-lane": { id: "jaylin-lane", name: "Jaylin Lane", position: "WR", team: "WAS", photo: "https://sleepercdn.com/content/nfl/players/thumb/12641.jpg", tier: 12, ecr: 371, adp: 302 },
    "kavontae-turpin": { id: "kavontae-turpin", name: "KaVontae Turpin", position: "WR", team: "DAL", photo: "https://sleepercdn.com/content/nfl/players/thumb/8917.jpg", tier: 12, ecr: 372, adp: 280 },
    "zavion-thomas": { id: "zavion-thomas", name: "Zavion Thomas", position: "WR", team: "CHI", photo: "https://sleepercdn.com/content/nfl/players/thumb/13411.jpg", tier: 12, ecr: 373, adp: 268 },
    "savion-williams": { id: "savion-williams", name: "Savion Williams", position: "WR", team: "GB", photo: "https://sleepercdn.com/content/nfl/players/thumb/12482.jpg", tier: 12, ecr: 374, adp: 277 },
    "eli-raridon": { id: "eli-raridon", name: "Eli Raridon", position: "TE", team: "NE", photo: "https://sleepercdn.com/content/nfl/players/thumb/13421.jpg", tier: 12, ecr: 375, adp: 291 },
    "tyler-bass": { id: "tyler-bass", name: "Tyler Bass", position: "K", team: "BUF", photo: "https://a.espncdn.com/i/headshots/nfl/players/full/3917232.png", tier: 12, ecr: 376 },
    "luke-musgrave": { id: "luke-musgrave", name: "Luke Musgrave", position: "TE", team: "GB", photo: "https://sleepercdn.com/content/nfl/players/thumb/9481.jpg", tier: 12, ecr: 377, adp: 364 },
};

// Helper function to get all players as an array
export const getAllPlayers = () => {
    return Object.values(playerDatabase);
};
